export const COLD: readonly string[] = [
  "It's tits-cold out. Layer the hell up.",
  "Cold enough to freeze your balls off. Plan accordingly.",
  "Your nostrils are gonna stick together. Enjoy!",
  "This is 'nipples could cut glass' weather.",
  "Fuck, it's cold. Find a fireplace and a bottle of something.",
  "Put on real pants. I mean it.",
  "Bundle up like your mom's watching. She'd be horrified by your jacket choices.",
  "The cold doesn't care about your fashion sense. Neither does frostbite.",
  "Thirty-four degrees. That's not a temperature, that's a threat.",
  "Your extremities called. They're pissed.",
  "This weather is giving main character energy, and the main character is hypothermia.",
  "A hoodie won't cut it today. A hoodie will betray you.",
  "Cold enough that your dog looks at you with actual pity when you grab the leash.",
  "Layers. Multiple. Not just two. Think ogre, think onion.",
  "Even your coffee is scared of going outside.",
  "It's the kind of cold that makes you question every life choice that led you here.",
  "Grab a coat or grab some regrets. Your call.",
  "Breath visible, patience invisible. Welcome to winter.",
  "The air has an attitude problem today. Dress like it owes you money.",
  "You'll want gloves unless you enjoy the sensation of raw chicken hands.",
  "Cold enough that birds are walking instead of flying to conserve heat.",
  "Your face is about to get a wake-up call it didn't ask for.",
  "Every step outside is a small act of bravery or a large act of stupidity.",
  "Don't underestimate it. This cold is petty and it has all day.",
  "Thirty degrees and no remorse.",
  "Your toes are going to have opinions about this. Thermal socks, asshole.",
  "It's scarecrow-hat weather. Put something on your head, for the love of god.",
  "Winter woke up and chose violence.",
  "The cold front moved in like an unwanted houseguest and it's not leaving.",
  "You'll be saying 'holy shit' the moment that door opens. Brace yourself.",
  "Hot take: stay inside. Cold take: also stay inside.",
  "Your skin would like to file a formal complaint.",
  "This is the weather that turns normal people into thermostat vigilantes.",
  "Put on a hat unless you enjoy a 40% heat loss through your thick skull.",
  "Not quite frostbite weather, but frostbite is warming up in the bullpen.",
  "Dress for the weather, not for the 'gram. The gram won't keep you warm.",
  "Mother Nature has entered her villain era.",
  "It's sweater-weather if 'sweater' means a full-on parka.",
  "Even the squirrels look annoyed.",
  "Your car door handle is a trap. You'll understand in about twenty minutes.",
  "Cold enough to make you hate literally everything.",
  "Fleece-lined or bust.",
  "Jack Frost can eat a whole bag of dicks today.",
  "This is the weather your ancestors built log cabins to escape. Be like your ancestors.",
  "Your lips are about to chap like they have a grudge against you.",
  "Good news: it's bracing. Bad news: 'bracing' is a polite word for 'awful.'",
  "The wind chill is not a vibe.",
  "Cold enough that your car takes ten full minutes to decide if it wants to cooperate.",
  "Thermal underwear isn't embarrassing. Frostbitten toes are.",
  "This air isn't fresh. It's hostile.",
  "Every exposed inch of skin is currently filing a grievance.",
  "Winter said 'hold my beer' and then immediately froze the beer.",
  "Your lungs are going to be surprised. And not pleasantly.",
  "Dress for warmth, not for dignity. Dignity is a summer luxury.",
  "NASA has warmer environments than your commute right now.",
  "Hot chocolate is not a want today. It's a medical need.",
  "Your body heat is already planning its resignation letter.",
  "Don't let the sunshine fool you. The sun is lying. It does this.",
  "It's the kind of cold that makes strangers bond over mutual suffering.",
  "Layer one: sanity. Layer two: also sanity. Layer three: a coat.",
  "The cold is here and it's making plans for your extremities.",
  "Real talk: your current jacket isn't enough. Add another. Then one more.",
  "This temperature exists to test you. You are failing.",
  "Scarf. Gloves. Hat. This is not optional. This is survival.",
  "Your steering wheel is going to feel like a frozen cactus.",
  "Even penguins have the sense to huddle in weather like this.",
  "Put the thin jacket back. I watched you grab it. Put it back.",
  "Cold enough to make a hot shower feel genuinely spiritual.",
  "This is not the weather for sandals. This is not the weather for any feelings of optimism.",
  "The cold is making promises it will absolutely keep.",
  "Get a thicker coat or get humbled by the elements. Same outcome.",
  "You are biologically warm-blooded. Act like it today.",
  "There's no shame in a neck gaiter. There's only shame in frozen ears.",
  "Every Floridian who ever bragged would not survive this morning.",
  "Your fingers will be useless in about four minutes of exposure. Plan tasks accordingly.",
  "Cold as hell, which, fun fact, is technically an oxymoron today.",
  "The kind of cold that makes you question your ZIP code choices.",
  "This is Narnia weather. Lions, witches, and also hypothermia.",
  "Your balls, if applicable, would like a word about your thermostat.",
  "Even the cats are judging you for going out in this.",
  "Thirty-four degrees Fahrenheit: God's passive-aggressive note.",
  "Dress warm or explain to the ER why you didn't.",
  "This is not a 'tough it out' situation. This is a 'wear all the things' situation.",
  "Cold enough that breathing outside feels like chugging ice water through your face.",
  "The cold front gives zero fucks about your schedule.",
  "Your nose hairs are going to do something weird. You'll see.",
  "Hot soup. Warm blanket. Heavy coat. This is the holy trinity today.",
  "If you're wearing shorts right now, we need to talk.",
  "Cold enough that your smart watch has sent you a concerned wellness check.",
  "Every cell in your body is requesting a transfer to a warmer climate.",
  "This weather requires layers the way your problems require therapy.",
  "Even the cold itself seems pissed off about how cold it is.",
  "Don't mistake the clear sky for good news. The sky is lying to you.",
  "Your inner child wants to play in this. Your inner adult says absolutely not.",
  "Put on a coat or become one of those people who says 'I never get cold.' No one likes those people.",
  "Cold enough that your Netflix queue looks more appealing than ever.",
  "Every thermostat in a ten-mile radius is in high demand right now.",
  "The air tastes like regret and winter.",
  "You'll need gloves to operate your phone. Modern problems, ancient cold.",
  "The sun is out but it is a liar and a coward.",
  "Your outdoor cat has already surrendered and is back at the door.",
  "Ice on the windshield. Anger in your heart. Coffee in your hand. You've got this.",
  "Whatever you're wearing, add one more layer. Trust no one. Trust no forecast.",
  "Your toes are going to develop opinions you've never heard before.",
  "Cold enough that words freeze mid-sentence and land on the sidewalk.",
  "The hot take is: go back to bed. The lukewarm take is: wear a coat.",
  "Even your nose is reconsidering its position on your face today.",
  "Thirty-ish degrees and dropping fast, like your motivation to be outside.",
  "Your face will make a sound when it hits this air. Prepare accordingly.",
  "Blanket burrito or tactical thermals. Either way, you'll thank yourself.",
  "Cold enough to make your armpits retreat inward.",
  "It's the kind of cold that turns ambitions into reruns on the couch.",
  "Bundle up or become a cautionary tale.",
  "The temperature dropped like it was embarrassed to be warm.",
  "Grab all the warm things. Prioritize aggressively.",
  "Your breath is visible, which means the cold is bragging.",
  "Cold enough to make a mug of tea feel like a relationship worth having.",
  "It is, objectively, too damn cold for nonsense. Minimize nonsense.",
  "Even thermometers are crying right now.",
  "Cold snap hit like a brick wall wrapped in ice.",
  "Your cheeks are going to glow red whether you like it or not.",
  "This cold has no chill. Ironically.",
  "If it's this cold, God is definitely punishing something.",
  "The forecast says 'cold as hell' and the forecast, for once, is honest.",
  "Put on another layer or spend the next hour vibrating like a human tuning fork.",
  "This is fine. This is absolutely fine. Put on a coat.",
  "Frost on the grass. Ice in your soul. Have a great day, champ.",
  "Cold enough to make you reconsider the entire concept of morning.",
  "Your hoodie has given up. Don't give up too.",
  "The temperature said hold my beer and then drank the beer before it could freeze.",
  "You deserve warmth today. Wear it.",
  "Layer up, Bilbo. Not all who wander are warm.",
  "Cold weather pro tip: pretend you're in a survival movie. You'll dress better.",
  "It's giving ice planet Hoth. Your Tauntaun is not coming.",
  "Your socks matter today. Choose aggressively.",
  "Not cold enough to stay home... but barely.",
  "It's sweater weather if sweater means 'emergency response gear.'",
  "The cold is an experience. A bad one. Prepare.",
  "Ice in the lungs, fire in the spirit, regret in the heart for not wearing more.",
  "Bundle up or regret it. Either way, it's going to be a story.",
  "Thirty-four degrees: the official temperature of 'are you kidding me.'",
  "Your hat is not a decoration today. Your hat is a lifeline.",
  "This is parka country. Respect the parka.",
  "Even Thor would throw on a second layer today.",
  "Your hands need gloves. Your ears need a hat. Your dignity needs layers.",
  "Cold enough to turn ordinary people into dramatic ones.",
  "The freeze is real and it's personal.",
  "Don't be a hero. Wear the scarf.",
  "Cold air hits different at this temperature. It hits like a disappointment.",
  "Your future self, standing outside unprotected, is already cursing your current self.",
  "Every warm room you leave today will feel like a personal betrayal.",
  "It's not the cold that gets you. It's the under-dressing.",
  "Meteorologists call this 'brisk.' The rest of us call it 'bullshit.'",
  "A single blanket is not enough. Stack them like pancakes.",
  "The ice on the steps is not your friend. Watch yourself.",
  "Cold enough to make you appreciate literally every warm thing in your life.",
  "Your nose is already running without your permission. You're welcome.",
  "Dress like you mean it. The cold definitely does.",
  "It's not a drill. It's actually this cold. Act accordingly.",
  "Cheeks red, fingers numb, spirit somehow intact. That's you today.",
  "Cold enough that heated car seats feel like a gift from god.",
  "Even the steam from your coffee looks alarmed.",
  "Suit up, champ. The cold doesn't play favorites.",
  "This temperature is not aspirational. Your outfit should be.",
  "The cold is back. Act surprised if it helps.",
  "Thirty degrees and zero apologies from the sky.",
  "Your warm shower this morning was the last luxury you'll know for hours.",
  "If you don't have a coat, you have a problem. Let's solve it.",
  "Cold enough to make you say 'oof' before you've even stepped off the porch.",
  "Dress for the cold or let the cold dress you. In ice.",
  "Your future self is already mad at your current self for leaving the coat at home.",
  "Ears. Cover them. They're very regretting-it-able.",
  "It's cold enough out here to sober up a brass monkey.",
  "The temperature is below freezing and above 'absolutely not.'",
  "The cold grabbed a mic and it's not letting go.",
  "Cold enough to question why humans ever left caves.",
  "Your thermal socks are not optional. Please consult your thermal socks.",
  "It's thirty-ish degrees and giving zero warm welcomes.",
  "Frostbite is on the menu if you're serving your bare skin to the outdoors.",
  "The air is sharp today. Like, actually sharp.",
  "Cold weather dating tip: nobody's attractive when they're shivering. Bundle up.",
  "The kind of cold that makes dogs give you a 'really?' look at the leash.",
  "Hot drinks. Warm socks. Low expectations for today. You've got a plan.",
  "Cold enough that getting dressed is basically an engineering challenge.",
  "Your outfit has two jobs today: look decent and prevent ice death.",
  "Thirty-four degrees is where fashion goes to die.",
  "It's giving Ice Age cinematic universe, but make it your Tuesday.",
  "Even the radiator is doing its best and deserves your respect.",
  "Cold enough to make a penguin say 'bit much.'",
  "This is where you earn your 'I survived winter' street cred.",
  "Grab a thermos or grab suffering. Same caloric content, different vibes.",
  "Your lips are about to crack and go rogue.",
  "Layers aren't weakness. Layers are survival. Layers are victory.",
  "Cold enough that getting the mail feels like a quest.",
  "The cold is humbling and it does not care about your schedule.",
  "This is what's known as 'deeply inconvenient' weather.",
  "Ice on the windshield is the universe's way of saying 'slow down, dummy.'",
  "Even your alarm clock feels bad for you today.",
  "You need a coat, gloves, and a little bit of spite. Get moving.",
  "Cold enough that your phone's battery is going to tap out before you do.",
];
