export const COOL: readonly string[] = [
  "A little nippy. Grab a hoodie, princess.",
  "Sweater weather, you cozy little goblin.",
  "Cool enough to justify a second coffee. And a third.",
  "Crisp. Like a good apple, or your ex's heart.",
  "Perfect weather for pretending you enjoy jogging.",
  "Hoodie weather has arrived. Honor it.",
  "The air has a bite. Don't be a baby about it.",
  "Cool enough to make you feel alive. Just barely.",
  "Put on a damn layer and go be a functional adult.",
  "It's brisk and beautiful and your excuses are flimsy.",
  "The kind of crisp that clears your sinuses and your bullshit.",
  "Nature's setting the vibe: cozy and mildly hostile.",
  "Not cold enough to suffer. Cold enough to look cute in a hoodie.",
  "This air tastes like it was made somewhere better than this.",
  "Sweater out of the drawer. Coffee in hand. You're winning.",
  "It's that 'one extra layer' kind of day. Don't overthink it.",
  "Cool air, warm drink, questionable life choices. Classic combo.",
  "The kind of weather that makes scarves feel earned.",
  "You're going to feel this in your cheeks. Good. Feel something.",
  "Temps are cool and the leaves are dramatic. Appreciate both.",
  "It's a little chilly. Perfect for looking brooding in a hoodie.",
  "Fall vibes hit different at this temperature. Enjoy the sadness.",
  "Cool enough to feel like autumn even when it isn't.",
  "The air is sharp and your jacket is necessary. You're welcome.",
  "Nip in the air. Hoodie on your body. Balance restored.",
  "Layer up, princess. You're not as tough as you think.",
  "Crisp morning, crisp attitude. Coffee first, opinions later.",
  "Nippy little bastard of a day. Dress accordingly.",
  "The weather is cold and cozy simultaneously. Like a good villain origin story.",
  "Layer weather. The kind of day where your options multiply.",
  "This cold is just cold enough to be fun. Not the bad kind.",
  "Sweater weather: nature's way of saying 'dress like you care.'",
  "The thermometer says layer up. The thermometer is correct.",
  "Brisk conditions. Perfect for a walk where you huff dramatically.",
  "The air is doing that thing where it's cold but you like it.",
  "Excellent hoodie weather. Your hoodie has been waiting for this.",
  "Put something warm on and stop checking if it's warm outside. It isn't.",
  "Cool breeze and a decent reason to visit a coffee shop.",
  "Not quite warm, not quite cold. Your closet is mildly confused.",
  "This is the weather that invented flannel shirts.",
  "Sweater out of storage. Good. It missed you.",
  "Crisp air. The good kind. Like a fresh dollar bill or a clean breakup.",
  "Temperatures are reminding you that comfort has a price: one hoodie.",
  "You will want a light jacket. You will be glad you brought one.",
  "It's giving autumn energy even if the calendar says otherwise.",
  "The kind of cool that makes hot chocolate feel morally necessary.",
  "Your hoodie is judging you for not putting it on already.",
  "Mildly chilly. Maximally hygge. Bring a hot drink.",
  "The temperature whispers 'put something on, idiot.' Listen.",
  "Cool but not cruel. The best kind of cold.",
  "Layering weather. Celebrate by wearing three things at once.",
  "This is peak 'sit outside at a coffee shop and look thoughtful' weather.",
  "Cool air in your lungs, hoodie on your arms, coffee in your hands. Holy trinity.",
  "This temperature is a gentle bully. It wants you to wear a sweater.",
  "The breeze has opinions. Your jacket doesn't care. Put it on.",
  "Nippy with a chance of 'you should have grabbed a jacket.'",
  "Cozy weather for cozy little goblins. You know who you are.",
  "The kind of day where staying inside feels earned.",
  "Just cold enough to feel the change. Just warm enough not to suffer.",
  "Hoodie out. Thermostat stays off. You're a goddamn hero.",
  "Cool and crisp. Like the beginning of a movie where someone goes for a walk.",
  "This is that temperature where you argue with yourself about a jacket. Bring the jacket.",
  "The sweater is calling. Answer the call.",
  "A little bite in the air. Perfect for dramatic walks and deep sighs.",
  "Pull on something warm. The outside wants your company.",
  "You don't need thermals yet. But you might want to know where they are.",
  "This weather smells like the beginning of something. Probably autumn.",
  "Cold enough to appreciate warmth. Warm enough to enjoy the cold.",
  "Hoodie-and-jeans weather. The outfit that built civilization.",
  "The air is fresh and a little rude. Love it.",
  "This temperature is begging you to make soup. Don't disappoint it.",
  "Perfect conditions for being a little goblin wrapped in fleece.",
  "It'll put some color in your cheeks. You need it.",
  "Weather that makes your morning coffee go from optional to mandatory.",
  "The universe is handing you a good reason to own a quality sweater.",
  "The cool air is not a problem. The lack of jacket is the problem.",
  "This is that 'the best part of being outside is coming back in' temperature.",
  "Mild briskness. Peak livability. Go interact with it.",
  "Your extremities will let you know if you under-dressed. They always do.",
  "Slightly chilly, mostly lovely. Two layers and you're golden.",
  "Classic hoodie weather. Wear it with confidence, you comfortable creature.",
  "That first breath of cool morning air. Like a reset button for your face.",
  "It's nippy out here and your sinuses are about to be unblocked for free.",
  "Grab a jacket. The kind you'll be glad you brought, not the kind you'll tie around your waist.",
  "Brisk outside, warm inside your layers. That's the deal. Take it.",
  "Perfect for a walk where you look like you have your life together.",
  "This weather is excellent for thinking. Thinking about putting on a hoodie.",
  "Temperatures say 'not cold, but getting there.' Your wardrobe says 'I see.'",
  "Light jacket energy. Moderate ambition energy. Good combo.",
  "Cool enough to need a layer. Warm enough to not need two. Lucky you.",
  "The crisp air will make you feel alive. The hoodie will keep you that way.",
  "Perfect weather to look at leaves dramatically from a coffee shop window.",
  "It's that temperature where your breath fogs just a little. Look mysterious.",
  "This is the beginning of soup season. Prepare your soup.",
  "The kind of cool that turns ordinary walks into cinematic events.",
  "Not freezing. Not pleasant. It's sweater weather and that's enough.",
  "Grab the layers, princess. The weather is not warming up for you.",
  "A hoodie, some boots, and zero complaints. That's the brief today.",
  "Cool air means your hot drink hits harder. Do the math.",
  "The temperature is a suggestion. The suggestion is: wear something warm.",
  "It's hoodie season. Not parka season. There's a difference. Know it.",
  "Perfect walking temperature if you are dressed for walking, dummy.",
  "This brisk-ass morning deserves a big-ass coffee. Make it happen.",
  "You were born for this exact temperature. You seem like a fall person.",
  "Chilly but manageable. Unlike your inbox.",
  "Less than sixty degrees is hoodie territory. You're in hoodie territory.",
  "The kind of weather that makes flannel feel like a personality.",
  "Good news: light jacket day. Bad news: light jacket is probably dirty.",
  "Fresh and cool like a mint, or like someone who just got dumped and feels weirdly great.",
  "Not cold enough to complain. Just cool enough to layer up and look intentional.",
  "Breezy and nippy. Your jacket knows what to do. Let it.",
  "The cool air is a gift. The hoodie is the bow. Open it.",
  "This temperature is the friend who tells you the truth. Dress for it.",
  "Conditions: pleasantly chilly. Forecast for you: well-dressed or uncomfortable. Pick one.",
  "A crisp little day that rewards preparation. Prepare.",
  "Coffee and a hoodie and a walk. Three things. All accessible. All necessary.",
  "The weather is pulling a light jacket out of your closet for you. Metaphorically.",
  "Excellent conditions for feeling autumnal and wise and slightly melancholy.",
  "Cool enough that your morning jog will feel heroic. Do it. Feel heroic.",
  "The kind of temperature that makes people say things like 'oh wow, this is nice.'",
  "Crisp and cool and pretty great, honestly.",
  "Fresh air with teeth. Dress accordingly or enjoy the teeth.",
  "Hoodie weather is here. Your sweatshirt has been waiting all summer for this.",
  "Not too cold to go outside. Exactly cold enough to dress warm and look great.",
  "You'll want a jacket. The jacket will make you feel ready. Good.",
  "Layer one: whatever you're wearing. Layer two: hoodie. Layer three: confidence.",
  "This is the good kind of cold. The kind that doesn't hurt.",
  "Mild chill. Excellent for thinking about hot things. Like soup. Or your ex.",
  "Grab a sweater, goblin. We're in the chilly-but-not-miserable zone.",
  "The air is doing that crispy fresh thing. Breathe it in. Don't waste it.",
  "Solid B-plus weather. Better with layers. Way better with coffee.",
  "This is 'bundle up and go for a long walk' weather. Emphasis on go.",
  "Cool breezes and questionable life choices. Weather like this demands both.",
  "Slightly cold. Highly cozy potential. One sweater away from perfect.",
  "The universe is offering you a hoodie day. RSVP: yes.",
  "Temps are in the hoodie zone. This is where the good stuff lives.",
  "The weather has opinions. Its opinion is: more layers.",
  "Crisp air, cold nose, warm soul. That's the forecast.",
  "You can feel the season changing and your wardrobe needs to catch up.",
  "This is what people mean when they say they love fall weather. This exact thing.",
  "Put on a layer. It'll make you feel like you've got your shit together.",
  "The cool air smells like cinnamon and disappointment. In the best possible way.",
  "That perfect temperature where you're cold enough to appreciate warmth.",
  "Nippy and delightful. Like a small dog with opinions.",
  "Weather got chilly. Your outfit should follow suit.",
  "The kind of day where you wear a hoodie and feel like you made the right choice.",
  "Cool, clear, and absolutely begging you to get a pumpkin spice something.",
  "Temperature's dropping the hints. The hint is a sweater.",
  "Not coat weather. Not T-shirt weather. Hoodie weather. The best weather.",
  "The air is cold and honest. Like a good friend with no filter.",
  "Feel that chill? That's the universe telling you to layer up or shut up.",
  "Brisk but not bitter. Refreshing, even. Look at you, refreshed.",
  "That hoodie in your closet is about to have its best day. Let it.",
  "Temps are cozy-adjacent. Meet them there.",
  "The temperature is between annoying and great. Closer to great with a sweater.",
  "Colder than you think. Warmer than tomorrow, probably. One jacket fixes everything.",
  "Pull on a hoodie. Become who you were always meant to be.",
  "Cool and breezy. Good jeans weather. Great boot weather.",
  "Morning air with a bite. Your coffee will taste 40% better because of it.",
  "This temperature is trying to protect you. Let it.",
  "Fall is flirting. You have to respond with a sweater.",
  "Cool conditions. Zero sympathy for those who dress like it's summer.",
  "The sweater season is upon us. Greet it with open arms. Preferably covered arms.",
  "A brisk day with all the charm of an autumn postcard.",
  "You will shiver exactly once. Then the hoodie happens. No more shivers.",
  "Outside temperature is sending mixed messages. Decode it with a light jacket.",
  "This is 'hands in hoodie pocket' weather. Honor the tradition.",
  "Chilly and atmospheric. Lean into it.",
  "The world got a little nippier and a lot more interesting. Get out there.",
  "Cool air demands warm drinks. This is non-negotiable.",
  "This weather does not negotiate. You do, however, own a jacket.",
  "Perfect for a walk that starts cold and ends with rosy cheeks and good feelings.",
  "The temperature says 'bring a layer.' You should believe the temperature.",
  "Coat stays home. Hoodie stays on. That's the arrangement.",
  "Not exactly welcoming. But not hostile either. It's hoodie weather. Compromise.",
  "Cool out there. Wear something. Don't be that person.",
  "First half: chilly. Second half: fine once you're moving. Both: better with a hoodie.",
  "The breeze just asked you to please put on a sweater. Politely. Be polite.",
  "Crisp morning air like the opening scene of a movie where things go well.",
  "Hoodie weather doesn't announce itself. It just arrives. It's arrived.",
  "The chill in the air is character-building. Put on a sweater and build some character.",
  "Cool temps are here. Your inner cozy goblin is thrilled.",
  "If a sweater were an excuse, this would be a perfect excuse.",
  "The cold is refreshing, not punishing. There's a difference. Today is the good one.",
  "Cool and clear as a conscience you don't have. Layer up anyway.",
  "Slightly chilly out. Majorly hoodie out. You know the drill.",
  "The kind of temperature that makes you grateful for fleece. And soup. And not skipping the jacket.",
  "Put the hoodie on. Drink the coffee. Go outside. Profit.",
  "Brisk air, warm heart, questionable decision to skip the jacket. Don't skip the jacket.",
  "A good hoodie day. A great coffee day. A fine excuse to be slightly cozy all day.",
  "This temperature exists to remind you that you own a great hoodie. Go get it.",
  "Cool air, bright day, one layer of sanity. That's all you need.",
  "The brisk is real. The brisk is manageable. The brisk rewards you with fresh air.",
  "Temperatures cooler than your attitude. Layer up.",
  "Light jacket. Hot drink. Reasonable expectations. Today's starter pack.",
  "Crisp enough to feel like a fresh start. Dress like one.",
  "You cozy little goblin, this weather was made for you. Go claim it.",
  "Fifty-something degrees and your sweatshirt drawer is calling your name.",
  "The cold air has logged in and is ready to meet your face. Bring a hoodie.",
  "This is not a T-shirt situation. This is a hoodie situation. Adapt.",
  "It's the temperature where coffee becomes a survival tool, not just a beverage.",
];
