export const DEEP_FREEZE: readonly string[] = [
  "It's colder than your ex's heart out there.",
  "Antarctica called — it's honestly impressed.",
  "This is the kind of cold that files a restraining order against your skin.",
  "Frostbite is out here recruiting. Cover up.",
  "Winterfell weather. Stay the fuck inside.",
  "Your snot will freeze mid-sneeze. Science!",
  "Twenty degrees or below. This is not a negotiation.",
  "The cold outside would make a polar bear check the thermostat.",
  "You step outside, the cold steps into you. Aggressively.",
  "Siberia has been reached for comment. It sends its sympathies.",
  "Frostbite isn't a risk at this point. It's an appointment.",
  "Negative wind chills are nature's way of saying 'absolutely not.'",
  "Your exhaled breath will freeze before it gets anywhere. Cool party trick. Terrible experience.",
  "This is survival weather. Dress for survival, not for Starbucks.",
  "The Donner Party had warmer days. Think about that.",
  "It's the kind of cold that kills motivation before it even wakes up.",
  "Exposed skin gets about four minutes before complaining. Loudly.",
  "Even hot soup is nervous about going outside today.",
  "The thermometer bottomed out and then kept going, out of spite.",
  "Your eyelashes might freeze together. This is a real thing. Blink faster.",
  "Thor is inside right now. Even he said hell no.",
  "This cold doesn't care about your tough-guy persona.",
  "The kind of temperature that makes you reevaluate every decision that brought you to this climate.",
  "Bundle up like your entire future depends on it. It might.",
  "Mars is warmer than your front porch today. Not by much, but still.",
  "The frost will bite. Not metaphorically. Actually bite your face.",
  "Your breath looks like a dragon sneeze from the moment you open the door.",
  "Stay inside. I'm not asking. I'm begging. I'm mandating.",
  "This cold is personal. It has a grudge. Against you specifically.",
  "Zero feels balmy from here. We've gone well past zero, friends.",
  "Jack Frost didn't just arrive. He moved in and stopped paying rent.",
  "Your eyelids are going to feel this temperature. That's how bad it is.",
  "Even the ice is complaining that it's too cold.",
  "Dead of winter energy. Dress accordingly. Grieve appropriately.",
  "The forecast says brutal and the forecast is, frankly, underselling it.",
  "Every exposed hair follicle is currently filing for emergency relief.",
  "You'll want hand warmers in every pocket, and one in your soul.",
  "The cold air at this temperature doesn't just sting — it lectures you.",
  "This is what astronauts train not to experience. Outside is that astronaut training.",
  "Layers upon layers. Then another layer. Then question the geographic decisions your ancestors made.",
  "Your car's engine is cold-soaked and resentful. Give it a minute.",
  "It is deeply, aggressively, personally cold outside.",
  "The temperature right now is a hate crime against warmth.",
  "You will understand what 'bone cold' means within thirty seconds of going out.",
  "This is Everest base camp vibes except without the sherpa or the glory.",
  "The wind chill is just the cold showing off at this point.",
  "At these temps, words freeze before they leave your mouth. Write things down.",
  "Your warm blood is now this cold's enemy. It will find every gap in your armor.",
  "Zeus froze the weather in this neighborhood out of spite. Thanks, Zeus.",
  "This cold has ambition. Terrible, frost-bitten ambition.",
  "Even penguins have a limit. We found that limit today.",
  "Twenty degrees below comfortable and descending fast.",
  "Staying inside isn't weakness. It's wisdom wrapped in blankets.",
  "Your facial features will protest this temperature loudly and immediately.",
  "This is what 'too cold to snow' means and it is exactly as awful as it sounds.",
  "The cold front doesn't have a chill side. It's all business.",
  "Put on enough layers that you can't fully bend your elbows. Perfect. Go.",
  "Your internal organs would like to be warmer than this. Please assist.",
  "Ice in the air, ice on the ground, ice in your immediate future if you're not careful.",
  "It's so cold the weather app added a frowning emoji. Even it's upset.",
  "Hypothermia is not a fun plot twist. Dress like you know this.",
  "Mother Nature had a bad day and decided to take it out on your zip code.",
  "The cold has entered the building. Metaphorically and through every crack in your wall.",
  "Stay inside long enough and this becomes someone else's problem.",
  "Bravado won't keep you warm. A down jacket will.",
  "This cold is ancient and powerful and it does not respect your schedule.",
  "Your nose hair is about to do something impressive and involuntary.",
  "The icy wind is practicing its knifelike precision directly on your cheekbones.",
  "If you go out underdressed, you will know exactly why in thirty seconds.",
  "This isn't cold. This is a reckoning.",
  "Layer up. Then layer up again. Then question the geographic decisions your ancestors made.",
  "The ice on everything is not decorative. It is hazardous. Watch your ass.",
  "Frigid beyond reason, windy beyond mercy.",
  "Even ghosts are staying inside today. That should tell you something.",
  "The cold reached sub-20 and kept going because it had more to say.",
  "Your blood, if polled, would vote unanimously to go back to bed.",
  "This weather exists in the gap between 'extreme' and 'actually ridiculous.'",
  "Snow's prettier from inside a window. Coincidence? No.",
  "Frost on every surface, freeze in every breath, regret in every step.",
  "The kind of cold where even your socks aren't enough. Invest in boots.",
  "All your warm dreams last night were a cruel joke the universe prepared.",
  "At this temperature, your body's warmth is a finite resource. Protect it.",
  "The Starks were right. Winter is here and it brought reinforcements.",
  "This cold makes you rethink what it even means to be outside.",
  "Exposed face? Bold choice. Bold, terrible, wrong choice.",
  "The temperature right now is technically a character flaw of this city.",
  "Your thermostat is the most important relationship you have today.",
  "Wool, fleece, down. The holy trinity. Assemble the trinity immediately.",
  "Wind plus below freezing equals the universe's least fun math problem.",
  "This is the weather Norse mythology was invented to explain and fear.",
  "Your warmest coat isn't warm enough. Wear it anyway plus more.",
  "There is no triumph in suffering this cold underdressed. Only frostbite.",
  "The cold doesn't give a damn about your commute. It will be there.",
  "Even the sun came out today and said 'not my problem.'",
  "Thermal everything. This is not a drill. This is a thermal situation.",
  "Your skin has human rights and they currently include staying inside.",
  "Every inch of exposed skin is a mistake waiting to happen.",
  "The ground is frozen. The air is frozen. Your patience should be too by now.",
  "Cold so dense you could lean against it. Don't, but you could.",
  "This is the cold that makes snowmen look warm by comparison.",
  "Hades is warmer today. The truly dead have it better.",
  "It's the kind of cold that sticks around and overstays every welcome.",
  "Don't open the door unless you have to. And if you have to: full battle rattle.",
  "The wind at these temperatures is attempting to remove your face from your skull.",
  "You thought cold was a spectrum. It is. You're at the wrong end.",
  "Even fire wants to be inside today.",
  "Full face coverage or full face regret. Those are the only options.",
  "It's so cold that metal surfaces have become traps. Gloves. Always gloves.",
  "Deep freeze: the season where your car tells you to go fuck yourself every morning.",
  "Your extremities are already planning their grievances. Don't give them ammunition.",
  "Layer up like you're heading to the surface of Neptune for a casual jog.",
  "The cold is ferocious, unhurried, and absolutely indifferent to your feelings.",
  "Good news: you'll build character. Bad news: character doesn't keep you warm.",
  "This cold will find you no matter how many layers you try. Add more anyway.",
  "Every thermometer in town is reading this with a sense of personal offense.",
  "Winter is not fucking around today. Return the favor. Bundle up.",
  "The polar vortex is not a myth. You are living inside one right now.",
  "At this temperature, coffee loses heat before you can finish the mug. Drink faster.",
  "Your warm car is your most important ally. Treat it with respect.",
  "The cold has audacity. Dress with matching audacity.",
  "There is no 'tough it out' at sub-20. There is only 'dress right.'",
  "Your eyeballs will feel this temperature. That should concern you.",
  "Winter took a deep breath and breathed all over your zip code.",
  "The frost crept up to the windows to watch you make bad wardrobe choices.",
  "If the weather report scared you this morning, it was correct.",
  "Cold that makes your knees hurt is a special kind of brutal. Today is that kind.",
  "The wind chill made the temperature worse and then laughed about it.",
  "Sub-20 is a number with consequences. Treat it accordingly.",
  "Even the icicles look tired of this.",
  "Your commute is going to be a small war against the elements. Pack accordingly.",
  "No amount of pride will make you warmer. Humility looks like a parka today.",
  "It's the kind of cold that makes you miss places you've never been.",
  "Cold so real it'll change your personality for the rest of the day.",
  "Your nostrils are a liability at this temperature. Scarf up to the nose.",
  "Outdoor plans are canceled. Canceled by the atmosphere. No refunds.",
  "Everything metal is a weapon against your skin right now. Respect that.",
  "The deep freeze has settled in like a bad houseguest with no self-awareness.",
  "This cold has been building this moment since October. It's been patient.",
  "Your feet will complain from the parking lot onward. Lined boots. Now.",
  "Hypothermia at this temp doesn't require stupidity, just insufficient layers.",
  "The weather made poor choices for your zip code. You don't have to.",
  "The wind hits different when it's sub-20. Hits like a brick wall of ice.",
  "Your warm bed this morning was not a mistake. Going out might be.",
  "Ymir himself would have something rude to say about this weather.",
  "It is simply too cold for anything but essential movement. Move essentially.",
  "Cold this extreme is practically alive. And it's hungry.",
  "Your metabolism is working overtime just to keep core temp stable. Feed it.",
  "Put on all the things. I don't care what they match. Fashion is not the goal today.",
  "The cold settled into the streets last night and claimed them as territory.",
  "If 'cold as balls' had a second act, this is it.",
  "Frozen pipes are possible. So is a frozen you. Similar fix: insulation.",
  "The cold front dropped in like an uninvited guest at 3am and it's still here.",
  "Dress like you have a reason to survive the walk to your car.",
  "Exposed cheeks will be red. Exposed ears will regret it. Everything else: bold choice.",
  "The cold woke up today with a purpose. That purpose is your discomfort.",
  "Your fingers in this cold go from numb to 'where are my fingers?' fast.",
  "The whole outdoors is basically a freezer that forgot to label what's inside.",
  "If you see your breath and also see it freeze in place, you're in the danger zone.",
  "Mittens. Hat. Scarf. Coat. Boots. You are now approximately warm enough.",
  "This cold took personal offense to this city. No one knows why. Everyone's suffering.",
  "Polar bear weather. And polar bears have fur. You do not. Act accordingly.",
  "The cold is maximum effort today. Please match its energy, but with warmth.",
  "Your face said 'take me outside.' Your face was wrong.",
  "If you go out like you usually do, you'll come back personally offended by winter.",
  "The kind of cold that makes 32 degrees feel like a beach vacation.",
  "Today's temperature is a masterclass in 'maybe not.'",
  "This cold makes the air feel thicker, denser, and personally hostile.",
  "Your warm drink is a weapon. Wield it every thirty minutes.",
  "The deep freeze arrived. It did not knock. It does not plan to leave soon.",
  "Your mittens and your survival instinct should both be fully active right now.",
  "It's not 'just cold.' It is existentially cold.",
  "The cold is daring you to underestimate it. Don't take the dare.",
  "This temperature is a full personality. Mostly aggrieved, somewhat murderous.",
  "Wind chill below zero and your confidence should be below that too.",
  "The ice on the road this morning was not decorative. It was a warning.",
  "Your heater is your best friend. Tell it so.",
  "Step outside insufficiently dressed and winter will correct your attitude instantly.",
  "Cold beyond reason, past the point of discomfort and into the realm of deeply personal.",
  "The freeze event has started. All schedules are now subordinate to it.",
  "This air will steal your warmth and walk away without an apology.",
  "Somewhere in this cold there's a lesson. You'll learn it in about forty seconds.",
  "The deep freeze does not negotiate. It simply freezes.",
  "It's the kind of cold where your brain says 'back to bed' and your body says 'agreed.'",
  "Cold of this magnitude has its own gravitational pull, back toward your couch.",
  "Outside is a frostbite museum and you're about to become an exhibit.",
  "Your ancestors, staring down weather like this, would have stayed home. Respect the ancestors.",
  "The type of cold that rewrites your plans, priorities, and your relationship with this city.",
  "This deep freeze is the reason hot tubs were invented. Go find one.",
  "Every outdoor task can wait. The cold, however, cannot wait to get you.",
  "The freeze is absolute and your jacket is not.",
  "Your dignity demands a face covering at this temperature. Put it on.",
  "It is this cold outside: too cold. That is the full report.",
  "Your blood would like to be 98.6 degrees and it's working hard to stay there. Help it.",
  "The cold at this level is not weather anymore. It's a condition. A hostile one.",
  "Defrost the car, defrost your soul, grab a parka, and God help you.",
  "This temperature broke the scale and then kept going.",
  "The cold said 'hold my beer' and then that beer became a solid.",
  "Even Odin took one look at today's forecast and rolled back over.",
  "This deep freeze has a personal vendetta against your morning routine.",
  "Cold so severe your excuses freeze before they leave your mouth.",
];
