export const DRIZZLE: readonly string[] = [
  "Just enough drizzle to be annoying, not enough to matter.",
  "God's spitting on you. Lightly.",
  "That wimpy 'is it even raining?' rain. Yes. Yes it is.",
  "Mist you not — it's damp as hell out.",
  "The sky is doing the least possible amount of raining.",
  "Drizzle: the participation trophy of precipitation.",
  "Barely raining but still somehow making everything worse.",
  "Not quite rain, not quite dry. Nature is being a wishy-washy bastard today.",
  "It's the drizzle that doesn't respect your umbrella decision either way.",
  "Atmospheric dandruff out there. Light but irritating.",
  "The air is basically just wet. Not raining. Just... wet.",
  "Microdrizzle vibes. Your glasses are fogged and your mood is fogged.",
  "The clouds are trying their best. It's not a very good best.",
  "Barely a drizzle but you'll still feel it by the time you get to your car.",
  "Light rain: technically precipitation, spiritually an insult.",
  "God's rinsing the city with a damp cloth. Not helpful. Thanks anyway.",
  "The sky is drooling on you. Gently. Rudely.",
  "Misting outside like nature is trying to set a mood.",
  "This drizzle doesn't have enough confidence to be a real rain.",
  "The universe is spraying you with a light mist to test your patience.",
  "Wet air. Technically speaking. Practically speaking: annoying.",
  "Drizzle so light you might talk yourself out of bringing an umbrella. Don't.",
  "It's not raining, it's crying. Very quietly. Very steadily.",
  "Light rain advisory: your hair is already over it.",
  "The air is just damp enough to ruin a blowout.",
  "Mist hanging in the air like a question nobody asked.",
  "Drizzling like the sky is procrastinating a proper storm.",
  "Damp and grey and softly miserable outside.",
  "Not a storm, not sunshine. Just the dull wet in-between.",
  "Soft drizzle falling like the weather gave up halfway through.",
  "The sky leaked a little. It's embarrassed but continuing.",
  "Drizzle day: too light to justify a coat, too wet to ditch one.",
  "Everything is mildly damp and vaguely sad.",
  "Light precipitation that has committed to neither leaving nor fully arriving.",
  "The rain is here but it's not trying. Zero effort precipitation.",
  "You're going to get that slight dampness that soaks through nothing but still bothers you.",
  "Mist so fine you won't know it got you until you're damp all over.",
  "Drizzle falling at the pace of broken dreams.",
  "Nature is spritzing you like a houseplant. You are not a houseplant.",
  "The sky is halfheartedly doing something wet. Brace for mild annoyance.",
  "Fine mist out there that makes everything feel vaguely British.",
  "Drizzle: the weather equivalent of someone breathing near you loudly.",
  "The raindrops can't commit. They're more of a mist.",
  "A light kiss of rain that you'll hate more than any downpour.",
  "Light drizzle, heavy existential damp.",
  "Mist rolling in because the sky couldn't be bothered to properly rain.",
  "The air is doing that thing where it's basically a cloud at ground level.",
  "Today's moisture: ambient and irritating.",
  "Drizzle so gentle it feels passive-aggressive.",
  "The sort of rain that's technically not raining but technically is.",
  "Your hair will frizz. Not because it's raining. Because the air said so.",
  "Mist ahead. Your hair already knows. It's grieving.",
  "Barely precipitating but absolutely succeeding at dampening everything.",
  "Light rain that doesn't have the guts to be a real storm.",
  "The weather is doing what your coworker does — hovering without committing.",
  "Just a light drizzle. Just enough to make you question all your choices.",
  "Soggy in a non-dramatic way. The worst kind of soggy.",
  "Today's precipitation arrived in mist form and nobody invited it.",
  "Drizzle has very low standards and is absolutely meeting them.",
  "The outside smells like rain but isn't having the decency to be rain.",
  "It's raining exactly enough to mess with you, not enough to cancel anything.",
  "Fine mist. Coarse annoyance.",
  "Everything has that slick wet look without any of the justification.",
  "Tiny rain, big disappointment in your grooming products.",
  "Drizzle outside: wet enough to matter, dry enough to debate.",
  "Mist and drizzle making a soft case for staying the hell inside.",
  "Low-effort precipitation from a high-effort atmosphere.",
  "The sky is leaking. Not gushing. Just leaking.",
  "Drizzle hanging in the air like the lingering memory of a bad decision.",
  "Just a little bit raining, which is somehow worse than a lot of raining.",
  "Damp everywhere but nobody can explain exactly why.",
  "Light drizzle: the Monday morning of weather events.",
  "Fog and drizzle making the world look like a sad painting.",
  "The mist is doing its slow, thorough work on your clothes.",
  "That fine spray that makes windshield wipers go on the slow setting. You know it.",
  "Drizzle day. Technically fine. Spiritually grey.",
  "Everything outdoors is doing that annoying glistening wet thing.",
  "Light rain that doesn't explain itself and doesn't need to.",
  "Barely-there rain that somehow gets everywhere.",
  "The sky is misting like an overconfident perfume salesperson.",
  "Drizzle without remorse.",
  "Everything is that specific texture of damp-but-not-soaked. Still bad.",
  "Rain so light it feels like clouds are just breathing on you.",
  "Soft drizzle, hard feelings about the weather.",
  "The air is wet in that specific way that makes your coat useless.",
  "Light precipitation: not dramatic enough to cancel plans, annoying enough to ruin them.",
  "Mist so thick the streetlights have halos. Poetic. Also damp.",
  "Everything outside is quietly collecting moisture.",
  "The sort of grey wet morning that makes you question your zip code.",
  "Drizzle is here. Umbrella is at home. Classic arrangement.",
  "Fine rain coming down at a weird angle specifically targeting your collar.",
  "Barely raining but fully committing to dampness.",
  "Atmospheric moisture event. Small. Persistent. Annoying as hell.",
  "The sky is rinsing you off. Not a shower. More of a wipe-down.",
  "Drizzle so polite it waits until you're outside to start.",
  "The forecast is: damp, dimly lit, and uninspiring.",
  "Light rain falling like it's doing you a favor. It is not.",
  "Mist you, mist me, mist everybody.",
  "Not raining hard enough to be dramatic. Just hard enough to be unpleasant.",
  "Drizzle forming a thin layer of misery on every outdoor surface.",
  "Fine water droplets suspended in the air because the sky has no follow-through.",
  "It's the 'do I need a hood?' drizzle. You need the hood.",
  "Soft rain falling on everything like the world is getting a light coating.",
  "Dreary and damp. Quintessential nothing weather.",
  "Drizzle so faint you'll try to ignore it until your sock is soaked through.",
  "Mist rolling in to make everything look haunted and vaguely sad.",
  "The sky is doing a light precipitation suggestion. You should take it seriously.",
  "Barely raining. Fully damp. Nature's most annoying compromise.",
  "That specific drizzle that makes you feel 10% wetter than you expect all day.",
  "The clouds couldn't be bothered to rain properly. Overachieving with damp.",
  "Fine mist: nature's way of saying 'you're not having a good hair day today'.",
  "Every outdoor surface now has that slightly wet sheen nobody wanted.",
  "Drizzle with the confidence of someone who knows they're ruining your day.",
  "The rain is barely trying and still winning.",
  "Grey, damp, soft, annoying. Today's weather in four words.",
  "Mist filling the air like the atmosphere forgot how to commit.",
  "The sky is rinsing you lightly. Almost respectfully. Still rude.",
  "Light drizzle making every outdoor task 20% more miserable.",
  "Not enough rain to use the wipers, too much rain to ignore it. Hell.",
  "Drizzle showing up uninvited and making itself comfortable.",
  "Today's vibes: damp and non-committal.",
  "Rain at 15% effort. Still 100% annoying.",
  "The mist is subtle. The damp it leaves behind is not.",
  "Dreary light rain turning the city soft and grey.",
  "Drizzle so gentle it apologizes as it soaks you.",
  "Fine precipitation falling on the just and the unjust alike.",
  "The kind of damp that seeps into your shoes between the house and the car.",
  "Outside is doing that gloomy wet thing where everything looks dim.",
  "Mist you not — this is going to be a damp one.",
  "Drizzle with poor timing and no self-awareness.",
  "Just enough water in the air to make your curls a decision.",
  "The outside smells like rain. The outside IS rain. Thin rain.",
  "Rain so subtle your umbrella feels dramatic. Use it anyway.",
  "Drizzle descending steadily with no plan to stop anytime soon.",
  "Low cloud, light mist, strong vibes of 'just stay inside'.",
  "Fine rain that requires neither full umbrella nor full denial.",
  "Today's light precipitation is the weather equivalent of a shoulder shrug.",
  "Drizzle falling like the sky has mild regrets.",
  "Thin veil of moisture across everything outdoor. Very annoying.",
  "Light rain advisory: your jacket is working overtime today.",
  "Everything is slick without being properly wet. Confusing. Dangerous.",
  "The drizzle doesn't announce itself. It just slowly ruins your afternoon.",
  "Damp day. Damp mood. Damp commute. Damp everything.",
  "Mist so pervasive it feels personal.",
  "Drizzle: precipitation that doesn't have the confidence of rain or the clarity of sun.",
  "A fog of light rain settling over the city. Cozy if you're inside. Terrible if not.",
  "Light rain. Heavy damp. Middling enjoyment of the outdoors.",
  "The clouds are leaking. Not flooding. Just... leaking.",
  "Drizzle making slow, steady progress on soaking your cuffs.",
  "Soft rain, soft complaints, soft refusal to go outside.",
  "Rain at its most passive-aggressive: barely there, totally annoying.",
  "Misty with a side of 'should I be wearing a hat?'. Yes. Wear the hat.",
  "Fine drizzle turning every hair you own into its own thing.",
  "The city is developing a slick surface. Approach with caution.",
  "Weather report: meh. Moisture report: unfortunately yes.",
  "If you go outside you'll arrive everywhere slightly damp.",
  "Drizzle moving through your neighbourhood at a casual, irritating pace.",
  "Sky doing a half-assed job of raining. Fully achieving annoyance.",
  "That faint hiss of fine rain that fills the air and soaks you over time.",
  "Fog and drizzle doing a tag team on your visibility and your mood.",
  "Light precipitation asking no one's permission to ruin everyone's day.",
  "The mist has opinions about your outfit.",
  "Fine rain falling at the angle specifically designed to miss your umbrella.",
  "Drizzle so soft it's hard to be mad at. But you're mad at it.",
  "Not quite wet enough to matter, not quite dry enough to enjoy.",
  "Low key wet out. The understated bastard of weather types.",
  "Damp air with light rain. Moderate vibe. Poor hair outcomes.",
  "This drizzle is the small talk of weather events: nobody asked for it.",
  "Fine mist making your jacket bead up and your soul feel damp.",
  "Light rain: the kind that promises nothing and delivers dampness.",
  "Drizzle quietly coating every surface. Sneaky little precipitation.",
  "It's barely raining. Barely is still enough to get you.",
  "Overcast and drizzling. The setting of every sad indie film.",
  "Rain too light to respect, heavy enough to defeat you.",
  "The mist doesn't care if you noticed it. It's still soaking you.",
  "Drizzle creeping in like an apology that doesn't actually fix anything.",
  "Damp, grey, and vaguely dispiriting. Just another day in the mist.",
  "Fine rain doing fine damage to your fine hair.",
  "Light drizzle confirming that outside was never the right choice today.",
  "The atmosphere is misty and the forecast is: bring a hood.",
  "Drizzle without drama. The most insidious kind.",
  "Mist settling in for the long haul. Pack accordingly.",
  "Barely raining and yet somehow ruining everything.",
  "Today's precipitation is light, persistent, and deeply committed to dampness.",
  "Drizzle so faint you'll talk yourself out of a hood. The hood was the right call.",
  "Low mist and fine rain making everything feel like a 19th-century novel.",
  "The dampness today is not optional, it's environmental.",
  "Drizzle falling on the righteous and the unrighteous. Mostly on you though.",
  "Fine rain turning every surface into a slightly treacherous version of itself.",
  "The outside is doing quiet wet chaos. Don't be part of it.",
  "Mist: technically not rain, practically: also rain.",
  "Drizzle so understated you'll forget about it until your underwear is damp.",
  "Light precipitation building a slow, steady case for staying inside.",
  "The clouds are sweating on you. That's the drizzle.",
  "Today the rain said 'I'll just do a little'. It lied.",
  "Mist like a damp secret the weather is keeping from your jacket.",
  "Drizzle: the stealthiest way the sky can ruin your plans.",
  "Fine rain at every angle your umbrella doesn't cover.",
  "Something wet is happening and it's aimed at you.",
  "Drizzle so relentless it's basically just a commitment to dampness.",
];
