export const FOG: readonly string[] = [
  "Foggy as hell. Visibility: my future.",
  "Spooky-ass fog out there. Watch for horror-movie villains.",
  "Can't see shit. Drive slow, genius.",
  "It's giving 'Silent Hill.' Be careful.",
  "The fog is so thick you could cut it with a knife. Or get cut by whatever's in it.",
  "Low visibility fog advisory. Your headlights are doing their best. It's not enough.",
  "Pea soup fog. The kind of morning where you drive by feel and hope.",
  "Fog this thick is nature putting on a horror show. You're the opening scene.",
  "Visibility near zero. Slow down before something slow doesn't slow down for you.",
  "Something's out there in the fog. Statistically it's just a mailbox. Statistically.",
  "Fog rolling in thick. This is how every Stephen King story starts.",
  "Drive with your fog lights on. No fog lights? Dignity and prayer. That's your kit.",
  "The fog doesn't care about your schedule. The fog is on the fog's schedule.",
  "Can't see ten feet ahead. Great conditions for trusting the process. Terrible for driving.",
  "That eerie silence that comes with fog is very cool and also mildly terrifying.",
  "Fog this thick means you're technically driving by faith today.",
  "Something lurks in the fog. It's probably your neighbor's badly parked truck. Probably.",
  "Every pedestrian out there is a jump scare waiting to happen. Slow way down.",
  "Visibility this low means high beams bounce back and blind you. Use low beams.",
  "The fog is atmospheric as hell. You'd appreciate it more if you weren't late.",
  "Fog turned the whole town into a moody film set. Except the film is your commute.",
  "Anything could be out there in the fog. Trees. Cars. That guy from The Mist.",
  "Morning fog: the universe's way of making everything ominous before coffee.",
  "If you can't see it, it can still see you. Probably. Fog is weird like that.",
  "The fog wrapped around everything like a wet, cold mystery.",
  "Low-visibility morning. High-anxiety commute. Perfect.",
  "Fog like this turns your neighborhood into a John Carpenter production.",
  "Thick fog and morning commutes are a pairing that belongs in a trauma memoir.",
  "The kind of fog where you slow down and the car behind honks. That driver is wrong and dangerous.",
  "Fog so dense even the GPS sounds unsure of itself.",
  "Your turn signal is your only communication with the universe right now. Use it.",
  "Fog gives everything the vibes of a place that definitely has ghosts.",
  "Morning fog rolling in: peaceful. Trying to drive in it: deeply not peaceful.",
  "Whole city disappeared in the fog. Could be building character. Could be a horror plot.",
  "Visibility: poor to none. Plans: adjustable. Commute: longer than expected.",
  "Fog like this is basically the atmosphere deciding to keep its plans to itself.",
  "Drive slow. Turn on your lights. Don't be the reason someone writes a sad story.",
  "This fog is so thick the GPS is probably sweating.",
  "Fog is beautiful and creepy and a deeply impractical way to start the day.",
  "Reduce speed. Increase following distance. Decrease confidence. That's today's instruction set.",
  "Low visibility means high stakes at every single movement of your car.",
  "It's the kind of fog that makes you whisper even when you're alone.",
  "Dense fog advisory issued. The universe is being theatrical about it.",
  "If this were a movie, someone would be running from something in this fog. Drive carefully.",
  "The fog turned the whole neighborhood into a gothic painting nobody commissioned.",
  "Fog-covered roads are best navigated slowly, carefully, with no faith in other drivers.",
  "Something is lurking in that fog. It's your parking spot. You can't find it.",
  "Dense fog: when the atmosphere decides to be deliberately mysterious.",
  "Your windshield will fog up too, because of course it will. Defroster on.",
  "Fog is water vapor but its vibe is pure supernatural menace.",
  "The road disappears into white. You're going to need more than headlights.",
  "Today's aesthetic: Victorian ghost story. Today's commute: correspondingly difficult.",
  "Fog doesn't care how late you are. Fog operates outside of time.",
  "Walk with your arms slightly out if you can't see your feet. Look ridiculous. Survive.",
  "Dense fog advisory: nature reminding you it can make you disappear whenever it wants.",
  "The fog is so thick it has texture. That's not a good sign.",
  "One wrong turn in this fog and you're in a different zip code or a supernatural dimension.",
  "Slow down. Then slow down again. Then consider parking and waiting.",
  "Fog like this is the sky saying 'I need some privacy right now.'",
  "No, you can't see through it. No, your high beams won't help. Drive slow.",
  "Visibility: minimal. Vibes: deeply ominous.",
  "This fog is so thick the birds are flying by instrument.",
  "Everything past 30 feet is theory. Navigate accordingly.",
  "Fog turned the highway into a mystery novel and you're the unsuspecting protagonist.",
  "Your car is a ghost in someone else's fog-drive. Be a visible ghost. Lights on.",
  "Fog advisory: proceed like everything could be right in front of you because it could.",
  "The fog smells like cold mystery and poor road conditions.",
  "Dense fog plus quiet street equals the first scene of a thriller you didn't audition for.",
  "Turn on your lights. Not your high beams. Your fog lights or low beams. Details matter today.",
  "Can't see the end of the road. Can't see the end of your problems. One of those is fog's fault.",
  "Fog this heavy makes every mundane object look ominous. That's a mailbox. Definitely a mailbox.",
  "Your headlights punch a small hole in the fog and reveal... more fog. Classic.",
  "Fog turns joggers into ghost shapes that materialize suddenly. Watch for them.",
  "Something moves in the fog. That's called 'other cars.' Still terrifying. Still slow down.",
  "This fog rolled in silently and it brought zero visibility with it. Rude entrance.",
  "The whole road vanishes into fog like it has somewhere to be and isn't telling you.",
  "Thick fog means you stop being a driver and start being a cautious suggestion on wheels.",
  "Visibility so bad that even your GPS sounds hesitant.",
  "Dense fog mornings call for headlights, slow speeds, and healthy respect for the unknown.",
  "The trees look like they're hovering. The road looks like it ends. Keep driving. Carefully.",
  "You know that calm feeling before something goes wrong? That's fog weather.",
  "A dense fog advisory means the weather service also can't see what's coming. Comforting.",
  "Fog this thick turns every intersection into a trust exercise.",
  "Spooky fog doesn't scare the birds away because birds are braver than you. Learn from the birds.",
  "Slow your roll. The fog has absorbed the road markings and the concept of speed limits.",
  "Fog creates a whole dramatic atmosphere completely incompatible with arriving on time.",
  "That's not mist. That's fog. That's a lot of fog. Drive accordingly.",
  "Fog does not reward speed. Fog rewards patience and appropriate following distance.",
  "Everything has that 'last seen before the disappearance' quality today.",
  "Dense fog: the condition that makes everyone slow down except the one guy who still doesn't.",
  "Fog on the bridge means the bridge is gone and you might as well believe it.",
  "Your windshield is fogging from the inside too. Defroster. Now. Immediately.",
  "The fog is so thick your morning commute is now a supernatural event.",
  "Visibility: technically measurable. Practically: none. Drive as if walls could appear at any time.",
  "You can't see the cars ahead. They can't see you. This requires everyone to be careful. They won't.",
  "Pedestrians in the fog are essentially invisible. Slow way the hell down.",
  "Fog like this is the atmosphere pulling a disappearing act on your whole morning.",
  "Dense fog warning: the sky is off today and isn't telling anyone why.",
  "The streetlights make foggy halos and it looks beautiful and you could die if you're not careful.",
  "Something about fog makes the world feel like a secret. Today's secret is 'drive slow.'",
  "Fog so thick you could practically carve your initials in it.",
  "Fog turns your familiar neighborhood into an unfamiliar fog dimension. Don't veer off route.",
  "The atmosphere is throwing a gray, opaque tantrum. Commute accordingly.",
  "Fog this dense means every car on the road is a ghost story waiting to happen.",
  "All this fog and still people are tailgating. Humanity baffles me.",
  "Fog advisory in effect. Your overconfidence is not an advisory.",
  "Dense fog: arrive later, arrive alive. One is clearly better than the other.",
  "The fog makes everything quiet. That quietness is suspicious.",
  "Pea soup doesn't cover the thickness of this fog. Bisque-level fog out there.",
  "Morning fog is nature's way of being moody. Don't take it personally. Just drive slow.",
  "The fog is low-hanging and heavy and has zero interest in your commute timeline.",
  "Everything looks like it's part of a ghost story this morning. Most of it isn't. Most.",
  "Can't see more than a car length ahead. That's your following distance. No, less.",
  "Fog makes bad drivers invisible until they're close enough to matter. Respect the threat.",
  "Your lights tell other drivers you exist. Be a car that exists. Lights on.",
  "This fog is so cinematic it deserves a score. Slow, creepy strings over your whole commute.",
  "Fog doesn't care about your GPS confidence. Fog overrules GPS.",
  "That shape in the fog that looks like a person? Probably a person. Slow down.",
  "Dense fog advisory. Nature is currently being deliberately unhelpful about visibility.",
  "The fog makes your familiar block look completely alien. Friendly alien, probably. Drive slow.",
  "Fog turned the morning into a mystery novel. Your commute is the confusing chapter three.",
  "The fog doesn't announce itself. It just shows up and makes everything your problem.",
  "Visibility is down. Anxiety is up. This is the fog experience, summarized.",
  "Fog turns streetlights into useless halos and gives your commute a horror movie budget.",
  "Slow down. You're not as visible as you think. Neither is anything else.",
  "Drive like you'll meet something unexpected around every corner. Today you will.",
  "Dense fog warning: the sky borrowed your visibility and forgot to give it back.",
  "Fog mornings are perfect for reflection and absolutely nothing else, because you can't see anything else.",
  "This fog is thicker than whatever excuse you were going to make for being late.",
  "Fog like this deserves a director's cut. It's that dramatic.",
  "The road ahead is obscured. Your route is a suggestion. Your speed should be low.",
  "Something about low-visibility fog makes the car behind you seem farther away than it is. It's not.",
  "That fog bank ahead looks soft and inviting. It is neither.",
  "Your commute just became an extreme sport with poor visibility as the main obstacle.",
  "Dense fog on the highway: the condition that turns 'confident driver' into 'humbled driver.'",
  "Fog gives every walk the energy of sneaking up on your own neighborhood.",
  "Zero visibility, hundred percent bad vibes. The fog means business.",
  "In dense fog, speed is the enemy. Patience is the only sensible gear.",
  "The fog will lift eventually. Your stress will not lift with it. Drive carefully.",
  "Fog this thick would be cool if you weren't trying to get anywhere.",
  "Nature said 'what if the world just disappeared for the morning' and executed perfectly.",
  "Dense fog: the rare condition where being wrong about the road ahead has consequences.",
  "Your confidence in this fog is charming. And misplaced.",
  "Something lingers in the fog. It's the sound of your better judgment saying 'slow down.'",
  "Fog turns a normal morning into something you'd describe later as 'eerie' and 'damn.'",
  "Driving in dense fog requires: lights on, speed down, following distance up, ego checked.",
  "The fog wrapped everything up like a present nobody wanted to open.",
  "Eerie, quiet, cold, and zero visibility: fog is doing the absolute most today.",
  "Can't see the road ahead. Can't see the cars around you. Everyone's just guessing now.",
  "Fog so thick you're navigating by memory and optimism.",
  "Dense fog means the road is technically theoretical right now. Drive as though it's real.",
  "The fog showed up uninvited and now everyone's late and vaguely unsettled.",
  "Visibility three car lengths. Tailgating is, therefore, insane. Someone will tailgate.",
  "Fog gives the morning a 'what if the world ended quietly' vibe. Spoiler: it didn't. Drive slow.",
  "The world is muffled and soft and completely unprepared for your commute speed. Slow down.",
  "Dense fog advisory: treat every intersection like it's guarding a secret. Approach slowly.",
  "Fog this thick is basically nature's jump-scare delivery mechanism.",
  "If you can't see your neighbor's house from your porch, it's not a morning for speeding.",
  "Foggy mornings are best spent inside. If you must go out, do it slowly and resentfully.",
  "This fog rolled in like it had a point to prove. You don't need to prove anything. Drive slow.",
  "The fog ate your usual landmarks. You're on your own out there.",
  "Fog likes to swallow things: your visibility, your confidence, your sense of where the curb is.",
  "Everything past twenty feet is a mystery box. Today's mystery boxes are on the road.",
  "Thick fog: the setting for every ghost story ever written and your morning commute.",
  "Your car is a lighthouse in a fog bank. Be the lighthouse. Lights on.",
  "Fog this heavy is the sky's version of a 'do not disturb' sign.",
  "Visibility: the fog ate it and didn't leave a note.",
  "Foggy morning. Creepy silence. Excellent day to stay home and watch the John Carpenter catalog.",
  "The fog makes the world mysterious. Driving in mystery: considerably less delightful.",
  "Dense fog and rush hour should not coexist. They do. They always do.",
  "Fog like this makes your headlights look like a flashlight in a cotton ball.",
  "The air is so thick with fog you could chew it. Don't. Drive slow through it instead.",
  "Fog advisory: existence outside confirmed but visibility is not.",
  "Your GPS doesn't know about the fog. Your GPS is overconfident. Be less like your GPS.",
  "Spooky isn't the right word. The right word is 'dangerous.' Drive accordingly.",
  "Thick fog morning: a reminder that weather can reduce your world to a very small circle.",
  "Everything beyond the fog line is a secret. The secret isn't good. Drive slow.",
  "It's not Silent Hill. Probably. But drive like it might be. Slowly.",
  "Dense fog turns the morning commute into a trust fall with the road.",
  "The fog doesn't care that you can see on a good day. Today is the fog's day.",
  "Fog morning: lights on, speed down, vibe: ominous.",
  "Walking in thick fog feels like being inside a cloud. A cold, spooky, navigation-optional cloud.",
  "Pea soup? More like pea concrete. The fog is dense and has opinions.",
  "Dense fog advisory: the fog is being extremely dramatic and you are the supporting cast.",
  "Fog on the bridge is different from regular fog. Bridge fog has a power level.",
  "Things that disappear in fog: visibility, distance perception, the illusion that you're in control.",
  "Slow down, lights on, and stop trusting that the road ahead is clear. It might not be.",
  "Fog advisory in effect. Translation: the atmosphere is pulling some shit.",
  "The fog is so thick it feels like driving through a cloud that has a grudge.",
  "Fog makes everything look like a movie still. An unsettling movie with a slow commute subplot.",
  "Low-visibility morning means high-stakes every moment you're on the road.",
  "Dense fog turned the sunrise into a rumor nobody can confirm.",
  "Fog's out there being deeply ominous and none of it is your fault. Drive anyway. Slowly.",
  "The fog doesn't want you to see where you're going. Fight back with headlights and patience.",
  "This fog is so thick even the sound is muffled. Quiet, cold, and invisible-road vibes.",
  "Dense fog: when the atmosphere decides to do improv with your morning.",
  "Fog so heavy it makes everything feel like a held breath. Release the tension. Slow your speed.",
  "Morning fog has the energy of a story that doesn't want to be told yet. Drive cautiously.",
  "The fog is theatrical, ominous, and genuinely dangerous. Appreciate two of those. Fear the third.",
  "Fog advisory: slow down, lights on, and accept that you're in a horror-adjacent situation.",
  "Visibility is whoever's running reality decided you've had enough for today.",
  "Fog like this doesn't just reduce visibility — it reduces your sense of everything. Drive to survive.",
];
