export const HELL: readonly string[] = [
  "It's hot as balls out there.",
  "It's fucking hot. Stay inside, you beautiful idiot.",
  "Satan called — he wants his thermostat back.",
  "This is the kind of heat that makes your car seat a war crime.",
  "Congratulations, you live on the sun now.",
  "The devil's armpit. That's the current temperature.",
  "Even the mosquitoes said 'nah' today.",
  "Hot enough to fry an egg on your forehead. Please don't.",
  "Welcome to Satan's armpit. Population: you, suffering.",
  "The sun isn't shining today. It's targeting you specifically.",
  "It's hotter than a goat's ass in a pepper patch.",
  "The air itself is broken. It's just hot soup outside.",
  "Your balls have fused to your inner thigh. They live there now.",
  "This isn't weather. This is the Earth trying to cook you alive.",
  "Hell would actually be a mild improvement right now.",
  "The pavement is cooking your shoes. They taste terrible.",
  "Satan looked at today's forecast and said 'damn, that's rough.'",

  "The sun is personally attacking you and it's winning.",
  "Your sweat has sweat. That sweat also has sweat.",
  "If you step outside, you will immediately regret every decision you've ever made.",
  "Even the lizards are inside today. Think about that.",
  "You're not sweating, you're pre-marinating.",
  "The thermometer said 'fuck this' and melted.",
  "This is what the inside of a Hot Pocket feels like.",
  "At this temperature, your deodorant has already written its resignation letter.",
  "The fire department called. They want to know if you're okay.",
  "Air conditioning isn't a luxury today. It's oxygen.",
  "You're one more degree away from spontaneous human combustion.",
  "The sun is doing a solo and it's really going for it.",
  "Your car seat is a torture device. Do not sit directly on it.",
  "If you're outside by choice, that's on you. Medical assistance is around the corner.",
  "Sweat is just your body crying. Right now your body is sobbing uncontrollably.",
  "This is the kind of hot that makes you reconsider the concept of clothes.",
  "You are a human rotisserie chicken. Spin accordingly.",
  "The road is giving off heat waves like it's auditioning for a movie about death.",
  "Even the sun looks tired of this shit.",
  "You don't need a sauna today. You're already in one. It's called outside.",
  "If the devil took a vacation, he'd choose somewhere cooler.",
  "Your phone is overheating. So is everything else. Including you.",
  "The air tastes like the inside of an oven. Because it is.",
  "Hydration isn't optional. It's the only reason you're still alive.",
  "Every surface outside is a frying pan and you're the egg.",
  "You could boil water on the sidewalk. Please don't make soup.",
  "It's so hot the birds are walking because they don't want to fly through that.",
  "Your sunscreen melted before you even applied it.",
  "If you touch the steering wheel, you'll leave fingerprints in the metal.",
  "This is God's punishment for something. I'm not sure what, but it must've been bad.",
  "The forecast says 'surface of the sun' with a 90% chance of you dying.",
  "Your ice cubes surrendered before they even hit the glass.",
  "This is what dying feels like, apparently.",
  "Asphalt is now accepting applications for a career in lava.",
  "You're not outside. You're inside the sun's mouth.",
  "Your shorts are welded to your thighs. They're part of you now.",
  "Find AC or find Jesus. Those are your two options.",
  "The heat index has given up using numbers and switched to screaming.",
  "Your dog refused to go outside. Your dog is smarter than you.",
  "Even a cold shower sounds like work when it's this hot.",
  "This is officially too fucking hot for human habitation.",
  "The weather app just sent a 'lol good luck' notification.",
  "Your nipples are sweating. You didn't know that was possible. Now you do.",
  "At this heat, dignity is the first thing to go.",
  "Step outside. I dare you. I double dare you, motherfucker.",
  "The concrete is so hot it's basically a grill. Don't be a burger.",
  "You'll need a new layer of skin by the time you get to your car.",
  "Sunglasses, sunscreen, and a will to live. Pack all three.",
  "If you have to ask if it's too hot, you're already heat-stroking.",
  "The air is 40% humidity and 60% the will to die.",
  "Your workout today is walking to the mailbox. Congratulations.",
  "Hell exists. It's outside your front door.",
  "Even your water bottle gave up and just became warm soup.",
  "It's so hot your shadow is sweating.",
  "The heat isn't just uncomfortable. It's making philosophical arguments you can't counter.",
  "Outside is a no-go zone. Treat it like molten lava. Because it basically is.",
  "Your AC is working so hard it's filing for overtime.",
  "Satan himself sent a 'stay hydrated' text. That's how bad this is.",
  "The sun has an agenda today, and you're on the list.",
  "Your soul just tried to leave your body to find a cooler host.",
  "It's like wearing a wool sweater in a hot tub. While on fire.",
  "Your sunscreen needs sunscreen.",
  "You could forge steel on your driveway right now. Do not attempt.",
  "The weather report said 'abandon all hope.' They meant it.",
  "Every breath you take is a slow cooking process.",
  "Your car is a convection oven and you're the casserole.",
  "If you have to be outside, make peace with the heat. It will not make peace with you.",
  "Sweat angels exist now. You'll leave one on your chair.",
  "The heat has given your ass its own personal rain system.",
  "Even the flies are too hot to buzz. They're just sitting there judging you.",
  "Your hair is styling itself based on pure sweat content.",
  "Hell has a better HVAC system than your city right now.",
  "Your car keys burned a hole in your pocket. Literally.",
  "The heat index says fuck off. Respectfully.",
  "Every step outside is a negotiation with entropy.",
  "Cold water doesn't exist outside anymore. It's all warm soup now.",
  "The ground is off-gassing heat back at you. The Earth is pissed.",
  "You're being slow-cooked by an indifferent universe.",
  "Your dignity sweated off somewhere around the driveway.",
  "If breathing weren't involuntary, you'd have given up by now.",
  "This is the 'I saw someone fry bacon on an engine block' level of hot.",
  "Your internal monologue has been replaced by 'it's so fucking hot.'",
  "Nature is currently trying to kill you via ambient temperature. Stay inside.",
  "Somewhere, a weather scientist is crying and they won't explain why.",
  "The heat radiating off the parking lot is a war crime.",
  "Your sweat glands are in a full sprint. They trained for this.",
  "It's the kind of hot where you stop caring about anything except cold water.",
  "You'll need a lifeguard for your shirt. It's basically a lake.",
  "Today's high: soul-melting. Today's low: still way too fucking hot.",
  "Your eyeballs are warm. That's a new sensation. Not a good one.",
  "The heat is doing things to your brain. Stupid, slow, sweaty things.",
  "Even Antarctica is side-eyeing your weather right now.",
  "Your cat has found every cold tile in the house. Respect your cat's wisdom.",
  "A Viking would go home today. That tells you everything.",
  "Dress code: survive.",
  "Your feet are cooking inside your shoes. Your shoes feel bad about it.",
  "The atmosphere is basically just recirculated oven exhaust.",
  "You're not living your best life today. You're just living.",
  "Is it possible to get a heat rash on your armpits? Today you'll find out.",
  "The bugs aren't even biting today. Too hot to give a shit.",
  "Your phone case is warm to the touch. Your soul is warmer.",
  "Drinks sweating, you sweating, everything sweating. It's a sweating party.",
  "At this temperature, SPF 100 is a prayer, not a sunscreen.",
  "Your sneakers are slowly fusing with the asphalt. Don't stop moving.",
  "The only acceptable activity today is floating in water and thinking about nothing.",
  "Even your anger about the heat makes you sweat more. It's a cruel cycle.",
  "Your body has activated every cooling mechanism and it still isn't enough.",
  "The meteorologist said 'triple digits' and then quietly went off-camera to cry.",
  "Concrete doesn't reflect sunlight. It hoards it. Today it's paying dividends.",
  "Hell is empty and all the devils are outside enjoying your city's weather.",
  "If you must go out: go fast, go dumb, and hydrate or die-drate.",
  "Your shirt is auditioning to be a wet-T-shirt contestant. It's not being subtle.",
  "Every outdoor plan is now cancelled due to the Earth hating you.",
  "The heat is making everything worse, including you.",
  "You're one hot minute away from becoming beef jerky.",
  "Your sweat is sweating. The physics of this should not be possible.",
  "Air thick enough to chew. Tastes like regret and exhaust.",
  "Even the sun is embarrassed about what it's doing to you today.",
  "Your car's steering wheel is at an internal temperature of 'do not touch.'",
  "If you leave chocolate in your pocket it will be a smoothie by the time you arrive.",
  "The parking lot is a post-apocalyptic hellscape. And you parked far away.",
  "Somewhere a thermometer is maxed out. That thermometer is a quitter.",
  "Your whole ass is a sauna. Nobody needed to know that. Now they do.",
  "It's giving 'inside a running dryer' vibes. Not great vibes.",
  "The wind isn't helping. The wind is just moving the hot around.",
  "You are one prolonged exposure away from becoming a raisin.",
  "Step one: get water. Step two: pour it on your head. Step three: repeat.",
  "Your neighbors have given up and are sitting in their cars with the AC running.",
  "Summer in Hell has more shade than this.",
  "Your sunglasses fogged up the moment you stepped outside. From the outside.",
  "The only thing keeping you going is spite and ice water.",
  "Today's workout: sweating. You're already killing it.",
  "The forecast called for a 'real bad day to be alive.' Checks out.",
  "If you have a pool, you're obligated to be in it. Legally, probably.",
  "Even your shadow is trying to get away from you. It's running for shade.",
  "Your shoes are squeaking because they're wet inside. Don't think about it.",
  "The street smells like hot rubber and broken promises.",
  "This heat is an event. A tragic, sweaty, UV-index event.",
  "The nearest planet with a livable temperature is about 100 light-years away. Enjoy the commute.",
  "Your grocery bags melted before you made it to the car.",
  "Today's UV index: yes.",
  "Even the trees look exhausted. Trees. Photosynthesis is supposed to be their job.",
  "Hell doesn't have a dress code because nobody lasts long enough to need one.",
  "Your skin is doing something it shouldn't be doing. Investigate later.",
  "The heat broke the will of better people than you.",
  "Even your HVAC unit is sweating its balls off trying to keep up.",
  "There's no shade out there. Just hot and hotter.",
  "You need a cold shower, a cold drink, and a cold reason to exist today.",
  "If you go for a run today, you are a maniac and we respect and pity you equally.",
  "The asphalt is soft. That's not supposed to happen. Go inside.",
  "Your sweat has achieved a gravitational pull. Check your calves.",
  "The phrase 'dry heat' means absolutely nothing to your wet-ass body right now.",
  "This weather is personal. It has your home address.",
  "Everything metal is a weapon today. Plan your route around door handles.",
  "Your water bottle went from ice-cold to lukewarm in eleven minutes. Science, baby.",
  "Even the roaches are inside. You know it's bad when the roaches are hiding.",
  "You're at the exact temperature where you stop trusting yourself to make good decisions.",
  "The heat is so intense it's getting a restraining order filed against it.",
  "Your car AC hasn't worked this hard since it was installed. It's filing a complaint.",
  "Eating outside today means eating hot soup. Whatever food it is, it's hot soup now.",
  "You will not walk to that. You will drive five feet to avoid the sun. No shame.",
  "Your skin is basically a solar panel, and today it's overloaded.",
  "Seriously. Stay inside. The outside has made it very clear it doesn't want you.",
  "The weather is rated R today. For Real Hot and absolutely Ridiculous.",
  "SPF 50? Cute. Put on SPF 'I surrender.'",
  "Go outside if you hate yourself. The temperature is more than happy to agree.",
  "Your internal cooling system has submitted a formal complaint to management.",
  "Even the pizza delivery guy gave up. You're on your own.",
  "This is what happens to meat when it sits in a hot car. Don't be the meat.",
  "Your existence is a hot, sweaty inconvenience to your own body right now.",
  "The sun is giving you hate-love. It's warming you just enough to ruin your life.",
  "Your spine has dissolved into a river of sweat. You're basically a jellyfish now.",
  "God has a thermostat. Today he cranked it and walked away laughing.",
  "The meteorologist's voice cracked when they read today's high. I respect their honesty.",
  "If this were a movie, you'd be the background character who passes out.",
  "The only appropriate response to this weather is profanity. You're doing great.",
  "Even the highway signs are buckling in the heat. Respect.",
  "Your lungs are getting a free sauna treatment with every breath. Unsolicited.",
  "You are a human pressure cooker and the valve is about to blow.",
  "The thermometer just threw up its hands and said 'figure it out yourselves.'",
  "Skin deep? Try 'sweat deep.' You are soggy to your bones.",
  "Your AC is doing God's work today. Leave it a good review.",
  "Inside: paradise. Outside: consequences.",
  "Even the cicadas sound tired. They never sound tired.",
  "Just so you know: your hair looks insane. Not your fault. It's the humidity.",
  "The grocery store parking lot is an inferno. Find a spot near the entrance or lose your will to live.",
  "Your entire wardrobe has failed you today. Doesn't matter what you put on.",
  "The sun said 'hold my beer' and then forgot to actually hold back.",
  "You and the asphalt are going through the same thing. Solidarity.",
  "Somewhere a lake is calling your name. That lake understands you.",
  "Put your feet on the tile floor and stay there. Permanently. That's your life now.",
  "This heat is above your pay grade.",
  "It's hotter than Satan's steam room. He's actually jealous of your weather.",
  "Your sweat has developed a zip code.",
  "Today's activity: existing without melting. Best of luck.",
  "The heat wants your soul and it's making a very compelling case.",
  "Asphalt, steel, your car, your hopes: all soft and malleable in this heat.",
  "Your exhale is hotter than the air outside. That shouldn't be possible.",
  "The sun isn't just in the sky today. It's in your living room, somehow.",
  "Your pits have given up. Your shirt already knows. Everyone knows.",
  "Stepping outside is technically a controlled experiment in suffering.",
  "The heat has achieved sentience and it hates you specifically.",
  "You're not persevering. You're marinating.",
  "Even the ants underground are writing strongly-worded letters about this.",
];
