export const HOT: readonly string[] = [
  "It's balls-hot. Not quite hell, but you'll sweat through your shirt.",
  "Swampass weather. Choose your seat wisely.",
  "It's the kind of hot where flip-flops become a bad decision.",
  "Drink some water, you sweaty bastard.",
  "Hot as hell's waiting room out there.",
  "Deodorant is not optional today.",
  "Your thighs are going to have a serious conversation with each other.",
  "Swamp ass o'clock. Set your watch.",
  "It's hot enough to fry an egg on your forehead. Please don't.",
  "The AC is your only true love now. Cherish it.",
  "Your shirt has merged with your spine. They're one organism now.",
  "Your deodorant has filed for divorce. You'll be getting papers.",
  "Not quite hell, but hell's waiting room. With worse magazines.",
  "Your back sweat has its own tidal zone.",
  "Step outside for thirty seconds. Regret it for thirty minutes.",
  "The air is thick, wet, and personally offensive.",
  "You're sweating in places that should remain dry. We've been through this.",
  "Beer sweating faster than you can drink it. Try harder.",
  "It's hot enough to make you question the concept of pants.",
  "Your chair just committed a crime against your thighs.",
  "Summer is being a complete dick today.",
  "Humid as a locker room after a double-header. And you're in it.",
  "You're not glistening. You're soaked. Stop lying to yourself.",
  "Cold water. Find it. Worship it.",
  "This is the kind of hot where doing nothing makes you sweat.",
  "You and your couch have a moisture agreement now. It's not ideal.",
  "Your deodorant is doing its best. It's not enough.",
  "If you parked in direct sun, that car is an oven and you owe yourself an apology.",
  "Standing outside counts as cardio today. Your heart rate agrees.",
  "Even your laziness requires effort in this heat.",
  "Your underwear situation is not great. You know it. They know it.",
  "The mailbox isn't worth it. Order online.",
  "Your body has given up trying to be subtle about sweating.",
  "Sunscreen isn't optional. It's damage control.",
  "The vibes outside are: wet, punishing, and deeply personal.",
  "Even the breeze is warm. The breeze has betrayed you.",
  "You need a cold drink, a good excuse to stay inside, and therapy.",
  "Shorts weather, technically. Swamp-ass weather, definitely.",
  "A light jacket is hilarious as a suggestion today.",
  "Your shirt is a map of every stressful decision you made this morning.",
  "The humidity is why you can't have nice things.",
  "Even standing still you're working up a solid sweat. You're fit now, I guess.",
  "Hot but survivable. Survive anyway.",
  "Your hair is doing whatever it wants today. Let it go.",
  "Air conditioning has never felt more like an act of love.",
  "The outside is an assault course. The inside is salvation.",
  "You've already sweat through your first shirt. The second one is on borrowed time.",
  "Hydrate like your life depends on it, because in this heat it kind of does.",
  "Your jeans are a mistake. They're a hot, heavy, oppressive mistake.",
  "Sitting outside at a restaurant is technically masochism.",
  "The breeze is just hot air with better PR.",
  "Your neck sweat has formed its own tributary system.",
  "Even your flip flops are squeaking from the moisture. Cool it.",
  "Summer said 'you wanted this' and honestly, fair.",
  "You're marinating in your own juices. Gross. Drink water.",
  "If you voluntarily wore a tie today, I'm so sorry.",
  "The heat index says 'wow, really' and then adds ten degrees for drama.",
  "Sweating through a meeting is a power move. That's what we're telling ourselves.",
  "Your lunch break is sponsored by shade and cold beverages.",
  "The parking lot asphalt is radiating heat like a grudge.",
  "You don't need a gym today. You need to stop existing in this temperature.",
  "Even your iced coffee became regular coffee by the time you got to your car.",
  "The phone in your pocket feels like a heating pad. Not great.",
  "Wearing black today was a choice. A bold, stupid choice.",
  "Your pores are doing overtime and they're not getting paid extra.",
  "You'll need a second shower. Maybe a third. Budget accordingly.",
  "It's the kind of hot that makes outdoor dining sound like a war crime.",
  "Your fabric softener had no idea it was training for this.",
  "A fan is blowing hot air around the room. It's technically moving air. That's the best we've got.",
  "Your dog is smarter than you. Your dog is inside.",
  "The ice in your drink has given up. Poured out for a soldier.",
  "Outside work today? You poor bastard. Drink everything.",
  "Your seat belt buckle is a small metal torture device today.",
  "Comfort is a myth. Mild misery is the current offer.",
  "SPF is the only thing between you and a crispy future.",
  "Your sunglasses are doing their job. The rest of your outfit is failing.",
  "Even a cold shower sounds like work in this heat. Do it anyway.",
  "The pavement smells like hot rubber and disappointment.",
  "This is the 'cancel all plans, make an ice bath' kind of hot.",
  "Your shirt collar is a sauna collar now.",
  "It's too hot to be productive. Don't try to prove otherwise. You'll fail.",
  "Your body is approximately 60% water. Today it's 59% sweat.",
  "Your ambitions melted hours ago. That's probably fine.",
  "The afternoon is going to get worse. Emotionally prepare.",
  "Cold drinks are sacred objects today. Treat them accordingly.",
  "Your office chair has absorbed you. You are part of the furniture now.",
  "Going outside is an extreme sport and you need better gear.",
  "The sun is at 'making a point' levels of intense.",
  "You sweat more in ten minutes outside than a full workout inside. Efficiency.",
  "Your lunch is already warm. Everything is warm. It's warm all the way down.",
  "The heat is oppressive and it doesn't give a damn about your schedule.",
  "Your inner thigh has declared independence. It wants its own territory.",
  "This is the weather that sells portable misting fans by the thousands.",
  "Even the shade isn't that refreshing. But it's better than nothing. Use it.",
  "Your outfit made sense at 7 AM. It has not held up.",
  "The vending machine in the break room is now a holy shrine.",
  "A cold beer has never sounded more important than it does right now.",
  "Your back is a topographical map of your afternoon. It's not flattering.",
  "You're not running hot, you're running 'evacuate the body' levels.",
  "Drinking water isn't refreshing, it's triage.",
  "Every surface you sit on is now permanently damp. You're welcome.",
  "Hot enough to make grown adults walk faster than usual just to get inside.",
  "Even the gym is more appealing than outside right now. It has AC.",
  "Your body odor has become an identity. Own it or shower.",
  "The forecast lied about a 'pleasant afternoon.' Report it.",
  "You've accepted that your clothes are wet now. This is the new normal.",
  "The only good idea you've had today was getting that cold drink.",
  "Your scalp is sweating. Your scalp.",
  "This is why people move somewhere colder and never look back.",
  "The bench you almost sat on would have made you reconsider existence.",
  "Sweat is just your body's version of 'help me.'",
  "At 95 degrees, your personality evaporates. Only survival instincts remain.",
  "The drive-through line is worth it. Anything to stay in the AC.",
  "Your shoes are wet inside. You don't want to know why. You already know.",
  "Outside meetings should be illegal until October.",
  "Even the cicadas sound resentful today.",
  "You need a sports drink, not a regular drink. Act accordingly.",
  "The sun is doing laps today. Extra laps. Overtime laps.",
  "Your shirt is basically a sponge at this point. A stylish, ineffective sponge.",
  "It's not the heat that gets you, it's the humidity. It's both. It's both today.",
  "If someone brings you ice cream right now, they are an angel.",
  "Your scalp tan is coming in real strong this week.",
  "The parking garage is three degrees cooler than outside. Three degrees feels like paradise.",
  "Your internal temperature gauge said 'sir this is a Wendy's.'",
  "Every cold thing has become precious. Guard your ice like a dragon.",
  "Grocery store, library, anywhere with AC. That's your itinerary.",
  "The only appropriate hat is a large one. The hat is load-bearing today.",
  "You've been outside for forty seconds and you need a nap.",
  "Even your patience sweated off. You have zero patience and one cold drink left.",
  "Your phone is warm in your pocket and you're warm in your skin and everything is warm.",
  "It's hot enough that people are being nicer to each other. Shared suffering builds community.",
  "The concrete is radiating heat upward and the sun is pushing it down. You're in a sandwich.",
  "Your sunglasses have fogged up from sweat. Respect.",
  "Anyone running outside right now has a much better relationship with suffering than you do.",
  "Your ice chest is the most important object you own today.",
  "Take the elevator. You don't have the caloric reserves to waste on stairs.",
  "Your cold glass of water is already sweating harder than you. Competition.",
  "The patio people are looking rough. Don't become a patio person.",
  "It's peak swamp-ass conditions. Act like you've been warned.",
  "Your makeup has melted off by noon and it's a whole new face situation.",
  "At this heat, cologne and perfume become aggressive. Nobody needs that.",
  "Drink water. Then drink more water. Then question your outdoor choices.",
  "You're burning calories just existing today. Not enough to justify ice cream, but close.",
  "The fan blowing across ice in a bowl isn't a real AC. It's a cope. Use it.",
  "Heat exhaustion isn't a vibe. Drink water before you become a cautionary tale.",
  "Your dignity is somewhere between your third shirt change and your first cold shower.",
  "Summer is working very hard to disappoint you. Mission accomplished.",
  "Your sweat pattern has become a Rorschach test for your misery.",
  "Even the birds are taking breaks. You should too.",
  "Outdoor concerts in this heat are a special kind of commitment. Respect or pity, unclear.",
  "Your car's interior is radiating heat stored since sunrise. Open the door from a safe distance.",
  "Even the ants are moving slower. Ants never move slower.",
  "Your lunch break walk was a mistake that no one can take back.",
  "Sweating through a button-down is a business casual disaster.",
  "The next three months are going to be a whole thing. Mentally prepare.",
  "Even the gym's AC can't keep up with the heat pouring in through the windows.",
  "Your cold brew just became warm brew. Nature is cruel.",
  "The humidity is why God invented oscillating fans.",
  "Any errand that can wait should wait. Leave the errands for October.",
  "You're not wilting, you're adapting. Badly, but still.",
  "Your car smells like hot plastic and sunscreen. That's summer in a nutshell.",
  "Stay hydrated or become a cautionary tale. Those are the options.",
  "The hat, the sunglasses, the SPF 50. You look ridiculous. You'll live.",
  "Your chair gave you a sweat mark so severe it's basically a crime scene.",
  "Even the grocery store AC can't fix what outside did to you.",
  "You're one more degree away from the hell band. Hang in there.",
  "Your resolve evaporated at noon. That's normal. Have a cold one.",
  "The sweat under your boobs has developed its own weather system. You're welcome.",
  "It's hot enough to make you actually consider buying a pool. Do the math first.",
  "Your internal monologue is just 'hot hot hot' on a loop.",
  "Every sip of cold water is a religious experience today.",
  "The humidity is doing your hair a disservice and it doesn't apologize.",
  "You'll need extra antiperspirant, extra patience, and probably extra beer.",
  "The heat is not your friend, but the shade is a solid acquaintance.",
  "Standing in front of an open refrigerator isn't a coping mechanism. Yes it is.",
  "By evening you'll have done a full body workout through passive sweating. You're welcome.",
  "Your standards for what constitutes 'comfortable' have dramatically lowered.",
  "The outdoor workers deserve all your respect and all your cold water donations.",
  "Even the shade tree is like 'I'm doing my best, man.'",
  "Your cold drink has been through a lot today. Respect its sacrifice.",
  "It's not ideal. It's not catastrophic. It's just really fucking hot.",
  "The two-second breeze was a tease and it knew exactly what it was doing.",
  "Your sweat is now a crop top whether you want it to be or not.",
  "Between the heat and the humidity, the air is basically wearable moisture.",
  "Being productive in this heat requires twice the effort and half the results.",
  "Your motivation left the building around 10 AM when the temperature crossed ninety.",
  "Outdoor dining: a romantic idea that becomes a hot, sweaty disaster after ten minutes.",
  "The thermostat in your office has been set to 'barely tolerable' and you're grateful.",
  "Your cold shower is going to be the best part of your day. Plan for it.",
  "That shirt is done. Do not attempt to salvage it. Start fresh.",
  "Your phone screen is warm from your sweaty hand. Everything is contaminated by heat now.",
  "You're basically a large, ambulatory radiator and everyone around you knows it.",
  "The ice cream truck has never sounded more like hope than it does right now.",
  "Your hairline is doing a full sweat sprint. Wipe it and keep going.",
  "Even the concrete is giving off that heat shimmer thing. Dramatic and warranted.",
  "Hot but not unreasonable. 'Unreasonable' is tomorrow's forecast.",
  "Your dignity and your dry shirt left at the same time. Approximately noon.",
  "The popsicle you ate was gone before it made any real difference. Life is fleeting.",
  "You will be showering twice today and it's already decided, you just don't know it yet.",
  "Staying horizontal in AC is actually the only rational response to this weather.",
  "Even the grocery list you wrote in the car feels damp now.",
  "Your socks are wet. Don't think about it.",
  "This is the kind of hot that makes you nostalgic for a mild winter day.",
  "The ice in the cooler is a limited resource. Plan accordingly.",
  "Sweat is today's fashion accessory whether you like it or not.",
  "Your afternoon productivity is inversely proportional to the temperature. Math.",
  "Somewhere, someone is enjoying this weather. They're wrong, but they're enjoying it.",
  "Even the birds perched in the shade are giving off 'why are you like this' energy.",
  "The heat hasn't broken your spirit yet. Give it another hour.",
  "Your chair has become a swamp. You are the swamp thing now.",
  "Patio bars are built for this. You are not. Go to a patio bar anyway.",
  "Your armpits have betrayed you and taken your shirt hostage.",
  "The outdoor table you grabbed seemed fun for exactly four minutes.",
  "Your ice pack is just a warm pack now. It tried.",
  "Even the dog's walk is getting cut short today. Solidarity.",
  "This is the sweat-ring-on-the-toilet-seat kind of summer. You know the kind.",
  "Your shirt had one job. It failed. Both of you know it.",
  "The sun is doing the most and you're just trying to do the least. Conflict.",
];
