export const ICE: readonly string[] = [
  "Freezing rain. The sidewalks want you dead.",
  "Ice storm vibes. Walk like a penguin or eat shit — your call.",
  "Everything's an ice rink now. Try not to break your ass.",
  "Black ice is out there, lurking like a passive-aggressive coworker.",
  "The driveway is a death trap. Proceed with absolute terror.",
  "Freezing rain turned the world into a slip-and-fall lawsuit.",
  "Every step is a gamble. The house always wins.",
  "Ice don't give a damn about your plans.",
  "Walk like you're defusing a bomb. Slow. Careful. Sweating.",
  "Your boots aren't as grippy as you think. Confidence is your enemy today.",
  "Outdoor surfaces have declared war. They're winning.",
  "One slip and you'll be doing a splits you absolutely did not intend.",
  "Ice: Mother Nature's way of saying sit your ass down.",
  "The parking lot is a glacier now. Good luck, champ.",
  "Freezing rain is just rain that really hates you.",
  "If you fall and nobody sees it, did it still hurt? Yes. Yes it did.",
  "Grip that handrail like it owes you money.",
  "Your tailbone is not ready for this. Your tailbone is never ready.",
  "Even the squirrels said 'fuck this' and stayed home.",
  "Black ice has no warning label. That's what makes it an asshole.",
  "Walking to your car: the most dangerous mission of your entire day.",
  "Roads are ice sheets. Every driver thinks they're exempt. They're not.",
  "Freezing rain: because regular rain was too polite.",
  "Tread carefully. The earth will betray you.",
  "The only workout you'll get today is falling in slow motion.",
  "Sidewalks are slicker than your excuse to call in sick.",
  "Ice is just water that decided to be a bastard.",
  "You ever do the full Bambi on a parking lot? Today might be your day.",
  "Salt the steps. Salt them again. Salt them a third time. Still might fall.",
  "Dress for the wipeout, not the weather.",
  "Your neighbor didn't salt their walk. Their negligence is now your problem.",
  "Imagine a skating rink. Now imagine it's everywhere. That's today.",
  "Low heels. Flat soles. Or stay inside, genius.",
  "The bushes are coated in ice. Pretty. Deadly. Like a lot of things.",
  "You're about to walk like you've never walked before. Arms out, baby steps.",
  "Roads out there are basically a curling sheet without the brooms.",
  "Mother Nature froze everything and did not leave instructions.",
  "Ice storm advisory: stop making plans.",
  "Hold the railing. Both hands. Don't be a hero.",
  "Freezing rain all night means this morning is a spectacular dumpster fire.",
  "Your car is encased in ice. That's not a car anymore, that's a discovery.",
  "Scrape the windshield. No, the whole windshield. The whole thing.",
  "You'll spend 20 minutes defrosting the car and 5 minutes questioning your life choices.",
  "Ice does not care that you're late. Ice has no mercy.",
  "The world is one giant Slip 'N Slide. Enjoy absolutely none of it.",
  "Driving today is an act of either courage or stupidity. Probably the latter.",
  "Ice on the roads. Winter has entered its villain arc.",
  "Freezing rain: precipitation with a mean streak.",
  "Every surface outside is a liability. Act accordingly.",
  "Your Crocs will kill you today. Swap them out. I'm begging you.",
  "If you go out and fall, that's on you. I told you.",
  "The mailbox is encased in ice. Let the bills wait — they deserve this.",
  "Freezing rain turns the world beautiful and homicidal. Mostly homicidal.",
  "Waddling is not embarrassing today. Waddling is survival.",
  "Ice doesn't discriminate. Rich, poor, fit, unfit — everyone busts their ass equally.",
  "Outdoor steps are now a test of character you did not sign up for.",
  "The universe froze the ground specifically to watch you struggle.",
  "Your knees are not ready. Your back is definitely not ready.",
  "Freezing rain fell all night. The world is now a skating rink run by chaos.",
  "Step one: look at the ground. Step two: look again. Step three: never stop looking at the ground.",
  "Your morning commute just became a survival documentary.",
  "Ice on every surface like winter threw up.",
  "Walk slow. Walk steady. Walk like a giraffe on roller skates, but carefully.",
  "Ice doesn't respect your hustle. Ice respects nothing.",
  "Freezing rain is petty. This is weather with a grudge.",
  "Ice storm: when winter stops playing and gets personal.",
  "If the stairs look suspicious, they are suspicious. Trust the paranoia.",
  "Salt on the driveway. More salt. An ungodly amount of salt. Still not enough.",
  "You're not in a hurry today. Physics won't allow it.",
  "This is the one day your slow, shuffling pace is actually correct.",
  "Ice thinks your confidence is funny. Ice is right.",
  "Every icy step is an invitation to meet the ground personally.",
  "Stay on the grass if you can. Grass is your ally. Pavement is your enemy.",
  "Car doors might be frozen. Windows might be frozen. Your will to live is about to be frozen.",
  "There's ice under the snow. It's layers of betrayal all the way down.",
  "Ice on the bridges first, always. Bridges are snitches.",
  "Winter looked at your commute and said 'let's make this worse.'",
  "Your coffee will be cold by the time you finish scraping the car. Drink faster.",
  "Shuffle your feet. Big penguin energy only.",
  "Slipping in public and catching yourself is the peak athletic achievement of winter.",
  "The ground is glass. You are not a ballerina. Act accordingly.",
  "Ice storm means every errand is optional now. All of them. Optional.",
  "Nature said 'let's ruin everyone's morning' and then executed flawlessly.",
  "Check your tires. Check your sole grip. Check your life insurance.",
  "Freezing rain is what happens when the atmosphere hates everyone equally.",
  "Black ice has no shame, no mercy, and no warning. Respect the threat.",
  "Your shoes? Cute. Lethal. Absolutely lethal on this ice.",
  "The trees are glittering with ice. They look gorgeous. They want you to admire them while falling.",
  "Ice on the roads: the universe's way of hitting pause on your schedule.",
  "Go slow or go to the hospital. Pick one.",
  "Winter is out here creating hazards with zero remorse.",
  "Every flat surface is now a trap set specifically for you.",
  "If you wiped out and your dignity survived, today counts as a win.",
  "Freezing rain: nature's passive-aggressive note on your front door.",
  "Ice doesn't care if you're in a rush. Ice is aggressively indifferent.",
  "One wrong step and you become the funniest video on the internet.",
  "Slippery out there. Like driving through a bowl of greased ball bearings.",
  "You're going to take tiny steps and you're going to like it.",
  "Every footfall is a negotiation between you and gravity. Gravity is negotiating in bad faith.",
  "Careful on the overpass — that's where black ice does its best work.",
  "Ice plus slope equals hospital visit. Do the math before you go outside.",
  "Your morning is already ruined. Make peace with it before you step outside.",
  "Freezing rain is just the sky telling you to cancel everything.",
  "Bundle up. The cold will stab through your coat like it owes you nothing.",
  "Ice storm warning. The earth is slippery and petty today.",
  "The freezing rain creates ice art on your windows. Pretty. Now scrape it off.",
  "Freezing drizzle sounds innocent. It is not innocent. It is a liar.",
  "Everything outside has a thin coat of 'absolutely not.' Walk accordingly.",
  "Your commute is now an obstacle course no one signed up for.",
  "The whole neighborhood is one giant trip hazard.",
  "Ice: nature's cheap linoleum floor, but the whole outdoors.",
  "Freezing rain is just rain that graduated from evil school.",
  "Outdoor stairs right now are a trust exercise you're going to fail.",
  "Even the ants are canceling their plans. Take the hint.",
  "Black ice can't be seen, can't be reasoned with, and does not care about your schedule.",
  "Winter hid the ice under a thin layer of snow like a prank gift.",
  "Low visibility and icy roads: a shitty combo platter for your morning.",
  "Snowflakes are cute; ice is just spiteful frozen water.",
  "Your hands need to be free. Put the phone away. Don't die scrolling.",
  "Ice is to winter what a bully is to a school hallway. Unavoidable and cruel.",
  "The porch steps have transformed into a death trap. Use the side door.",
  "Shuffling isn't optional today. It's your only movement setting.",
  "Step firmly, breathe deep, and try not to look stupid. You will look stupid.",
  "Your dignity may not survive the morning commute. That's okay.",
  "Freezing rain last night. This morning: an outdoor ice sculpture exhibit that hates you.",
  "Ice conditions: a great day to work from home and pretend you tried to go in.",
  "Watch the curb cut. That smooth concrete dip is the most dangerous place on earth right now.",
  "Roads are basically a skating rink operated by idiots in pickup trucks.",
  "Freezing rain all night means your car is a snow globe you have to chisel open.",
  "Gravel? Use it. Sand? Use it. Salt? Use all of it. Fight the ice.",
  "Mother Nature hit 'freeze all' and went back to bed. Smart of her.",
  "You will not be graceful today. No one is graceful today. Graceful is canceled.",
  "The ice doesn't care that it's inconvenient. The ice thrives on inconvenience.",
  "Every step outside is a scene from a nature documentary about survival.",
  "Your knees are about to file a formal complaint with your brain.",
  "The whole city's been laminated. Nothing to do but shuffle and hope.",
  "Ice on sidewalks means today's commute is sponsored by anxiety.",
  "Walking to work today takes the same focus as defusing a live grenade.",
  "That thin clear coat on the pavement? That's black ice. That's chaos. That's your enemy.",
  "The freezing rain has turned your neighborhood into a funhouse nobody wanted.",
  "Step off the porch like you owe winter a debt. Carefully.",
  "Ice: a free physics lesson and a potential ER co-pay.",
  "The roads are slick and the drivers are cocky. A lethal combination.",
  "Winter froze the world solid. Impressive. Also: rude.",
  "Don't trust anything that looks dry today. It's probably not.",
  "Your morning is now 40% longer due to ice-related walking speed reductions.",
  "Ice turns normal adults into slow, cautious toddlers and that's fine.",
  "Freezing rain has once again made everything outside a terrible idea.",
  "Your car is coated in ice armor. You have a vehicle you can't use for 20 minutes.",
  "The ground is wearing a disguise and that disguise is 'solid.' Do not be fooled.",
  "Ice storm energy: stay inside, drink something warm, watch people wipe out on Ring cameras.",
  "Watch your step or don't — your call — but the concrete doesn't care about your feelings.",
  "Winter turned everything into a surprise skating rink. No skates provided.",
  "Confidence is a liability out there today. Replace it with caution.",
  "The ice on your car door handle is winter saying 'please don't go.'",
  "Frozen roads plus overconfident drivers equals a chaos buffet.",
  "This is what you trained for. You didn't train for this.",
  "Ice on the roads means your drive is one bad decision from becoming a news story.",
  "Freezing rain fell last night with the sole purpose of ruining your day.",
  "The world is coated in frozen menace and it is not fucking around.",
  "Even parking lots — the safest-looking surfaces — are death traps today.",
  "Ice day. The universe took one look at your morning and said 'no.'",
  "Step out like you're on thin ice. Because you are. You literally are.",
  "Every horizontal surface outside is now a polished hazard.",
  "Ice: winter's way of making you regret leaving the house.",
  "Your morning confidence will be tested immediately by the first patch of ice you hit.",
  "Freezing rain don't give a damn about your timeline.",
  "The only people unbothered by this ice are penguins and people who've already fallen once.",
  "Do NOT trust the flat-looking bits. They are the most treacherous bits.",
  "Winter deployed ice overnight. It's a tactical assault on your schedule.",
  "The ice is here and it's got your number.",
  "Freezing rain: a meteorological middle finger pointed directly at you.",
  "Ice covers everything with a thin, beautiful, malicious layer of nope.",
  "The whole outside world is a slip-and-fall accident waiting to be filed.",
  "Walk the slow walk. The embarrassing shuffle. The survival shuffle.",
  "Freezing drizzle is just ice that came early to ruin things.",
  "Your knuckles will thank you if you keep one hand free and rail-adjacent at all times.",
  "Ice wants to meet you face-first. Deny it the pleasure.",
  "Every puddle out there is a potential frozen hellhole.",
  "The leaves and grass are glazed in ice. Don't stop to admire it while you fall.",
  "Nature doesn't give partial credit for trying to walk on ice.",
  "This is an excellent morning to reconsider every plan you made.",
  "Freezing rain: it sounds mild and is genuinely trying to hospitalize you.",
  "Walk. Like. A. Penguin.",
  "Ice said 'plans are for people who can stay upright.' That's a direct challenge.",
  "Roads are skating rinks. Parking lots are skating rinks. Your life is now a skating rink.",
  "Stay inside. If you must go out, do it slowly. Like, embarrassingly slowly.",
  "Black ice is silent, invisible, and an absolute bastard.",
  "Freezing rain doesn't announce itself. It just waits on the ground for you.",
  "One ambitious step and it's ass-over-ankles for you. Take your time.",
  "The cold is trying to trip you. It is literally trying to trip you.",
  "Ice: a full-time nemesis in seasonal clothing.",
  "Winter gave you ice and zero sympathy. Classic winter.",
  "Today is not a day for optimism. Today is a day for rubber-soled boots and fear.",
  "Somewhere under the ice is your confidence from yesterday. It's staying there.",
  "The weather forecast was 'ice.' Consider yourself warned and previously ignored.",
  "Out there it's ice. In here it's warm. Only one of those wants you to fall.",
  "Freezing rain turned the whole damn neighborhood into a liability.",
  "Your morning commute is now rated M for Mature. Slippery content ahead.",
  "Winter said 'what if I made everything worse' and it did and here you are.",
  "Ice rink everywhere. No Zamboni. No skates. Just suffering.",
  "Freezing rain: the one precipitation that actively wants you on the ground.",
  "Your boots are your only allies. Do not betray them with icy overconfidence.",
  "The ice doesn't announce its presence. That's what makes it a genuine bastard.",
  "Every crack and seam in the pavement is hiding a tiny ridge of ice. Fun surprise.",
  "Winter dressed everything up in a thin glass coat and called it weather.",
];
