export const MEH: readonly string[] = [
  "Cold-ish and blah. The weather equivalent of a shrug.",
  "Not freezing, but your nipples know something's up.",
  "Bundle up a bit, you fragile little bean.",
  "That annoying 'is it a coat day?' temperature. It is.",
  "Grey, cold, forgettable. Like a Monday with a body.",
  "Not great. Not terrible. Just kind of... there.",
  "The weather equivalent of a middling Yelp review.",
  "Forty-ish degrees and zero personality. Dress warm.",
  "This is coat weather. The coat knows. The coat is ready. Are you?",
  "The sky said 'meh' and meant it.",
  "Uninspiring conditions. Dress like you have somewhere to be anyway.",
  "Cold but not 'dramatic about it' cold. The boring kind.",
  "This weather has the energy of leftover rice.",
  "The universe said 'fine' and set the thermostat to fine.",
  "It's cold in that forgettable way. Like a coworker whose name you've forgotten.",
  "Weather: mediocre. Your commute: still happening. Dress for it.",
  "Bundling up isn't optional today, you delicate little thing.",
  "It's the temperature equivalent of a half-hearted shrug from God.",
  "Not the worst day. Not the best. Right in the barrel of blah.",
  "Forty degrees and overcast. The weather equivalent of a cancelled plan.",
  "Wrap something around yourself. This cold is boring but it's still cold.",
  "The day arrived in greyscale. Dress in color. Reject the vibe.",
  "This weather wants to dampen your spirit. Resist. With a coat.",
  "Cold enough to bite, not enough to be interesting. Story of this temperature.",
  "Meh degrees outside. Full-send on the coat.",
  "This weather has no notes. No soul. Just chilly grey mediocrity.",
  "Put a coat on, genius. The sky isn't getting warmer for you.",
  "It's about as exciting as your most forgettable Tuesday.",
  "The temperature is dull and so is the sky. Your outfit doesn't have to be.",
  "Cold-adjacent. Not cold-committed. Either way: coat.",
  "Forty degrees says 'wear a coat.' The coat agrees. The coat is right.",
  "The weather has given up on ambition today. Don't follow its example.",
  "It's like the weather is on hold music. You're stuck in it. Dress warm.",
  "This is that cold that creeps. Not the honest kind. The sneaky kind.",
  "Grey and cold and fine. Just fine. Absolutely just fine.",
  "Bundle up. You're not as tough as you think and the cold absolutely knows it.",
  "The temperature is doing the meteorological equivalent of a sigh.",
  "It's chilly in a tedious way. Functional coat weather.",
  "Temperature today: forgettable. Your outfit: hopefully not.",
  "The sky and the temperature are colluding to do nothing interesting. Respect it anyway.",
  "Coat on, expectations low, you're already ahead of this day.",
  "Bleak. Functional. Cold. Put on a coat and carry on.",
  "The weather is gray flannel and bad decisions. Dress for the flannel.",
  "Cold enough that the wind makes it personal. Cover up.",
  "This is the weather nobody has a favorite memory in.",
  "Meh weather gets meh results. Fight it with a good coat.",
  "That dull cold that makes staying in feel rational and going out feel necessary.",
  "Forty-something degrees. Not newsworthy. Still cold. Still requires a coat.",
  "The temperature has shrugged and shuffled off to wherever dull cold goes.",
  "Cold and forgettable. Like most of November.",
  "Wear your coat. The temperature isn't interested in your toughness today.",
  "It's the kind of cold that doesn't bite, it just kind of... lingers awkwardly.",
  "Not inspiring. Not terrible. Just a grey cold Tuesday of a temperature.",
  "The weather is in a mood. The mood is: adequate coat weather.",
  "This kind of cold doesn't earn a dramatic coat. But it earns a coat.",
  "The chill today is persistent but not passionate. Dress for persistence.",
  "Layer up. This cold is too boring to be survived with enthusiasm, but still cold.",
  "The weather equivalent of a mumbled apology. Not satisfying, but there.",
  "Cold, dull, and slightly damp. Bundle up, fragile little thing.",
  "This temperature can't commit to anything. Your coat can commit. Bring it.",
  "It's that cold where you go outside, think 'huh, that's cold,' and nothing else happens.",
  "The thermometer today is doing the bare minimum. So should you. With a coat.",
  "Forty degrees and an overcast sky with absolutely no notes.",
  "A cold day that forgot to be interesting. Your coat doesn't care if it's interesting.",
  "This temperature is the meteorological equivalent of a shrug emoji.",
  "It's cold enough to be annoying and not cold enough to be dramatic. Worst of both worlds.",
  "Put on the coat. Stop negotiating with the cold. The cold doesn't negotiate back.",
  "Today's forecast: bleak but manageable. Your mood: optional.",
  "Chilly in that low-key spirit-crushing way. Fight it with caffeine and a coat.",
  "Grey skies, cold air, zero plot. Bundle up and make your own narrative.",
  "Not dramatic cold. Just persistent cold. The most annoying kind.",
  "This temperature is the meteorological equivalent of elevator music.",
  "The cold today has no character. Your jacket does. Let it do the work.",
  "Cold-ish. Blah-ish. Coat-ish situation confirmed.",
  "The kind of cold that makes the indoors feel like a moral victory.",
  "Temperatures hovering in the gray zone where you can't even complain properly.",
  "Your nipples haven't issued a full alert, but they've filed a complaint.",
  "This weather is built for beige. You are not beige. Dress accordingly.",
  "Cold enough to remind you it's cold. Not cold enough to forgive you for forgetting a coat.",
  "Meh weather for a meh morning. Your coat says we can do better.",
  "The kind of cold that hunches shoulders and kills ambition. Coat prevents this.",
  "Today the weather is a bureaucrat. It's cold, it doesn't care, and it expects compliance.",
  "Neither hot nor cold, and therefore annoying. Dress for annoying.",
  "This temperature is exactly as interesting as watching paint dry. Still cold, though.",
  "Cold enough to need a coat. Bleak enough to make you resent it.",
  "The temperature is in a holding pattern: not great, not leaving.",
  "Wrap up a little. You look fragile and the wind agrees with me.",
  "Cold, grey, and committed to doing absolutely nothing impressive. Bring a coat anyway.",
  "The weather today is a callback to every bad commute you've ever had.",
  "It's that temperature where you briefly hope you can skip the coat and you cannot.",
  "The sky today is the color of broken promises.",
  "Forty-degree cold with a side of existential blah. Jacket recommended.",
  "This weather has the enthusiasm of a third-choice candidate. Still elect a coat.",
  "The cold today doesn't have a personality. It just has presence. Acknowledge it.",
  "A coat is not a choice today. A coat is a conclusion.",
  "It's the kind of day where even the weather looks like it needs a coffee.",
  "Thoroughly unexciting cold. Still cold, though. Still requiring a coat.",
  "The forecast shrugged. The temperature followed. Your coat didn't ask.",
  "This cold won't give you a story to tell. Just a reason to wear a coat.",
  "Not inspiring weather. Not terrible weather. Weather that exists and is cold.",
  "Bundling up: required. Drama about it: optional but understandable.",
  "The sky is phoning it in. Your coat doesn't have to.",
  "Cold in a way that makes you feel nothing except slightly chilly. Dress for chilly.",
  "This temperature is neither a friend nor an enemy. It's a coat situation.",
  "Grey and chilly and refusing to commit to anything. Classic.",
  "Today the cold is competent but uninspired. Your job: be the opposite. With a coat.",
  "This is the 'I told you to bring a jacket' temperature. Someone told you. They were right.",
  "The weather has done the bare minimum. So has your enthusiasm. Bring a coat.",
  "Cold enough that your body is considering its options.",
  "The temperature is what fine-but-cold looks like in real life.",
  "Chilly, grey, and quietly resentful. Classic in-between weather.",
  "If this weather were a person, it would cancel plans via text.",
  "This cold doesn't have a plot. Wear a coat. That's the whole plot.",
  "The temperature is unremarkable. Your coat should be remarkable.",
  "Forty degrees is technically above freezing and also still cold as hell. Coat.",
  "The air is cold and the sky is grey and you know exactly what to do about it.",
  "Low forties: the purgatory of temperatures. At least purgatory had a coat rack.",
  "Blah weather for your blah errands. Dress like you'll be outside anyway.",
  "This is that cold that doesn't announce itself — it just slowly makes you unhappy.",
  "Bundle up, buttercup. This isn't the cold to underestimate.",
  "The weather is a beige sedan today. Put on your coat and get in.",
  "Tepid, grey, forgettable. The weather equivalent of tap water.",
  "Cold without commitment. Annoying without effort. Get a coat.",
  "The temperature has all the excitement of a parking ticket.",
  "Jacket weather. Not glamorous jacket weather. Functional jacket weather.",
  "Cold but boring about it. Your coat is neither. Let it shine.",
  "It's what cold looks like when it doesn't want to try.",
  "This temperature exists in a space between 'meh' and 'ugh.' Dress for both.",
  "Not dramatically cold. Quietly cold. The kind you forget until you're out in it.",
  "The air is cold and uninteresting. Your coat doesn't have to be interesting, just on.",
  "A whole day of this grey stuff. Your coat is the plot twist.",
  "Bundle up, fragile one. The cold will not be moved by your stubbornness.",
  "This weather's personality is 'adequate.' Your outfit: shoot for more.",
  "Cold in the sense that your hands will be cold and you'll be annoyed. Pockets help.",
  "Forty-ish degrees is where the cold starts being rude about it.",
  "The weather today is the meteorological equivalent of forgetting what you went to the kitchen for.",
  "Not the kind of cold people write songs about. Just the kind you wear a coat in.",
  "Low ambition temps today. High ambition coat today.",
  "This cold is subtle and persistent, like a rumor or a bad song you can't shake.",
  "Exactly cold enough to punish you for not bringing a coat. Bring the coat.",
  "The forecast is shrug. The appropriate response is coat.",
  "If the weather were a film it'd be rated C for Cold and Completely Forgettable.",
  "In-between temperatures for in-between moods. Dress like you mean it anyway.",
  "Cold, grey, and slightly damp in spirit. Layers are your best friend today.",
  "This temperature is just a prelude to being cold. Act accordingly.",
  "The air has teeth but they're baby teeth. Still coat weather, though.",
  "Low forties: the demographic of cold that nobody champions but everyone experiences.",
  "Grey all the way down. Warm yourself from the inside with coffee and outside with a coat.",
  "This cold is unimpressive and also inevitable. Your coat is inevitable too. Wear it.",
  "The weather equivalent of being put on hold. Cold, tinny, and endless.",
  "It's chilly and damp and grey and that's just the situation today.",
  "Cold without drama. Still cold. Still a coat situation.",
  "Today's weather is the visual equivalent of a sigh.",
  "Undecided weather. Your coat has decided. Listen to your coat.",
  "Cold enough to need a coat. Not cold enough for people to be impressed you're wearing one.",
  "Today the sky is having a grey area phase. Dress for the grey area.",
  "Bleak but survivable. That's kind of the brand for this temperature range.",
  "Forty degrees of quiet, determined cold. Respect it with a coat.",
  "The temperature is the color grey expressed as a feeling.",
  "Something warm is happening in your coat closet. Go let it happen.",
  "Cold and forgettable the way only an in-between week can be.",
  "This weather makes a strong case for staying inside. Your plans don't care. Coat on.",
  "Not miserable cold. Just inconveniently cold. Which is still cold enough for a coat.",
  "The kind of temperature that makes you reevaluate your coat strategy.",
  "This cold won't kill you. It'll just make you wish you'd grabbed a jacket.",
  "Cold in the background, grey in the foreground, you in the middle with a coat.",
  "A coat is the difference between experiencing today and enduring today.",
  "Your nipples are not confused — they're sending intelligence. Act on that intelligence.",
  "Temperatures in the 'is it really that cold?' range. Yes. It really is. Coat.",
  "This weather is making a low-effort argument for winter. Dress for the argument.",
  "Cold-ish grey-ish blah-ish. Coat-ish is the answer.",
  "This cold is competent and efficient and utterly without charm. Wear a coat.",
  "The type of cold that turns 'I'll just run out quick' into 'I regret this.'",
  "Weather today is neutral-hostile. Your coat is neutral-helpful. Bring the coat.",
  "It's cold in a way that'll sneak up on you if you leave without a jacket. Don't.",
  "Today the temperature is neither here nor there but still manages to be cold.",
  "Low-grade cold today. High-grade reason for a jacket.",
  "The cold today is pedestrian and rude simultaneously. Coat neutralizes both.",
  "Bleak middle-ground cold. Bundle up, you precious anxious noodle.",
  "The weather equivalent of standing in a lukewarm shower that keeps getting colder.",
  "This temperature forgot to bring a personality. Bring yours. And a coat.",
  "Cold in that 'I don't care about you specifically' way. Universal. Coat up.",
  "This is neither here nor there and yet here it is: cold. Coat.",
  "Forty-ish degrees are the weather equivalent of someone saying 'sure, whatever.'",
  "Grey and persistently chilly. Like your last three Mondays. Dress for it anyway.",
  "This cold has commitment issues. Your jacket doesn't. Wear the jacket.",
  "Cold enough that your body is having second thoughts. Your coat doesn't have second thoughts.",
  "Bundling up is self-care today. Call it that if it helps.",
  "The cold is doing its job. Your coat should do its job. That's the whole plan.",
  "This weather is the human equivalent of a handshake — cold, forgettable, necessary.",
  "Cold-ish and grey, the dullest combo in the thermostat's repertoire.",
  "Bundle up, you delicate little creature. This isn't drama weather but it IS coat weather.",
  "Barely above freezing. Your nipples have thoughts. Listen to your nipples.",
  "This temperature exists just to make you question your jacket choices. It is a coat day.",
  "Today's cold is quiet and persistent. Like a bill you forgot about. Coat up.",
  "Not exciting cold. Not brutal cold. Just the cold that makes you sigh and put on a coat.",
  "The weather has clocked in, done the bare minimum, and called it cold. Agree with it. Wear a coat.",
  "Today's weather shrugged and walked away. Your coat didn't shrug. It stayed. Be the coat.",
  "The sky is a study in grey. Your coat closet is a study in options. Pick one.",
  "Forty-degree grey nothing. Wear something warm and get through it, champ.",
];
