export const NICE: readonly string[] = [
  "Chef's kiss weather. Don't waste it doom-scrolling.",
  "This is the good shit. Get out there.",
  "Mild as hell. No excuses today.",
  "Weather so nice it's almost suspicious.",
  "Light jacket, big attitude. You got this.",
  "Absolutely nothing to complain about, which is weird for you.",
  "It's gorgeous out. Put your pants on.",
  "The sky is showing off and you're still in bed. Shameful.",
  "Perfect. Absolutely fucking perfect. Go touch some grass.",
  "Not a cloud in sight. Your excuses are also invisible today.",
  "This is that weather people write shitty poetry about.",
  "Go outside before it turns into something miserable.",
  "The sun is out, the birds are loud, and you're wasting it.",
  "Genuinely delightful. Don't ruin it by staying inside.",
  "You've been waiting for this. It's here. Move.",
  "The universe handed you a free pass. Use it, genius.",
  "Outdoor weather. The real kind. Not 'quick errand' weather.",
  "Even your most boring park walk slaps today.",
  "Put your damn shoes on. The weather is better than your excuses.",
  "Forecast: excellent. Your plans: dogshit. Fix that.",
  "This is the weather gods saying 'you're welcome, idiot.'",
  "Temperature's doing everything right. You should too.",
  "Light breeze, warm sun, zero reasons to be indoors.",
  "It's like the weather read your therapy homework and delivered.",
  "A walk in this would cure whatever's wrong with you. Probably.",
  "Great out. Criminally good, actually.",
  "The kind of day that makes you forget you hate everything.",
  "Mild and magnificent. Get out there and be a person.",
  "No heat, no cold, just vibes. Pure fucking vibes.",
  "Your ancestors survived plagues for you to go outside today.",
  "Zero complaints from the meteorological department. Zero excuses from you.",
  "Statistically perfect. Don't waste the data point.",
  "This is what weather looks like when it's trying to impress you.",
  "Comfortable enough that even your inner goblin wants fresh air.",
  "Seventy degrees and a light breeze. Nature's calling you a coward.",
  "Ideal conditions for a human being to exist outdoors. Just saying.",
  "The weather is giving 10 out of 10. You're giving 3. Step up.",
  "Honestly a bit insulting how good it is out there.",
  "The kind of day that makes joggers smug. Become the smug jogger.",
  "It's not going to be this nice forever. Clock is ticking.",
  "Your future self will regret not going outside. Your future self is always right.",
  "Nature sent a chef's kiss and you're ignoring the RSVP.",
  "So nice out that birds are genuinely embarrassing themselves singing.",
  "The sun is working overtime. Match that energy.",
  "Even the wind took the day off. That's how good this is.",
  "Perfect weather for staring at your phone in a park instead of inside.",
  "It's too nice to be gloomy. Reschedule the gloomy.",
  "Moderate and magnificent. Dress like a human and go.",
  "The trees are gorgeous and they're judging you for not being out there.",
  "This weather is basically begging you to have a good day.",
  "Conditions: ideal. Attitude: your problem, not the sky's.",
  "Clear skies, good temps. The universe is doing its part. Are you?",
  "No complaints. From weather or from your mom. Rare alignment.",
  "The air out here doesn't even smell like regret today.",
  "Your jacket stays on but your mood goes up. Simple math.",
  "Whatever you were planning to stay home for: cancel it.",
  "Perfect weather for a walk, a picnic, or admitting you need both.",
  "Absolutely ripping outside. Get ripped on fresh air.",
  "It's giving 'childhood summer' energy and you're being a coward.",
  "Pleasant. Breezy. You have no excuse, you beautiful disaster.",
  "Today the weather wins. You can win tomorrow.",
  "Even your knees feel good in this. Trust the knees.",
  "This is the part of the movie where you go outside and everything changes.",
  "The forecast is aggressively reasonable today.",
  "Mild perfection. Wear what you want. You'll be fine.",
  "No coat, no sweat, no problem. Get the hell outside.",
  "Everything is cooperating except you. Fix that.",
  "The kind of weather that makes strangers nod at each other like idiots.",
  "If this doesn't make you want to go outside, check your pulse.",
  "Delightful conditions. Almost aggressively so.",
  "Not too hot, not too cold. Goldilocks would be losing her mind right now.",
  "The sky is doing a fantastic job. It would like you to acknowledge that.",
  "You could eat lunch outside today. You absolutely should.",
  "Temperature sitting at chef's kiss degrees. Get out there.",
  "No thermals required. No heavy coat required. No excuses required.",
  "This weather is proof the universe occasionally gives a shit.",
  "Conditions are elite. You're optional, but encouraged.",
  "Sunshine and moderate temps. God's apology for last week.",
  "Gorgeous, you ungrateful bastard. Go appreciate it.",
  "Weather this good only happens a few times a year. Don't blow it.",
  "Objectively a banger of a day. Subjectively, your call. Wrong call.",
  "Go be one of those annoyingly happy people in the park. Just for today.",
  "Temperature is perfect. Your posture, however, is not.",
  "Lovely day. Shame if someone sat inside on it.",
  "Nature is showing off today. Rude not to watch.",
  "This is what you moved here for. Or should have.",
  "Ideal weather for a creature that walks upright. That's you. Go.",
  "Even the pigeons look happy today. Take notes.",
  "Today's weather brought to you by 'what the hell are you still doing inside.'",
  "Outside: great. Inside: your own problem.",
  "This is prime 'leave your phone at home' weather.",
  "Genuinely no reason to stay inside. The court rests.",
  "Today the weather is winning every argument you have.",
  "Don't be the person who checked the weather and still didn't go out.",
  "Wear a light jacket or don't. Either way, you'll be fine. That's the point.",
  "The sun is making today its business. You should too.",
  "Low effort weather. High reward. Get out there.",
  "Seasonal perfection. Statistically rare. Move your ass.",
  "Today is an A-plus weather day. You're currently failing the class.",
  "It's mild enough that even your excuse-brain has nothing to say.",
  "The forecast is so good it's almost offensive.",
  "Outside smells like hope and slightly damp earth. That's good. Go.",
  "Even your laziest self deserves this weather. So go deserve it.",
  "Soft breeze. Good light. You look great, probably. Go find out.",
  "Temperatures in the zone where you forget you have problems. Enter the zone.",
  "Sky is clear, birds are doing something, go investigate.",
  "That sweet spot where you're comfortable still and comfortable moving. Rare. Use it.",
  "The weather is asking nothing of you except your presence. Show up.",
  "Today was designed by someone who gives a shit about you.",
  "Zero layers required. Zero brain cells required. Just walk.",
  "If you don't go outside today, the weather will remember.",
  "Seasonally correct. Morally required to enjoy it.",
  "This is the part where you decide to be a person. Be a person.",
  "The weather is not going to wait while you finish your episode.",
  "Mild, lovely, a little smug about it. Join it.",
  "A good ten degrees from anything worth complaining about.",
  "Mother Nature cooked today. At least show up to taste it.",
  "The only bad decision you can make today is staying inside.",
  "Beautiful weather for someone who isn't being an idiot. Which is you, today.",
  "It's not perfect — it's better than perfect, and you're wasting it.",
  "Wear the light jacket. Breathe the air. Unlock your inner golden retriever.",
  "We're in the sweet spot and it won't last. Get out.",
  "Fresh air won't kill you. It'll probably help, you indoor creature.",
  "The sky is 100% doing the right thing. Your turn.",
  "Officially: good weather. Unofficially: get off the couch.",
  "Peak 'grab a coffee and walk' conditions. Do the thing.",
  "You were made for exactly this temperature. Get out there and prove it.",
  "No gloves. No umbrella. No excuses. Just shoes and a pulse.",
  "The vibe outside is immaculate. The vibe inside is you on a screen. Choose.",
  "It's the kind of day you'll lie about to your therapist. 'Yeah, I got outside.'",
  "Genuinely nice. Almost suspiciously nice. Check for traps, then go anyway.",
  "It's brisk-free and cloud-light. Your ancestors would be jealous.",
  "Even the grumpy old man down the street is outside. Beat him.",
  "One of those days where you forget the weather ever sucked. File that away.",
  "The conditions are doing the damn work. Your job is just to show up.",
  "Objectively beautiful. Go be a part of it, you sedentary wonder.",
  "The temperature is neither here nor there — it's exactly there. Go there.",
  "You're going to die someday. Not today's forecast. Today's forecast: pleasant.",
  "Today the weather asked you out. Say yes, you idiot.",
  "Absolutely nailing it out there. Can't say the same for your effort level.",
  "This is a 'wear a light jacket and feel like a movie character' kind of day.",
  "Perfect conditions to go outside and stare at things. Any things.",
  "The horizon is doing great. Pop your head out and acknowledge it.",
  "Delightful temps and a light wind. Earth is flirting. Flirt back.",
  "Nothing wrong with the weather. A few things wrong with your initiative.",
  "The sun is giving you permission. You don't need more than that.",
  "This exact weather convinced people to move to cities they couldn't afford.",
  "Ten out of ten conditions. You're rating it a two by staying in. Fix it.",
  "Rare event: weather you can't complain about. Mark the date.",
  "It's the kind of day poets would ruin with metaphors. Don't ruin it. Just walk.",
  "Tolerable? No. This is excellent. Call it what it is.",
  "Today: certified gorgeous. You: still making excuses. One of you is doing better.",
  "The air is doing you a favor. Don't ignore favors.",
  "Nobody hates this weather. Nobody. You are nobody's exception.",
  "Even the clouds cleared out. They knew you needed this.",
  "Standing outside in this feels like a free gift. Go get your gift.",
  "Good enough to make you believe in something. Don't overthink it. Go.",
  "Perfect light jacket weather means perfect everything else weather.",
  "Conditions checked. Box ticked. Get moving.",
  "Mother Nature's having a good day. Be a part of it.",
  "Sunlight, breeze, zero meteorological drama. Sounds like a personal problem if you stay in.",
  "Extraordinary ordinariness. The most underrated kind of perfect.",
  "Peak 'eat lunch somewhere other than your desk' weather.",
  "Not a single thing to dread outside. Not one.",
  "The weather equivalent of a high-five from a stranger you like.",
  "Today's forecast is brought to you by 'absolutely no excuses, buddy.'",
  "Mild perfection wrapped in light breezes. Don't shit on it by staying home.",
  "This exact temperature is why people go hiking. You don't have to hike. Just go.",
  "If this is how bad the weather gets, sign me up for more bad weather.",
  "Perfect conditions detected. Get outside, dummy.",
  "Today the weather is being the bigger person. Take the hint.",
  "Sun's out, your excuses are not. Good alignment.",
  "There's no coat heavy enough to justify missing this.",
  "Go touch the outside world. It's doing well today.",
  "This is peak 'walk to get coffee instead of making it' weather.",
  "A perfectly ordinary miracle of a day. Go be in it.",
  "The sky is a masterpiece and you're skipping the exhibit. Rude.",
  "Seventy-something degrees. Everything is forgiven. Go.",
  "Today's conditions: no notes. Your plans: several notes.",
  "You don't deserve this weather, but you're getting it anyway. Say thanks by going outside.",
  "Even your shadow looks better on a day like this.",
  "Good temp, good light, good air. The holy trinity. Go worship.",
  "This day was custom built for you, you lucky bastard.",
  "Weather report: better than your entire last month. Go enjoy one damn day.",
  "The outside is doing everything right. Your job is to show up.",
  "Certified perfect day. Your certification pending. Go get it.",
  "No sweating, no shivering, just existing outside like a champion.",
  "Weather so fine it should be illegal. Catch you outside.",
  "Today's the day. You know it is. Stop reading this and go.",
  "This is that rare weather that doesn't ask anything of you. Just exist outside.",
  "Jacket optional. Mood improvements mandatory.",
  "The weather hit a ten and you're over here nursing a two. Get out.",
  "Windows open, shoes on, ass outside. In that order.",
  "Today was made for walking around aimlessly with coffee and no agenda.",
  "Mild as a good dream. Step into it, you couch goblin.",
  "A perfect day to remember that fresh air is free, you absolute hermit.",
  "This weather is actively good for you. Go collect your free healthcare.",
  "The birds, the breeze, the temps — all doing their job. Are you?",
  "Outside is aggressively better than inside right now. That's the whole forecast.",
  "This is the universe's argument for owning good walking shoes. It's winning.",
];
