export const NIGHT: readonly string[] = [
  "It's darker than my ex's soul out there.",
  "Pitch black. Perfect cover for your bad decisions.",
  "The streetlights are doing God's work tonight.",
  "Go to bed. Nothing good happens after midnight.",
  "Something's rustling in the dark and it is NOT your business.",
  "Dark as hell out here. Your flashlight app is not helping, coward.",
  "The moon is watching your terrible choices and judging accordingly.",
  "3 AM. The witching hour. Also your third drunk text of the evening.",
  "It's dark enough to justify bad decisions. You're welcome.",
  "Stars out. Raccoons out. You should not be out.",
  "The night is hiding your face and doing you a favor.",
  "Whatever is moving in that bush, don't investigate.",
  "A possum is making better life decisions than you right now.",
  "Night this dark belongs to criminals and insomniacs. Which one are you?",
  "The dark is like a blanket, except it can't save you from your choices.",
  "The streetlight down the block is flickering. You noticed. Now it knows.",
  "Somewhere out there, a moth is absolutely losing its mind over a bulb.",
  "Your phone screen is the only light you have. Use it to go the hell to bed.",
  "Nothing good was ever texted after 2 AM. Nothing.",
  "The stars don't care about your problems. Beautiful and indifferent, like your ex.",
  "An owl is out there being more productive than you.",
  "Darkness this deep is either peaceful or a sign you should panic.",
  "The night shift is real and they hate you for sleeping through it.",
  "Somewhere a bat just ate a mosquito that was thinking about biting you. Give thanks.",
  "It's so dark, your eyes need a minute. Your life needs longer.",
  "You're doomscrolling in the dark. A raccoon just found a full pizza slice. Think about that.",
  "The void stares back. Blink first and you lose.",
  "Bars are open. Your dignity is not.",
  "Even the neighborhood cat is judging you for being up this late.",
  "The moon's out tonight, mostly to witness your stupidity.",
  "One flickering porch light stands between you and complete existential darkness.",
  "It is dark out here. Not metaphorically. Just literally dark. Go inside.",
  "Your eyes aren't adjusting. That's because there's nothing worth seeing.",
  "The night belongs to those who made worse choices than you. You fit right in.",
  "A werewolf would be a step up from whatever's lurking out there.",
  "Nighttime is when raccoons are professional. You're still an amateur at living.",
  "The shadows know what you did last Tuesday.",
  "Pitch black outside. Your flashlight battery is at 4%. Pray.",
  "Don't go outside. This is exactly how horror movies start.",
  "A possum just hissed at something in the dark. That something might be you.",
  "The darkness doesn't judge. It just watches. Silently. Always.",
  "You should be asleep. The raccoons are disappointed in you.",
  "It's the kind of dark where every sound is a serial killer.",
  "Nobody important is awake right now. Except you. And you're barely trying.",
  "The stars are pretty tonight. You won't notice because you're staring at a screen.",
  "Whatever you're thinking about texting -- don't. 3 AM lies are expensive.",
  "The moon is full. So is your regret.",
  "Late-night snacking in the dark. You know who you are.",
  "Your sleep cycle is completely annihilated. Congratulations.",
  "The dark is doing your appearance a favor. Accept the gift.",
  "Somewhere out there, vampires are networking. You should be sleeping.",
  "Headlights sweep by and for a second you wonder if you're being hunted.",
  "It's quiet out. Suspiciously quiet. Too quiet.",
  "You should go to sleep, but the internet has one more thing to show you. Always one more.",
  "The neighborhood at 3 AM hits different. Mostly sadder.",
  "A moth just flew into a light and died convinced it made the right choice.",
  "Even the cats have gone inside. You're the last idiot standing.",
  "The stars are undefeated. You? Iffy.",
  "Night this dark and you're checking your ex's Instagram. Pathetic and relatable.",
  "The darkness is a blanket. The existential dread is the pillow.",
  "Bad decisions made before midnight get worse after it. Documented fact.",
  "Some things only come out at night. You're one of them.",
  "Somewhere a drunk guy is telling a story that peaked at the third sentence.",
  "The moon doesn't care how late you stay up. Neither does your regret, frankly.",
  "It is genuinely dark out here. Like, 'stumble into your own furniture' dark.",
  "The night sky is beautiful and you're wasting it doomscrolling.",
  "Nighttime: proof that the universe is 95% darkness and 5% your bad decisions.",
  "You were supposed to be in bed two hours ago. And yet.",
  "Even insomnia has standards. Yours are lower.",
  "Whatever you heard outside, leave it alone. It's none of your business.",
  "The dark hides a lot of things. Most of them aren't good.",
  "It's late. Your brain is mush. You're reading a weather app. Seek help.",
  "Late night drive through an empty city hits different after a few bad months.",
  "The street is empty, dark, and full of poor choices waiting to happen.",
  "The universe is mostly void. You personally are about 30% void right now.",
  "It's pitch black and you're still awake. The void is proud of you.",
  "Darkness: free, eternal, and better company than most people you know.",
  "Night hours are when your phone becomes a weapon of mass self-destruction.",
  "The lone streetlight on your block is carrying more emotional weight than your therapist.",
  "It's dark enough out here that a vampire would feel at home. You probably would too.",
  "You didn't get a booty call because nobody wants to navigate this darkness.",
  "The moon is your only friend right now and it isn't answering texts.",
  "At this hour, every decision feels brilliant and you'll pay for it when you wake up.",
  "The dark is free, democratic, and entirely devoid of good ideas.",
  "Three raccoons just organized better than your last team meeting.",
  "The night shift workers out there deserve a raise. You deserve a bedtime.",
  "Every horror movie character that said 'I'll be right back' said it at night.",
  "Your eyes are red and the bags under them have carry-on luggage.",
  "The dark of night is where ambition goes to take a nap and never wakes up.",
  "Somewhere a bartender is already tired of this guy's story. Be better.",
  "Night air, bad decisions, someone's car alarm in the distance. Classic.",
  "The stars have been here five billion years. You're awake past midnight for no reason.",
  "It's not insomnia if you never tried to sleep. That's just chaos.",
  "A bat is pulling off aerial maneuvers right now that you couldn't manage sober.",
  "The darkness swallowed the street whole and didn't even burp.",
  "You're awake, you're bored, and you're going to regret this tomorrow.",
  "The night is young. You are not. Go to bed.",
  "Every terrible idea sounds better in the dark. That's the trap.",
  "The shadows know your shame and have no plans to forget it.",
  "Last call was an hour ago. You missed it. Time to make worse decisions at home.",
  "The walk of shame works best in darkness. You're prepared.",
  "Your porch light gave up months ago. The darkness appreciated the gesture.",
  "This late at night, even your good ideas are trash.",
  "The stars are infinite. Your excuses for being awake are getting repetitive.",
  "It's dark out, and somewhere a possum is pretending to be dead. Role model.",
  "Whatever glowing eyes are in that bush, mind your business.",
  "The moon saw everything you did tonight and kept quiet. Suspicious.",
  "Late night brain worms are the worst. The answers always sound wise at 2 AM.",
  "Dark as a politician's conscience out there.",
  "Night this thick should come with a warning label.",
  "The darkness is immersive. Like a horror game, but you can't save.",
  "You're still awake and the raccoons have completed their third heist tonight.",
  "Night owls are just insomniacs who convinced themselves it was a personality.",
  "The last bar just called time. The bad ideas are just getting started.",
  "An owl is judging you from a tree. It's been there for hours.",
  "You are checking your phone in total darkness like a gremlin. Relatable.",
  "Nighttime is when the city pretends it's a movie. It's not. It's just dark.",
  "The darkness has no opinions on your choices. It just witnesses.",
  "Your neighborhood looks different at night. Worse.",
  "Bats are the only ones out here with their shit together.",
  "The moon is full and your life is half-empty at best.",
  "Nothing good lives in the darkness except raccoons, and they're criminals too.",
  "Insomnia is your body's way of saying it hates you.",
  "Night this dark and you're texting someone who isn't going to text back.",
  "The universe is dark and cold and vast. So is your ex's apartment, probably.",
  "Vampires are out tonight. They're better dressed than you.",
  "Every light in the neighborhood is off except yours. Think about that.",
  "The shadows outside look like shapes. They are shapes. Don't make them a thing.",
  "Somewhere out there, a cat is screaming at nothing. Valid.",
  "You're exhausted but still awake. This is a hostage situation with your own brain.",
  "Street empty, lights low, you've officially entered the 'stupid decision' district.",
  "The dark is honest. It shows you nothing and hides everything.",
  "Late night pizza will fix nothing except your hunger. Get it anyway.",
  "A raccoon just made eye contact and didn't flinch. That's respect and a threat.",
  "Dark as the inside of a horse out there.",
  "Night air and poor choices: the official scent of staying up too late.",
  "The clock says 3 AM. Your body says 3 AM. Your dignity left at midnight.",
  "Nothing open at this hour except regret and drive-throughs.",
  "The dark is all-inclusive. It accepts your bad decisions without judgment.",
  "Even your subconscious has checked out. Just the dumb part of your brain now.",
  "No alarm. No schedule. No shame. That's the night for you.",
  "The streetlight at the corner is the loneliest object in your neighborhood right now.",
  "Whatever you're overthinking at 3 AM will be a non-issue at 9 AM.",
  "The void called. It wants you to get some sleep.",
  "Night birds are singing. You're awake. Both of you have questionable lifestyles.",
  "Darkness wraps around everything and makes bad ideas look cozy.",
  "It's past midnight and your search history is embarrassing your ancestors.",
  "The glowing screen in your hand is the only star you'll see tonight.",
  "Night this dark, a stranger's porch light starts to feel personal.",
  "Your circadian rhythm filed a missing person report on you months ago.",
  "The dark doesn't have opinions. It just has consequences.",
  "Somewhere a night security guard is watching CCTV and eating cold fries. Solidarity.",
  "You're awake because your brain refuses to shut up. Relatable. Annoying. Go to sleep.",
  "The stars are gorgeous. You're too busy spiraling to notice.",
  "Late-night you and next-day you are legally distinct people with different agendas.",
  "The night is a cover charge for whatever dumb thing you're about to do.",
  "Your porch light is on. Everything else is dark. You're a beacon for nonsense.",
  "Darkness this complete is either peaceful or a sign you've made a terrible mistake.",
  "The raccoons have a better union than most of the people you work with.",
  "Whatever's howling in the distance, it's not your problem unless it gets closer.",
  "The dark brings out the wildlife, the weirdos, and the wonderfully irresponsible.",
  "You shouldn't be outside right now. At least take a buddy.",
  "It's late and your phone is at 8%. Poor planning on every level.",
  "The night sky is full of stars that died before your great-great-grandparents were born. Sleep tight.",
  "Somewhere out there, a drunk person is confidently going the wrong direction.",
  "Nighttime is when the city's infrastructure reveals its crimes.",
  "The dark swallows sound and returns it as something worse.",
  "You've been awake so long your thoughts are just static and regret.",
  "Last light is out and you're still making plans. Bold. Stupid. Probably both.",
  "Pitch black and you're doomscrolling. The raccoons are right to judge you.",
  "A cat just started a full yowl-fest at 3 AM with zero explanation and zero apologies.",
  "The night hides your face, your choices, and most of your mistakes. Gratitude.",
  "An owl hooted outside and your heart rate hit 180. Calm down.",
  "Your eyes are dry, your phone is hot, and it's past midnight. This is a cry for help.",
  "Darkness makes cowards of us all and romantics of the drunk ones.",
  "The moon is enormous tonight. It sees you. It has always seen you.",
  "Even the 24-hour gas station clerk is judging the reason you're there right now.",
  "Nobody told the stars you were having a bad night. They don't care anyway.",
  "Night this dark, your GPS is the only voice of reason and it's still wrong.",
  "Somewhere out there, a drunk person just sat down on a curb and reconsidered their choices.",
  "The dark holds secrets. Most of them are embarrassing. All of them are yours.",
  "Late night, porch light, bad idea, good story.",
  "Nighttime sobriety check: if you have to think about it, you failed.",
  "The stars are old, cold, and completely indifferent. Vibe.",
  "Darkness is when the city finally drops the act and shows its real face.",
  "A bat is using echolocation to not die. You're using your phone light and failing.",
  "Night shift and day shift exist. You? You're just shift-less.",
  "The moon is a judgment-free zone, which is more than your group chat can say.",
  "Whatever noise that was outside, it's fine. It's probably fine. Don't look.",
  "Your eyes are adjusted but your life isn't.",
  "Night this dark, you're either brave or too tired to be scared. Could go either way.",
  "The whole neighborhood is asleep and you're out here having a whole crisis.",
  "You and the moths both keep flying toward things that are bad for you.",
  "The dark is full of wonders, mostly raccoons and regret.",
  "Somewhere a neon sign is buzzing in an empty parking lot. That's the most honest thing in town.",
  "Sleep is calling and you keep sending it to voicemail.",
  "Night air in your lungs. Bad choices in your head. Same as it ever was.",
  "Dark as a dungeon and you're still awake reading this. Superb judgment.",
  "The coyotes are out tonight. No advice. Just wanted you to know.",
  "Nighttime: the free trial of what rock bottom feels like after enough bad calls.",
  "Your night-vision is trash. Your judgment is worse. Stop walking around.",
  "The dark doesn't owe you anything and you've been asking a lot of it.",
  "Somewhere a bouncer just turned someone away for the third time tonight. Perseverance.",
  "It's so dark out here, even your shadow gave up and went inside.",
  "The only things open right now are diners, regrets, and your DMs.",
  "Night owl or just bad at sleeping? We know the answer. So do you.",
  "The moon rose and your standards dropped. Coincidence? Probably.",
  "Stars are out, trash cans are knocked over, and somewhere a possum found a whole taco.",
  "Night this deep and your phone autocorrects to whatever it thinks you're trying to confess.",
  "Whatever you just saw move in the shadows, it saw you first.",
];
