export const RAIN: readonly string[] = [
  "One day it started raining, and it didn't quit for four months. — Forrest was onto something.",
  "We been through every kind of rain there is. Little bitty stingin' rain, and big ol' fat rain.",
  "It's pissing down. Bring the damn umbrella.",
  "Rain with a bad attitude. Waterproof your soul.",
  "Wet-ass weather out there.",
  "Perfect day to stay in bed and ignore your responsibilities.",
  "It's raining sideways, which is just nature flipping you off.",
  "The sky opened up like it has a personal vendetta against your shoes.",
  "Rain so heavy even the ducks are like 'this is a bit much'.",
  "If you go out without an umbrella, you deserve everything that happens to you.",
  "Nature's pressure-washing the city. Unfortunately you're in the way.",
  "This rain isn't here to play. Your dry clothes are already a memory.",
  "It's raining buckets. Not metaphorically. Actually buckets.",
  "The heavens have opened and they are not happy about it.",
  "Rain: the universe's way of saying cancel your plans and sulk.",
  "Get a raincoat or get wet. There is no third option.",
  "Everything is soaked. Your soul is next.",
  "Today's forecast: saturated as hell.",
  "It's raining like someone up there knocked over a really big cup.",
  "The kind of rain that gets inside your shoes and ruins your whole philosophy.",
  "This rain has commitment issues — it just keeps coming.",
  "Your umbrella is the only relationship that matters right now.",
  "Rain so relentless it's basically a personal attack.",
  "It's officially too wet to pretend going outside was ever a good idea.",
  "The sky is crying. We don't know why. We respect the process.",
  "Downpour incoming. Your hair already gave up.",
  "Even the pigeons are sheltering. Follow their lead.",
  "It's raining like the clouds owe somebody something.",
  "Everything outdoors is now aggressively wet.",
  "Your commute just became an aquatic adventure. Enjoy.",
  "Rain beating down like it lost a bet and is taking it out on you.",
  "Heavy rain ahead. Your umbrella is somewhere you're not.",
  "Precipitation: excessive. Excuse to cancel plans: legitimate.",
  "The streets are rivers and you're the idiot crossing them in sneakers.",
  "It's a drown-on-your-way-to-the-car kind of morning.",
  "This rain has absolutely no chill.",
  "The outside world is now a waterfall. Stay inside.",
  "Soaked to the bone weather. The bone doesn't even know what happened.",
  "Sheets of rain coming down. Bed sheets staying on. See the logic?",
  "Rain like this is why umbrellas were invented. Use one, genius.",
  "It's raining hard enough to clean the car for free. Unfortunately you're also the car.",
  "The sky is in full monsoon mode. Adjust accordingly.",
  "Your umbrella will flip inside out in T-minus twenty seconds.",
  "This is the rain that makes you question every outdoor decision you've ever made.",
  "Heavy precipitation today. Your shoes will be wet until Thursday.",
  "Downpour so severe it's become a lifestyle.",
  "The rain has arrived with purpose. That purpose is soaking you.",
  "Driving rain. Walking rain. All of it is terrible rain.",
  "It's raining like God is trying to fill a quota.",
  "If you go outside, you're going outside wet. That's the deal.",
  "Rain so thick you can barely see the stupid decision you're about to make.",
  "Wet as hell out there. Everything is moist. Congratulations.",
  "This rain is doing the most. Unfortunately 'the most' is 'drenching everything'.",
  "Umbrella day. Not an umbrella? Good luck, legend.",
  "It's raining sideways and diagonally and every direction umbrellas can't handle.",
  "Classic damp misery out there. Poetic, really.",
  "You want to go outside in this? Bold move. Stupid move. Same thing today.",
  "The kind of heavy rain that makes you feel like the sky is personally chasing you.",
  "Rain hammering the windows like it has something to say.",
  "Every puddle out there is deeper than it looks. Trust nothing.",
  "The weather is aggressively wet and absolutely not your friend.",
  "You don't need to be out in this. Nobody does. Stay.",
  "Even your waterproof jacket has limits. Today is the test.",
  "The sky is power-washing the whole neighborhood and you're part of the schedule.",
  "Raining cats and dogs. Mostly the ones that bite.",
  "Heavy rain advisory: your umbrella is a suggestion and the wind disagrees.",
  "The kind of rain that soaks through 'water resistant' like it's a dare.",
  "This rain is not background noise. It's the main event.",
  "If Noah were alive, he'd be like 'I've seen worse but not by much'.",
  "Rainy days are nature's way of forcing productivity. Or sleep. Your call.",
  "The streets look like rivers. The rivers look like oceans. Go home.",
  "Heavy rain today. Your plans are the collateral damage.",
  "Getting soaked out there is 100% avoidable if you stay inside.",
  "It's raining so hard the gutters are overwhelmed and honestly same.",
  "The umbrella you left at home is mocking you.",
  "Nobody told the rain to calm down and it did not calm down.",
  "Every drop out there is committed to getting you wet. Dedicated little bastards.",
  "Wet outside. Dry inside. This is not a hard puzzle.",
  "Your shoes are already a sacrifice. Accept it.",
  "Today's rain has the energy of someone who's very tired of your crap.",
  "The sky is dumping everything it saved up all week.",
  "Soak outside or chill inside. That's the whole decision.",
  "Rain so heavy the birds are walking.",
  "Welcome to Wet City. Population: everyone who ignored this forecast.",
  "It's raining like the sky just found out about a betrayal.",
  "The gutters are overwhelmed. Your umbrella is overwhelmed. You are soon to be overwhelmed.",
  "Classic unpleasant rain experience happening in real time.",
  "Walking out there without protection is a cry for help.",
  "Rain status: fully committing. Your dry socks: endangered.",
  "It's coming down hard enough to ruin your mascara, your mood, and your afternoon.",
  "The weather today is damp, dreary, and deeply unhelpful.",
  "Every outdoor person is a wet outdoor person today.",
  "Precipitation at peak 'why did I leave the house' intensity.",
  "It's a stay-in-your-pajamas-forever kind of rain and you know it.",
  "Rain this relentless has the audacity of a bad ex.",
  "Hard rain outside. No shame in calling it a couch day.",
  "The clouds have been saving up and today is payday.",
  "Steady heavy rain. Your optimism about the weather was wrong.",
  "Raining like it means it. Because it means it.",
  "Your umbrella won't fix this but it'll make you feel better about yourself.",
  "The sky is doing that thing where it just doesn't stop. Classic.",
  "Drenching rain out there. Your umbrella is now load-bearing.",
  "It's raining sideways, upwards, and in ways that defy geometry.",
  "Rain like this is its own kind of beauty. A terrible, soaking beauty.",
  "The puddles are evolving. They have absorbed the sidewalk.",
  "Heavy downpour. Your car is getting a free wash. You are not.",
  "This rain is here to stay and it brought luggage.",
  "Rain so intense it's practically its own weather event.",
  "The kind of rain that writes you a formal apology, then does it again.",
  "Rain falling at the speed of 'none of your plans are valid'.",
  "Take cover or accept your soggy fate. Both are options.",
  "Rain that would make a waterfall jealous.",
  "It's raining everywhere. Yes, including under your umbrella.",
  "If you needed a sign to cancel your outdoor plans, this is it.",
  "Rain of Biblical proportions. Okay, maybe just Tuesday.",
  "Every inch of outside is wet. Every inch of inside is not. Choose carefully.",
  "Nothing is dry and nothing is going to be dry for a while.",
  "The sky found your address and it has complaints.",
  "Rain so heavy the forecast gave up and just said 'wet'.",
  "The outside is not for you today. The outside is for rain.",
  "Dense, persistent, aggressive rain. It has a work ethic you wish you had.",
  "Today's rain is working harder than you and it's not even employed.",
  "Heavy rainfall incoming. Your umbrella might not be enough. Bring a boat.",
  "This rain has the follow-through your gym routine lacks.",
  "Sky's in full precipitation mode. Forecast for your hair: destroyed.",
  "Rain hammering down with all the subtlety of a wrecking ball.",
  "You asked for weather. Weather answered. It said: wet.",
  "If your shoes aren't waterproof today, your socks are paying the price.",
  "Rain pouring like someone just knocked over the cloud.",
  "The weather today can be described in one word: soaked.",
  "It's basically raining on your parade. Specifically your parade.",
  "This is that 'just five more minutes in bed' rain and it'll last all day.",
  "Umbrella use is not optional. It's survival.",
  "Heavy rain: great excuse, terrible weather.",
  "If you brave this rain, report back. We want to know if it was worth it.",
  "Today the sky woke up and chose violence. The watery kind.",
  "Your outdoor furniture has already accepted its fate.",
  "The rain doesn't care about your schedule. The rain never cared.",
  "Persistent rain: the word 'persistent' here means 'absolutely not stopping'.",
  "Today's weather is wet with a chance of wetter.",
  "This rain is the universe telling you to read a book or drink some tea.",
  "Every umbrella in the city has been conscripted.",
  "Rain so steady it's almost hypnotic. Don't go out there hypnotized.",
  "The clouds are emptying their storage. You're in the drop zone.",
  "Today's rain is an inconvenience at best and a disaster at worst. Pick your lane.",
  "Sustained heavy rain. Outstanding reason to cancel everything.",
  "The window view is just grey and wet and honestly kind of soothing from inside.",
  "Rain's out there doing the absolute most with no remorse.",
  "Downpour of the particularly soaking variety. Classic.",
  "The outdoor world has become a wet obstacle course.",
  "Rain this heavy has no interest in your plans or your feelings.",
  "Full wet misery mode outside. Full dry warmth mode possible inside.",
  "Your umbrella is not a weapon but today it needs to be.",
  "Pouring rain. The kind that tests your resolve and your waterproofing.",
  "The forecast today is: soak it up or stay home. Easy choice.",
  "Rain pounding the city into submission.",
  "It's absolutely raining. Absolutely.",
  "If you ignore this rain, the rain will not ignore you.",
  "Heavy rain day. Coffee day. Inside day. Good day.",
  "Rain's been going all night and shows no signs of apology.",
  "Your commute is wet, your lunch break is wet, your evening walk is wet.",
  "This rain has commitment and unfortunately it's committed to ruining your day.",
  "Rain so heavy it deserves a name. Let's call it 'stay inside'.",
  "The sky has chosen chaos. The chaos is wet.",
  "Drenching rain warning: your optimism has been overruled by meteorology.",
  "Today the sky is a fire hose and you're in the way.",
  "Don't fight the rain. You'll lose. It has the high ground.",
  "The streets are wet, the clouds are full, and your umbrella is still at the office.",
  "It's really, truly, properly raining. No exaggeration required.",
  "This rain is not impressed by your plans. It has its own.",
  "Walking out into this rain is technically your choice. Technically.",
  "Heavy steady rain. The forecast for your good mood: declining.",
  "It's wet. It's miserable. It's your Wednesday now.",
  "Rain with the determination of someone who really needs to prove a point.",
  "Today's precipitation: thorough. Today's forecast: don't bother.",
  "The rain doesn't know your name but it's out to get you personally.",
  "Rain with the dedication of a debt collector who really wants to be paid.",
  "Outdoor plans in this rain are less of a plan and more of a sacrifice.",
  "Everything that was dry is now auditioning for the wet look.",
  "Sustained rainfall. Your resolve is the only dry thing left.",
  "Puddles forming everywhere. Pick your route carefully or accept the splash.",
  "Rain piling up in places you didn't expect rain to reach. Expect it now.",
  "The downpour is thorough, consistent, and completely uninterested in your schedule.",
  "You could brave this rain. You could also just not.",
  "Rain so convincing that staying inside feels like the right answer for once.",
  "Today's moisture level: oppressive.",
  "Storm drain working overtime. Your shoes about to work overtime too.",
  "It's raining hard and slow and all the other annoying ways.",
  "Heavy precipitation covering every inch of the city except where you want it.",
  "The kind of rain that makes you want to move somewhere sunnier.",
  "Rain today. Rain tomorrow. Rain until further notice.",
  "Weather so wet it's redefining what outdoor counts as.",
  "This is rain with a mission. The mission is you, specifically.",
  "Sidewalks: rivers. Roads: rivers. Your mood: also a river.",
  "Rain showing up like it was invited. It was not invited.",
  "Steady and heavy and thoroughly unpleasant. Nothing new, everything wet.",
  "Heavy rain falling on all your good intentions of going outside.",
  "You're not going to want to go outside. Good. Don't.",
  "Rain advisory: maximum moistness in effect.",
  "The precipitation out there is doing a thorough and thankless job.",
  "Downpour with consistent delivery. Zero stars. Would not recommend.",
];
