export const SNOW: readonly string[] = [
  "It's snowing. Build a fort, throw a snowball, act like a child.",
  "Snow-day energy. Call in 'sick,' you legend.",
  "Winter's dandruff is falling. Bundle up.",
  "Snow's coming down. Drive like everyone else is an idiot — they are.",
  "Pretty as hell until you have to shovel it.",
  "Snowflakes are each unique and together they're trying to ruin your commute.",
  "Nature broke out the powdered sugar. Don't eat it.",
  "Snow day! Or as adults call it: shoveling day.",
  "Dig out the car first. Cry second. Shovel the walk third.",
  "The snow is beautiful. The people driving in it are not.",
  "Winter decided to dump, and now you're the one cleaning up.",
  "Snowflakes are falling fast and furious — and unlike those movies, nobody wins.",
  "It's a winter wonderland out there. A cold, miserable, shovel-heavy wonderland.",
  "If you don't have boots, your feet will hate you within three blocks.",
  "Back pain from shoveling is winter's signature gift to adults.",
  "You know who loves snow? Kids. You know who shovels? Adults. Think about that.",
  "Fresh snow looks like a postcard. Moving through it feels like a punishment.",
  "Snow this deep means every step is a commitment you'll regret.",
  "Your car is buried. Pour one out. Then get a shovel.",
  "Snow fell all night, and the plows went everywhere except your street.",
  "Shoveling burns calories and breaks backs in equal measure.",
  "Six inches of snow and your neighbor's already out there showing off. Relax.",
  "Layers. So many layers. You'll look like a marshmallow and feel even more like one.",
  "The snow hides every pothole, curb, and patch of ice. Surprise awaits.",
  "Blizzard conditions mean optional everything. Everything is now optional.",
  "Stay on the paths. The deep stuff will swallow your whole boot and fill it with cold misery.",
  "Snow is nature saying 'slow down' in the rudest possible way.",
  "That snowplow came through 10 minutes ago and already buried your driveway again.",
  "White-out conditions. Stay home. No, seriously. Stay home.",
  "The world looks pristine. Give it two hours and it'll look like a slush slaughterhouse.",
  "Snow: it's pretty for about four minutes before it becomes everyone's problem.",
  "Dress warm enough that even the cold can't find you.",
  "Snow day energy: snacks, blankets, pretending work doesn't exist.",
  "Somebody's gonna throw a snowball today. Let it be you.",
  "School's canceled. Adults everywhere seething with envy.",
  "The flakes are huge and coming down sideways. The atmosphere is embarrassing itself.",
  "Your boots are about to earn their keep.",
  "Shoveling the walk is a great core workout if you hate yourself.",
  "The snow doesn't care that it's Tuesday. Snow respects no schedule.",
  "Wind-driven snow in your face is winter's version of a slap.",
  "Winter looked at your schedule and said 'let's ruin it.'",
  "Make a snowman. Name him something mean. Throw a scarf on him. He deserves it.",
  "Snow angel time. Fall back dramatically. Pretend it was planned.",
  "Every snowflake is unique, and together they're conspiring against your morning.",
  "Your gloves are not enough. Your gloves are never enough.",
  "Hot cocoa isn't optional today. It's infrastructure.",
  "The heater in your car needs five full minutes before it stops blowing cold air at you. Fun.",
  "Snow makes everything look clean. It is a lie.",
  "There's snow in the forecast and idiots in the grocery store wiping out the bread aisle.",
  "Bread and milk fully sold out. Classic panic-snow behavior.",
  "Snow day officially declared. Pajamas are now a dress code.",
  "That first step into fresh deep snow is either delightful or devastating depending on your boot height.",
  "Nature's confetti is piling up fast. Nobody ordered this party.",
  "Heavy snowfall: a great time to remember you never replaced those windshield wipers.",
  "Your windshield wipers are working overtime and they did not sign up for this.",
  "Three inches on the car roof. That's a snow hat your car never asked for.",
  "Do not drive through a snow drift. A snow drift will win every time.",
  "Pulling into traffic slow is wise. Your neighbor disagrees and will spin out at the roundabout.",
  "The road crews are doing their best. Their best is insufficient today.",
  "Snow packed under your boot sole is winter's built-in trip wire.",
  "Snowfall so thick you can't see the end of your block. Cozy? Terrifying? Both.",
  "The trees are gorgeous under the snow. Also, one of those branches is coming down on a power line.",
  "Wind and snow together is called a blizzard. Staying home is called common sense.",
  "The driveway isn't gonna shovel itself, which is profoundly unfair.",
  "Your back will be filing a formal grievance by the time you finish the walk.",
  "Snow day for the school kids. Just a regular shitty commute for you. Life is imbalanced.",
  "Visibility near zero. Drive like you're in a cloud. A soft, cold, murderous cloud.",
  "Snow's making everything picturesque. You've never hated picturesque more.",
  "Winter dropped six inches overnight. Try not to be dramatic about it.",
  "If you shovel once and it keeps snowing, you get to shovel again. That's the deal you made.",
  "Layers: base, mid, outer. Forget one layer and winter wins.",
  "Your car's a snow globe. Congratulations.",
  "Snow plows plowed everything except exactly where you need to be.",
  "Slip-on boots? No. Not today. Not in this.",
  "The kids on your street are having the time of their lives. Ignore them. Shovel.",
  "Snow: the weather event where everyone acts surprised like this doesn't happen every year.",
  "Your driveway has been replaced by a small mountain range. Get the big shovel.",
  "Winter's out here dumping like a breakup text delivered in weather form.",
  "Hot soup today. Non-negotiable. Hot soup is a survival mechanism.",
  "The sidewalk out front won't shovel itself, and your neighbors are definitely judging you.",
  "Let the snow pile up. Let your responsibilities pile up with it. Not today.",
  "Heavy snow. Light visibility. Moderate regret about not working remotely.",
  "Snow turns every errand into a mini expedition you did not prepare for.",
  "The dog loves this shit. You do not. One of you is correct.",
  "Snowfall overnight means your alarm was 20 minutes too late. It just was.",
  "First snowfall of the year and people forget how to drive like it's their first road ever.",
  "Winter snow hitting your face during a walk is nature personally insulting you.",
  "It's a snow day. Declare it officially. Cancel the optional stuff. Nap aggressively.",
  "Snow this deep means your feet will be wet by noon no matter what you wear.",
  "Every step makes that satisfying crunch. Small consolation. Feet still freezing.",
  "Nature's doing a full whitewash of your neighborhood. It looks nice. It sucks.",
  "The snow is falling fast enough that any shoveling you do now will need to be redone.",
  "Winter arrived with no apology and a ton of snow.",
  "It's a whole snowscape out there and your car is buried under its most dramatic accent.",
  "Today's forecast: cold, white, shovely, and full of bad driver energy.",
  "Every plow pass adds a foot of packed snow to the end of your driveway. Science is cruel.",
  "Bundle up. Look ridiculous. Stay warm. Pick two.",
  "Snow is objectively beautiful until it's on your car at 7 a.m. and you're already late.",
  "The roads are covered in white and stupidity in roughly equal parts.",
  "Ice hides under snow. Snow hides under more snow. It's betrayal all the way down.",
  "Your car's exhaust pipe better not be buried or you're in for a very special kind of bad morning.",
  "Shoveling heavy wet snow is a cardio test your doctor didn't prescribe.",
  "Those big fluffy flakes look like a Hallmark movie. They lie.",
  "Call it a snow day. You deserve it. You absolutely deserve it.",
  "The universe decided to white out your calendar for the day. Accept the gift.",
  "Roads slick with snow and traffic backed up for miles. Peak winter experience.",
  "Snow removal is a community effort. Your neighbor is not pulling their weight.",
  "This is the kind of snow that makes you want a fireplace and zero obligations.",
  "Wear your thick socks. Thin sock people are out there suffering and they deserve it.",
  "Everything is slow today. Your commute. Your car. Your will to do anything.",
  "Snow so deep the fire hydrant is gone. No one mention this to the fire department.",
  "Drive steady. No sudden moves. Treat the road like it's watching you.",
  "Nature put a white blanket on everything and tucked in your motivation with it.",
  "Hot coffee number one is a survival move. Hot coffee number two is a victory lap.",
  "Snow and wind are a tag team of winter's worst instincts.",
  "Your car knows it snowed before you even open the door. That's why it's being difficult.",
  "The snow looks fluffy and forgiving. It is not. It is cold and heavy.",
  "Every snow shovel handle is approximately two inches too short for a normal human spine.",
  "Frostbite is not a metaphor. Wear your damn gloves.",
  "Snowball fight rules: no ice balls, no face shots, no mercy.",
  "Today is one of those days winter dares you to leave the house. Call its bluff. Or don't.",
  "The forecast called for flurries. That was a lie of the softest magnitude.",
  "Accumulation looks more like a total hostile takeover of your neighborhood.",
  "Your commute smells like boots, stress, and wet wool today.",
  "Snowfall heavy enough to cancel the things you didn't want to do anyway.",
  "Snow day. The adults who are jealous of school cancellations: valid.",
  "If you leave footprints in pristine snow, you're ruining nature's aesthetic. Worth it.",
  "Snow at sunrise looks like something out of a movie. A very cold, inconvenient movie.",
  "The shovel is in the garage. It's been there since April. It's ready.",
  "The clouds dropped everything they had overnight. Rude. Spectacular. Rude.",
  "Visibility: enough to see your own bad decisions.",
  "The car thermometer said negative numbers. That was a warning.",
  "Feet wet before noon is winter's way of saying it won the day.",
  "Snowfall: the weather phenomenon that unites us all in mild misery.",
  "You thought shoveling was optional. The HOA disagrees.",
  "Your morning plans just added 45 minutes for snow-related logistics. Sorry.",
  "Winter's out here being theatrical as hell and you're just trying to get to work.",
  "Snow on a weekday hits different than snow on a weekend. The universe knows.",
  "Your street's not been plowed yet. Your street will not be plowed for a while yet.",
  "Make the hot drink. Pick the big coat. Cancel the optimism.",
  "Snow so heavy the tree in the backyard is performing a dramatic bow.",
  "Windshield scrapers exist. Use the damn windshield scraper. All of it. Every inch.",
  "Snow made the whole world quiet. Enjoy that second before a snowplow destroys the silence.",
  "That snow is heavier than it looks. Your lower back is about to issue a press release.",
  "Winter's back with another dump and less remorse than ever.",
  "Wet, heavy snow is basically nature's resistance training.",
  "The snowflakes coming down: beautiful. The snowplow wake-up call at 4 a.m.: less so.",
  "Bundle the kids up and send them out. They'll be fine. You'll have five minutes of peace.",
  "Boots, coat, gloves, hat, scarf, dignity — get all of it before you open that door.",
  "Snow. Still snowing. Will continue snowing. Everything is fine.",
  "Your car is a snow-covered tomb. You are the archaeologist.",
  "Winter is out here doing the absolute most and you just needed to buy groceries.",
  "The first person to shovel on your block: a legend. Do it. Be the legend.",
  "Roads are white and slippery and everyone's going either too fast or too slow.",
  "Walk the long way if it means staying on salted ground. Your tailbone thanks you.",
  "Eight inches overnight. Welcome to winter. She didn't knock.",
  "Those big flakes drifting down look peaceful. In your car at 7 a.m., they are the enemy.",
  "Snowfall: the universe enforcing rest you would never take voluntarily.",
  "Visibility is low and every driver's confidence is inversely proportional to their skill level.",
  "Wiper blades freezing mid-swipe is winter's version of a jump scare.",
  "Shovel smart, not hard. Use your legs. Throw the snow far. Regret nothing.",
  "That snow is gorgeous. It's also six inches deep on your car roof and your problem.",
  "Snow is here. Your plans are guests who didn't check the weather before coming over.",
  "Winter blanketed everything in white and forgot to give you the day off.",
  "Go slow. Think slow. Drive slow. Just slow everything down today.",
  "Fresh snow is the universe hitting reset. Too bad your schedule doesn't reset with it.",
  "The snow forecast was right. The one time predictions nail it and you wish they hadn't.",
  "If you can work from home today: do it. Don't be a martyr in a snowstorm.",
  "Your commute is now an adventure. An unwelcome, cold, slippery adventure.",
  "Snow this deep should be someone else's problem but it is definitely yours.",
  "Mother Nature went full 'covering everything' mode. She has no off switch.",
  "The shovel handle is cold. Your back will be sore. Do it anyway.",
  "Six to eight inches overnight. The weather service called it and you ignored the forecast.",
  "Winter wonderland is pretty. Winter workland is not. Guess which one you have today.",
  "All that fluffy white snow comes at a price: suffering, shoveling, and slow roads.",
  "Your beanie is somewhere in the back of the closet. Today it earns its keep.",
  "Drive carefully. The roads are snow-covered and full of people who aren't.",
  "Fresh powder looks like a ski resort. You are not at a ski resort. You are at life.",
  "Snow fell overnight and the world is quieter for it. Briefly. Until the scrapers start.",
  "Every car on the road is a rolling dice roll on road grip.",
  "Make the hot drink first. Everything else second.",
  "Snowstorm: when winter stops being subtle about ruining your week.",
  "Heavy snow says cancel the optional things and double the blankets.",
  "Your driveway is a clean slate. It requires 30 minutes of labor to reclaim.",
  "Snow like this demands soup, slippers, and absolutely no ambition.",
  "Nature's winter edition: cold, white, heavy on the shovel, light on the mercy.",
  "Streets are iced under the snow. The snow is a disguise. Classic winter trickery.",
  "Snow packed against your door handle is winter's idea of a small personal insult.",
  "Stay in the right lane. Drive like you have somewhere to be — which today, maybe you shouldn't.",
  "The snowplow will come through. The snowplow will undo your shoveling. Circle of life.",
  "Temperature's dropping and the snow's not done. A dynamic duo of misery.",
  "Shoveling is a great reminder that winter does not care about your fitness level.",
  "That deep snow step: satisfying crunch, hidden ice, surprise wipeout. Three-act tragedy.",
  "Snow-day vibe requires: hot drink, fuzzy socks, no ambition.",
  "Layer up. Look ridiculous. Be warm. That's the snow day trifecta.",
  "The mountains of snow your plow pushed to the roadside will outlast your will to live.",
  "Snow is here and it brought all its friends. You are outnumbered.",
  "Pull the boots on. Grab the big coat. Accept that today is a snow day whether you like it or not.",
  "Snowflakes are saying nothing and saying it everywhere, all at once, all over your car.",
  "Shoveling builds character. Shoveling heavy wet snow builds resentment.",
  "This is a snow event. This is a survival situation. This is a Tuesday.",
  "Wind chill plus snow equals a weather combo that hates you personally.",
  "You'll shovel. It'll snow more. You'll shovel again. That's winter. That's the deal.",
];
