export const STORM: readonly string[] = [
  "Thor's throwing a tantrum. Stay indoors.",
  "Big dramatic sky-rage happening. Unplug your shit.",
  "Thunderstorm rolling in like it owes God money.",
  "Zeus is pissed. Don't be the tallest thing in a field, dumbass.",
  "Lightning's auditioning out there. Enjoy the show from indoors.",
  "Nature is conducting electricity and you're not invited.",
  "The sky is having a full mental breakdown. Respect that.",
  "If lightning hits you, that's a you problem. Go inside.",
  "Thunder means Zeus is rearranging the furniture. Stay clear.",
  "The atmosphere just declared war. Hunker the hell down.",
  "Unplug your router or don't. I'm a weather app, not your dad.",
  "Sky's doing its loud bastard routine again.",
  "That's not a drumroll, that's Thor warming up. Take cover.",
  "Lightning: nature's way of saying you're in the wrong spot.",
  "Storm rolling in hot. Your WiFi is about to die dramatically.",
  "The clouds are furious and frankly I don't blame them.",
  "God's flicking the lights on and off like a passive-aggressive roommate.",
  "Thunderstorm incoming. Cancel your plans, hug your pets.",
  "Zeus called — he's in a mood. Don't be outside.",
  "Your umbrella is useless here. This is lightning, not sprinkles.",
  "The sky is trying to kill your appliances. Unplug everything.",
  "If you stand in a field during this, Darwin wins.",
  "Thor's hammer is doing overtime tonight.",
  "This storm has the same energy as your ex showing up unannounced.",
  "Lightning outside. Meaning don't stand on your roof being an idiot.",
  "The weather gods are clapping at each other. Stay inside.",
  "Storm surge of drama incoming. Batten down the emotional hatches.",
  "Nature unplugged tonight. Ironically, so should you.",
  "Big sky energy. Bad outdoor energy. Stay the hell home.",
  "This storm didn't come here to make friends.",
  "The thunder is just God's coffee grinder at 3am. Still, stay inside.",
  "Electrical storm: thrilling to watch, deadly to be in. Pick the right one.",
  "Somewhere out there a tree is having a very bad night.",
  "This lightning show is free but the medical bills aren't.",
  "Storm's here. Cancel golf. Cancel everything.",
  "The sky has become aggressively electric. Noted.",
  "A healthy fear of lightning is a sign of intelligence. Have it.",
  "You are not a lightning rod. Do not test that theory.",
  "Thunderstorm spotted. Time to doomscroll from your couch like a smart person.",
  "Rain, lightning, thunder — the full dramatic package. Nature is extra.",
  "The sky is screaming. It's fine. Stay inside and let it scream.",
  "If you hear thunder, lightning already happened nearby. Math is scary.",
  "Apocalyptic skies. Wonderful. Just wonderful.",
  "Storm rolling through like it has a point to prove.",
  "Every bolt is Zeus filing a complaint. Take it seriously.",
  "The atmosphere is vibrating with unresolved tension. Relatable.",
  "Thunderstorm: God's way of making you stay home and be productive.",
  "This is a hard pass for outdoor activities, pal.",
  "Nature's mood tonight: destructive and theatrical.",
  "A storm this dramatic deserves respect, not a selfie from your porch.",
  "Thor's on tour and your neighborhood is the venue. Stay inside.",
  "The sky is trying to electrically apologize for something.",
  "Unplug the fancy stuff. The sky's playing fast and loose tonight.",
  "Your TV doesn't deserve to die in a power surge. Unplug it.",
  "The lightning out there is absolutely not messing around.",
  "Thunderous chaos overhead. Classic. Very on-brand for today.",
  "Sky's throwing sparks. You stay indoors. Simple arrangement.",
  "This storm has audacity. Do not go outside and match it.",
  "Zeus has opinions. They're all happening above your head.",
  "Heavy storm, heavy drama, heavy suggestion to go nowhere.",
  "Nothing inspires staying home like a lightning bolt two blocks away.",
  "You've seen Twister. You know how this goes. Go inside.",
  "The clouds are bringing the noise AND the juice tonight.",
  "Electrical chaos overhead — and your phone has 7% battery. Bold.",
  "Lightning doesn't care about your plans. It has its own agenda.",
  "Storm this big probably has a name. Let it have the spotlight inside.",
  "Atmospheric anger levels: extremely high. Outdoor plans: cancelled.",
  "The thunder is God knocking on the ceiling. Answer by staying inside.",
  "Power flickers incoming. Save your documents. Or don't. Your call.",
  "Sky's doing its terrifying electrical dance. Do not join it.",
  "This storm has better stage presence than most rock bands.",
  "Thunder shaking the windows like it wants a word with you.",
  "Zeus threw the whole bolt. Not a warning shot. The whole bolt.",
  "Good night to stay in. Bad night to be a tall metal object.",
  "Storm's rolling in mean. Don't give it a reason to be mean at you.",
  "Between you and lightning, lightning has more confidence.",
  "Severe thunderstorm vibes. Serve yourself some couch time.",
  "The forecast is: dramatic, electrically dangerous, and absolutely not a BBQ day.",
  "Lightning says hi. From outside. Where you should not be.",
  "Stay in, stay safe, watch Netflix, pretend the thunder is the soundtrack.",
  "Storm of the century. Okay maybe just the week. Still, inside.",
  "Thunderclap so loud your neighbors think the building's falling. It's not. Probably.",
  "Your patio furniture is about to become a projectile. Move it.",
  "If you walk outside right now I will be very disappointed in you.",
  "The storm doesn't care about your delivery order. Neither does the driver now.",
  "Sky's full of lightning and spite. Classic combo.",
  "Mother Nature is cranky. Don't poke the bear.",
  "You ever seen a tree get split in half by lightning? This is that weather.",
  "The atmosphere is fully unhinged tonight. Same energy as your group chat.",
  "Stay the hell inside. The sky is doing something violent.",
  "It's the kind of storm that makes you believe in something.",
  "This electrical business overhead is not your friend right now.",
  "Unplug your stuff, settle in, and watch the light show through glass.",
  "The clouds built up to this all day. They deserve their moment.",
  "Tonight the sky is its own special effects department.",
  "Dramatic storm energy. The night demands you watch from the couch.",
  "Power surge incoming. Your gaming rig fears this night.",
  "If the thunder woke the baby, blame Zeus. Loudly.",
  "Sky's doing electrical work without a permit. Avoid the job site.",
  "Real talk: this weather will eat your umbrella for breakfast.",
  "The only correct outdoor activity right now is running inside.",
  "Your phone charger will survive the night if you stay wise.",
  "Weather like this is why indoor plumbing was invented.",
  "Storm mode: activated. Your chill mode: required.",
  "Big electric sky-tantrum happening. Not your problem if you're inside.",
  "The forecast calls for divine wrath. Cancel the barbecue.",
  "Every tree in the neighborhood is now playing Russian roulette.",
  "Nature's doing its dramatic monologue tonight. Don't upstage it.",
  "Rain and thunder: the dynamic duo of staying home.",
  "Go inside. Charge your phone. Be boring. Live to fight another day.",
  "The storm outside is intense. Your couch is more intense-ly comfortable.",
  "Lightning doesn't ask for permission. So you should ask to go inside first.",
  "The sky is trying out new pyrotechnics. Not a great night to review them live.",
  "Your roof is doing more work tonight than you've done all week.",
  "Rolling thunder means something big is on the way. Go inside now.",
  "The universe is conducting dangerous experiments again.",
  "It's a full biblical-style storm out there. Noah would understand.",
  "Sky looks like the final act of a disaster film. Stay off set.",
  "Electric atmosphere. Literal sense. Move indoors.",
  "If you liked lightning bolts you'd move outside. You don't. Stay in.",
  "Storm big enough to make you feel small. Accept that feeling from inside.",
  "Thunderstorm: 1. Your outdoor plans: 0. It was never a contest.",
  "The sky is on fire. Electrically. Figuratively. Either way: inside.",
  "No amount of 'it looked fine twenty minutes ago' saves you now.",
  "Consider: your house has a roof. The field does not. Choose wisely.",
  "Every thunderclap is a reminder that nature can do whatever it wants.",
  "Sky's in full villain arc tonight. Enjoy watching it from your living room.",
  "God's bowling again. It's a strike. Stay inside.",
  "The lightning out there is aiming, and you'd make a decent target.",
  "This storm has Rotten Tomatoes certified destruction energy.",
  "Weather update: it's dangerous outside. Weather conclusion: don't go there.",
  "Storm so loud your cat is under the bed. Smart cat.",
  "Tonight's lightning count: unknowable. Tonight's inside count: hopefully you.",
  "Thunderstorm clocking in for its shift. Your outdoor shift: cancelled.",
  "Big dramatic sky. Small, fragile you. Do the math.",
  "The storm wants no visitors. Honor that.",
  "Your umbrella is a lightning rod with a handle. Leave it home.",
  "Storm's already flipped someone's trampoline. Just so you know.",
  "Electrical madness above. Total tranquility possible below. Choose below.",
  "If the sky had a Yelp review right now it would be 'not recommended'.",
  "Thunder's rattling the dishes. Your dishes are scared. Listen to them.",
  "This storm wants drama. Give it none by staying indoors.",
  "Stay inside, unplug your crap, and enjoy the free light show from the window.",
  "Lightning is the universe's way of telling you to go sit down.",
  "Every good thunder story starts with 'I was inside when it hit'.",
  "The sky is all thunder and fury, signifying: go the hell inside.",
  "Tonight's vibe: atmospheric violence. Tonight's plan: couch.",
  "Rain and lightning making beautiful chaos. Watch it; don't be in it.",
  "Severe weather advisory from the universe: sit the hell down.",
  "Another day, another storm reminding you nature doesn't care about your schedule.",
  "Storm big enough to impress someone who's seen a lot of storms.",
  "Sky went full supervillain. Stay in your quiet lair.",
  "The forecast is spectacular and terrifying. Mostly terrifying.",
  "Thunderstorm asking nicely-ish for you to remain indoors.",
  "Lightning outside. Battery pack inside. Priorities sorted.",
  "The sky is full of electricity and spite. Don't catch either.",
  "Thunderstorm so loud the neighbors checked their roof. Yours too, probably.",
  "Weather: angry. Outdoor plans: suicidal. Solution: couch.",
  "Zeus hasn't had a good day. Your field is his stress ball tonight.",
  "The lightning is free entertainment. Your deductible is not.",
  "Violent atmospheric drama in progress. You're not in the cast.",
  "The gods are arguing. Let them. Watch from inside.",
  "Storm's knocking. Don't answer.",
  "The sky just called and it's pissed off about something.",
  "Lightning lit up the whole block. Spectacular. Dangerous. Stay inside.",
  "Electrical storm rolling through like a debt collector.",
  "Tonight the sky is doing things lightning does not normally do. Inside. Now.",
  "One good lightning bolt could ruin your whole month. Consider that.",
  "Severe weather means the universe is making a point. Point taken. Indoors.",
  "This storm brought friends: thunder, lightning, and zero chill.",
  "The storm says your outdoor plans are cancelled. The storm wins.",
  "Big, loud, electric night ahead. Not your best night for a walk.",
  "Tonight's weather: yes, it will hit you if you go out there.",
  "Stay inside and let the storm have its thing.",
  "If lightning had feelings, it'd want you to stay inside so it could perform freely.",
  "Thunder clapping so hard the neighbors think there's a concert.",
  "The storm is doing what storms do. You should do what smart people do: stay in.",
  "Full electrical chaos outside. Full stupid potential if you go out there.",
  "Zeus is giving a live performance. It's not a meet-and-greet.",
  "The sky wrote 'do not enter' in lightning. Read the sign.",
  "Every tree outside just drew the short straw. Don't join them.",
  "Storm this strong has a personality. It's not a friendly one.",
  "The electrical display overhead is impressive and lethal. Both things.",
  "Thunderstorm making your neighborhood briefly exciting. Watch from indoors.",
  "Bolts from the sky: nature's way of saying 'not today'.",
  "Thor is the mood of this storm. Loud, powerful, vaguely Norse.",
  "This storm hit the gym. It shows.",
  "Sky's throwing punches tonight. Duck inside.",
  "Nothing says 'stay home' quite like a sky full of lightning.",
  "Thunderstorm so classic it should have its own Spotify playlist.",
  "The storm is all business tonight. Your outdoor business: postponed.",
  "Voltage in the air high enough to make your hair stand up — from inside.",
  "Heavy lightning activity. Translation: don't be a tree or a fool tonight.",
  "The sky is absolutely going off and you should absolutely not be under it.",
  "Tonight's storm has more energy than you've had all month.",
  "Thunderstorm so severe even the weather app looks stressed.",
  "Nature is having its loudest argument since last season.",
  "The flash-bang show up there is live and free but lethal. Watch from a window.",
  "Grab a blanket, let the storm do its thing, pretend you're in a movie.",
  "This is precisely the weather that makes power strips nervous.",
  "If you own a boat, it is having a worse night than you are.",
  "Storm clocking in with full commitment. Your outdoor plans: clocking out.",
  "The sky said 'hold my beer' and then proceeded to do all of this.",
];
