export const WARM: readonly string[] = [
  "Genuinely nice out. Go touch some grass.",
  "Warm and lovely. Try not to squander it indoors, you gremlin.",
  "Perfect 'day-drink on a patio' weather.",
  "It's nice enough that even you should go outside.",
  "T-shirt weather. Don't screw it up.",
  "The sun is showing off. Let it.",
  "Shorts weather, baby. Don't overthink it.",
  "Crack a beer. It's actually nice out for once.",
  "Warm enough to pretend you have a social life.",
  "The first legitimately nice day in a while. Try not to waste it on your couch.",
  "It's a patio day. You've earned it.",
  "Almost too warm, but actually just right. Like Goldilocks, but with sweat.",
  "Your flip flops have been waiting for this moment all year.",
  "This is the 'windows down on the highway' temperature. Do it.",
  "Sunscreen is still on the table. Just a thought.",
  "It's nice out. Don't ruin it by staying inside.",
  "Mild swamp-ass detected. Breathable fabric recommended.",
  "Finally, you can stop bitching about the cold. Now you can bitch about the heat.",
  "You're one cold drink away from a great afternoon.",
  "The grill is basically legally required to be used in this weather.",
  "Nice enough to go outside. Warm enough that you'll still complain.",
  "You could sit on a patio for hours. Or you could sit inside and feel like an idiot.",
  "Summer's making its case. Weakly defending it, but still.",
  "The kind of warm that gets you laid if you play your cards right.",
  "Your SPF 30 is fine. Your SPF 0 is a gamble. Pick wisely.",
  "Even your dog wants to go outside today. And your dog has opinions.",
  "A light layer in the morning, topless by afternoon. That's the forecast.",
  "This is the weather people move to warm climates for. You've achieved it.",
  "The park is calling. Your couch is whispering. Trust the park.",
  "Perfectly warm, lightly sticky, and entirely tolerable.",
  "This is the 'finally not wearing a coat' promised land. Welcome.",
  "Your hair looks better in warm weather. Accept the compliment.",
  "Sun's out, ass out? Optional. But noted.",
  "Not too hot, not too cold. Just warm enough to generate mild swamp-ass and call it a day.",
  "The evening will be perfect. Just wait for it.",
  "Iced coffee weather. You've made the right choice.",
  "Your pores are happy for the first time in months.",
  "This is 'take a walk and feel superior to people still inside' weather.",
  "A nap with the windows open is available to you right now. Seize it.",
  "Even the vibe outside is good today. Don't ask questions.",
  "Sunburn is a risk. A badge of honor, kind of. Definitely a risk.",
  "It's warm enough to be nice and not hot enough to ruin it. The sweet spot.",
  "Your sandals are back, baby. Toenail check was last week. No refunds.",
  "Light sweat, good times, no real complaints. Except from you, probably.",
  "This is the weather that makes you forget winter ever happened. Until November.",
  "Outdoor brunch has never been more justified. Order a Bloody Mary.",
  "The sun is doing a great job today. Tip your server.",
  "Your car is warm but not a death trap. Progress.",
  "Ideal conditions for a cold beer and poor decision-making.",
  "The kind of warm that makes every outdoor plan seem brilliant.",
  "Pack a bag, go somewhere. You don't need a plan, just momentum.",
  "Even errands feel okay today. Briefly. Very briefly.",
  "Your linen shirts have been waiting patiently. Their time has come.",
  "This is pool weather. Someone with a pool owes you an invitation.",
  "Warm and comfortable enough to enjoy the outdoors like a functional adult.",
  "The weather is doing its part. You're the variable.",
  "Even a light sweat is proof you were living, not just existing.",
  "This is 'happy hour is outside now' weather.",
  "Your mood improved the second you stepped outside. Own that.",
  "Shorts are not just appropriate, they're required today.",
  "This is the weather that belongs in a coming-of-age movie montage.",
  "Warm enough to need deodorant. Cool enough that it still works.",
  "It's giving 'long afternoon with nowhere to be' energy.",
  "The birds are happy, the breeze is real, and you've got options.",
  "A hoodie in the shade, nothin' in the sun. That's the ideal outfit strategy today.",
  "Sunglasses on. Attitude acquired. Weather approved.",
  "The humidity is present but not aggressive. Call it 'politely damp.'",
  "Today you can actually appreciate being alive. Use it.",
  "Your sweat is appropriate and proportionate. It's fine.",
  "The grill should be going. If it's not, start the damn thing.",
  "This is 'leave work five minutes early and no one can stop you' weather.",
  "Mild sunburn is a love letter from the sun. A slightly painful one.",
  "Your ice cream melts in five minutes. That's peak summer.",
  "Even the bees seem chill today. Don't push it.",
  "Nature is good today. Don't read the news. Just be in it.",
  "You don't need to be doing anything important. Just be warm and outside.",
  "Warm enough for a light sweat, cool enough for dignity. Mostly.",
  "Today feels like a baseball game, a cooler, and terrible decisions that become great stories.",
  "Convertible weather. For those who have convertibles. Smug bastards.",
  "A cold drink, warm sun, and zero obligations. Fictional ideal or your actual afternoon?",
  "Wear the outfit. Take the pic. Post it. Own the warm-weather moment.",
  "The kind of day where you sit outside and accidentally stay for four hours.",
  "Mild enough to enjoy. Warm enough to feel it. Perfect range.",
  "Even your morning commute isn't awful today. The bar is low. But still.",
  "You can walk to wherever you're going and actually enjoy it. That's notable.",
  "Outside is good today. Repeat: outside is good today.",
  "Light and breezy vibes punctuated by mild regrets. That's summer in the sweet zone.",
  "You deserve a long lunch somewhere with a patio. Take it.",
  "Your mood has been directly improved by UV exposure. Science agrees.",
  "A nap in the hammock is both allowed and encouraged by the weather gods.",
  "Warm enough that 'going for a walk' sounds appealing and not like punishment.",
  "The back porch is open for business. BYOB and a decent attitude.",
  "You could go for a run today and not die. If you're into that.",
  "Your sunscreen is optional but smart. Your beer is mandatory but questionable.",
  "Light jacket in the morning. Bold decision by afternoon. Great story either way.",
  "The breeze is real, the shade is available, and life is briefly acceptable.",
  "Perfect weather to make outdoor promises you'll forget by Monday.",
  "Your cold drink is sweating. A solidarity sweat. Comrades.",
  "Even the grass looks good today. The grass, man.",
  "Tee-shirt weather with a mild side of 'maybe don't sit in the sun for four hours.'",
  "This is the kind of day that makes warm-climate people insufferable. You're one of them now.",
  "Breezy and warm, like a good conversation with someone you actually like.",
  "Your whole body is convinced this is a good idea. Follow your whole body.",
  "Patio seating is no longer a gamble. Today it pays off.",
  "Warm enough to get a little pink. Not hot enough to get crispy. Stay in that range.",
  "Good weather for bad decisions made outdoors. The best kind.",
  "Lawn chair or hammock. Either is correct. Both involve cold beverages and sunshine.",
  "You're outside and you feel fine. Write that down. That doesn't happen often.",
  "A tee shirt, cold drink, and zero responsibilities is a peak human experience.",
  "Even a light jog doesn't sound terrible today. Who are you becoming?",
  "Farmers markets, street festivals, patio brunches. All viable. All yours today.",
  "The kind of warm that makes a Frisbee seem like a reasonable activity.",
  "Your deodorant is holding. Respect that relationship.",
  "Summer's best offering before it goes full asshole. Savor it.",
  "Shorts and sunglasses, cold beverage, nowhere specific to be. That's the brief.",
  "Even the parking lot is fine today. The parking lot. That's something.",
  "You're warm, hydrated, and mildly content. That's a rare combination.",
  "Light sweat, warm sun, cold beer. The holy trinity of a good afternoon.",
  "Your dog wants to go outside. Your dog is correct about this.",
  "This weather doesn't need to be fixed. Don't try to improve it.",
  "Today's conditions: perfect for skipping the gym and going to a park instead.",
  "The kind of day that makes you feel like you're good at summer.",
  "Cold pool, warm sun, beer in hand. You've cracked the code.",
  "Someone's cooking out nearby. You can smell it. That person has their life together.",
  "Even your commute home is pleasant. Who are you and what have you done?",
  "Warm and breezy is the setting. Terrible decisions are the outcome. Enjoy.",
  "Mild enough to sit outside. Warm enough to appreciate the shade.",
  "Your linen pants were waiting for exactly this moment.",
  "Just warm enough to break a slight sweat doing nothing. Summer's checking in.",
  "This is 'sit on a friend's porch for six hours and not notice the time' weather.",
  "Sunset tonight is going to be ridiculously good. Plan for it.",
  "Perfect conditions for underestimating how much sun you're getting. Wear sunscreen.",
  "Even getting the mail is a brief pleasure today. Don't tell anyone.",
  "If you're inside right now, close this app and go outside immediately.",
  "This is the 'you'll miss this in January' weather. Remember that.",
  "You can grill out, sit out, hang out, or just take the fuck out. All valid.",
  "Your social obligations feel less painful in this weather. Answer a text.",
  "Light, easy, warm, and completely agreeable. That's today's whole deal.",
  "Even the bugs aren't awful today. For now.",
  "The beach, the park, the backyard, or a parking lot tailgate. All venues valid today.",
  "Today's weather is rated 'PG-13 for mild swamp-ass and language.'",
  "Your whole energy improves by twenty percent in this weather. Tested and proven.",
  "A cold drink in one hand and nothing in the other is a valid plan.",
  "Warm enough for summer clothes, cool enough to keep them on.",
  "The vibe is immaculate and you deserve it after winter.",
  "Even the slightly annoying people in your life seem tolerable today. Warm weather is a drug.",
  "Sunglasses mandatory. Attitude optional. Ice cream strongly advised.",
  "This is 'text someone you haven't texted in a while' weather. Just a vibe.",
  "The world looks better in warm weather. That's not up for debate.",
  "You're in a pleasant sweat. The respectable, earned kind.",
  "Warm, slightly damp, and completely alive. That's the forecast.",
  "Today you get to be the outdoor person. Own it.",
  "You could take a nap outside and it would be the best nap of your year.",
  "This is the weather that makes you promise yourself you'll be outside more. You won't. But still.",
  "A cold beer and some shade is a complete and total life plan right now.",
  "Warm enough for ice cream, cool enough to eat it before it becomes soup.",
  "Even the neighbors are out. The neighbors. This means something.",
  "It's warm. It's nice. It's not complicated. Just go outside.",
  "The breeze is the unsung hero of today's weather situation.",
  "You're sweating just enough to feel like you did something. You did not. You sat in a chair.",
  "Warm weather makes bad ideas seem great. That's a warning and a permission slip.",
  "Today is for slow mornings, cold coffees, and not answering emails.",
  "Your shorts situation is fully justified. No notes.",
  "Light humidity, warm breeze, cold drink. That's the whole equation.",
  "Even traffic is okay in this weather. Actually no, traffic is still garbage. But the weather's nice.",
  "Wear sunscreen so you can enjoy tomorrow without looking like a lobster.",
  "The day is long, the weather is good, and your obligations are temporary.",
  "Warm enough that winter feels like a myth you made up.",
  "Your outdoor voice is appropriate today. Use it somewhere actually outside.",
  "The patio is where you belong today. Trust the instinct.",
  "Mild and gorgeous, like a person who actually has their shit together.",
  "Warm enough to break a sweat throwing a ball around. Throw a ball around.",
  "Your sunglasses tan is coming in. Make it count.",
  "It's warm and real and outside is good. That's the whole status report.",
  "The sun is being responsible today. Appreciate it while it lasts.",
  "Today has 'remember this when it's February' written all over it.",
  "Outdoors is fully unlocked today. No conditions, no restrictions.",
  "Warm enough to want ice cream but not so hot that ice cream is survival gear.",
  "Take the long way. Walk around a bit. This weather supports that kind of nonsense.",
  "Even the work-from-home crowd is going outside today. That's saying something.",
  "Your sunburn will be funny to your future self. Your present self should still use SPF.",
  "It's pleasant. Genuinely pleasant. Don't look for problems.",
  "Your cold drink will stay cold for a reasonable amount of time. Progress.",
  "Warm without being punishing. Summer is being a reasonable adult for once.",
  "Today's vibe: outdoor furniture, cold can, no obligations, light breeze. Go get it.",
  "Somewhere between 'finally' and 'too soon.' It's perfect right now.",
  "Even bad ideas seem okay in this weather. Execute them responsibly.",
  "Your whole neighborhood smells like someone grilling. Investigate.",
  "Today's weather is a green light and you've been waiting for this.",
  "Cool enough to stay in your clothes. Warm enough to want to take them off.",
  "Warm, breezy, and mildly illegal in terms of how good it is outside.",
  "You'll sleep well tonight because of how much sun you accidentally absorbed today.",
  "This is not a drill. The weather is actually nice. Go do something about it.",
  "Warm enough to enjoy a long walk. Cool enough that the walk is actually enjoyable.",
  "Even your introversion isn't winning today. Outside is winning.",
  "This is the weather that belongs in a montage. Become a montage.",
  "Mild swamp-ass: present. Mild good vibes: also present. Balance achieved.",
  "The whole outdoors is a solid option today. Pick a part of it.",
  "Even the weird neighbors are outside. It's a block party waiting to happen.",
  "Your cold beverage just sweated on the outside. Perfect summer aesthetic.",
  "This is 'say yes to more things' weather. Say yes to more things.",
  "Light, warm, genuine. That's the temperature and also a good personal brand.",
  "Even your feet are happy today. And feet are never happy.",
  "Warm and kind. Like good weather should be. Like summer rarely is.",
  "SPF and hydration. Then the rest is just good times.",
  "Your sunglasses are earning their keep today. Thank them.",
  "It's warm. It's beautiful. It's going to get hot soon. Soak this up.",
  "Today requires nothing but presence and a cold drink. Consider both supplied.",
  "The sky is doing something nice. Look up occasionally.",
  "Your lawn chair is your office, the kitchen is irrelevant, and your beer is cold. Work from home achieved.",
  "Outside is excellent right now. This is a limited time offer.",
  "A slight sweat, a real smile, and nowhere to be. That's the data.",
  "This is the weather version of finding a twenty in your old jeans. Just enjoy it.",
  "Warm enough that being outdoors is a reward, not a sentence.",
  "Your outdoor plans have a 100% approval rating from the weather. Rare.",
];
