export const WIND: readonly string[] = [
  "It's blowing like a bastard out there. Hold onto your hat.",
  "Windy as hell. Your hair is a lost cause today.",
  "Wind strong enough to steal your soul and your napkins.",
  "Gusty as fuck. Trash cans are becoming projectiles.",
  "The wind is personally attacking you today. Lean into it.",
  "Your umbrella is going to invert and die today. It's been a good umbrella. Respect the sacrifice.",
  "The gusts have an agenda and your face is on it.",
  "Wind speed: impressive. Your outfit: insufficient armor.",
  "Hold your keys, hold your coffee, hold on for dear life.",
  "This wind said 'doors? I'll handle those' and meant it.",
  "Anything not tied down is now a weather projectile. Duck.",
  "The kind of wind that makes strangers bond over mutual hat-chasing.",
  "Your hair? Gone. Your dignity? Also gone. Your receipt? On the next block.",
  "Gusts are clocking in at 'extremely rude' today.",
  "The wind is showing off. It doesn't need your approval.",
  "Tie everything down or watch it become someone else's property.",
  "The trees are doing yoga they didn't sign up for.",
  "This isn't a breeze. This is a hostile takeover.",
  "Your umbrella stood no chance. It knew it stood no chance. It sacrificed itself anyway.",
  "Napkins, receipts, wigs: all airborne. Welcome to the forecast.",
  "The wind is not asking permission. It is informing.",
  "If you brought a hat, it's on the next block. If you didn't: condolences to your ears.",
  "Gusting enough to make you walk at a forty-five degree angle. Respect the lean.",
  "This wind has places to go and it's taking your stuff with it.",
  "Signs are swaying. Doors are fighting back. Your jacket is flapping like a flag of surrender.",
  "Horizontal is the new direction of everything today.",
  "Trash day plus wind equals chaos. Nature is producing content.",
  "Your carefully styled hair is now modern art. And not the good kind.",
  "The wind picked up your plans for today and carried them to the next state.",
  "Anything over twenty mph and it's officially a fight. You're in a fight.",
  "Step outside and immediately say things you've never said to weather before.",
  "The wind is getting paid overtime today. You can tell.",
  "Blustery is the polite way to say 'your sunglasses are flying into traffic.'",
  "This wind has audacity, ambition, and your lunch receipt.",
  "Even birds are choosing not to fly today. That is a data point.",
  "The gusts are strong enough to redecorate your neighbor's yard.",
  "You'll spend more time fighting your jacket than wearing it.",
  "Hold everything important at all times. Assume nothing is secured.",
  "The wind is testing the structural integrity of everything in your path.",
  "Your patio furniture is in motion. Hopefully you like your neighbor.",
  "The weather became a personality and today that personality is aggressive.",
  "Every door you open today is going to have thoughts. Strong ones.",
  "Windy enough to justify the train. Even if you love driving.",
  "You'll hear yourself thinking 'this is insane' about thirty seconds in. Correct.",
  "The wind hit 'peak annoyance' around 8 AM and has been sustaining since.",
  "Your coffee lid is not a guarantee today. Cover it with your hand.",
  "Outdoor dining: absolutely not. The wind made that decision for you.",
  "Secure the kids, secure the pets, secure the hat. In that order.",
  "The trees look stressed. That's because they are.",
  "Gusts like these are what awnings dread every night.",
  "Your carefully placed sign is now two blocks east. Good luck.",
  "Wind with this attitude should be required to pay for whatever it breaks.",
  "You'll be walking into this wind like it owes you money. It doesn't.",
  "Everything light is now airborne. Everything heavy is now a hazard.",
  "The forecast: windy as hell with a strong chance of napkin loss.",
  "Step outside and immediately become an involuntary participant in the weather.",
  "Your jacket will billow. Your ego will struggle. Your hair will not recover.",
  "These gusts are the reason humans invented buildings.",
  "The wind today has chosen violence and is committed to it.",
  "Even the flags are exhausted. They've been at full extension for three hours.",
  "Hold on to loose items like your job depends on them. Actually your job might.",
  "This wind woke up angry and has not calmed down since.",
  "Doors are slamming themselves. Curtains are horizontal. It is a vibe.",
  "Gusting enough to make a grown-ass adult say 'whoa' immediately.",
  "Whatever music you're playing through earbuds is now competing with the wind for volume.",
  "The wind has been hired as today's main character. Everything else is a prop.",
  "Your umbrella is already a liability before you've opened it.",
  "Lids, hats, papers, dignity: all subject to departure at any moment.",
  "The wind is reading your plans for today and laughing.",
  "It's blowing hard enough that walking requires extra caloric expenditure.",
  "Trees bending, fences creaking, your resolve tested.",
  "Forecast: sustained gusts with a high probability of regretting your hairstyle choice.",
  "The wind is exercising its right to be a complete pain in the ass.",
  "Trash cans down the block are having a meeting. A mobile one.",
  "Forty mph gusts are nature's way of saying 'stay inside, dummy.'",
  "The wind isn't a breeze anymore. It's commentary.",
  "Your hair products cannot help you today. No products can help you today.",
  "Blustery is a word invented by people who experienced exactly today and survived.",
  "Every lightweight object in a two-mile radius is now a ballistic.",
  "You'll spend the entire commute horizontal against the gusts. Great cardio.",
  "The wind today is not decorative. It is structural.",
  "Squint into the wind. Walk forward. Pretend it's character-building.",
  "Seriously, hold your hat down with your hand. Don't trust the hat alone.",
  "Today's wind is sponsored by chaos and it's meeting its deliverables.",
  "The gusts hit like a reminder that nature runs this place, not you.",
  "Even kite enthusiasts looked outside and thought 'bit much.'",
  "Your sunglasses are going to fly off your face. Transition lenses would have survived.",
  "The wind tore through like it missed a meeting and is making up for lost time.",
  "Your jacket is billowing enough to generate lift. Zip it up.",
  "The outdoor seating at every cafe just got quietly moved inside.",
  "Wind strong enough to start a conversation with every stranger it blows into you.",
  "Sustained gusts mean sustained attitude. And this attitude is combative.",
  "The wind picked today to become a main character. Respect the commitment.",
  "Flowers in the yard? Exciting, because two of them are about to visit your neighbor.",
  "Your hood is now either your best friend or your enemy. It decided to be your enemy.",
  "The kind of wind that makes your eyes water just from the audacity of it.",
  "Things taped to walls, staked in yards, parked on ledges: all in jeopardy.",
  "Windy enough that staying on your feet requires genuine intent.",
  "Even your dog is giving you a 'not today' look through the window.",
  "If your gate's unlatched, it's unlatched and angry and swinging.",
  "This wind left its mark on every person who went outside today. Ask them.",
  "The gusts don't care about your plans, your schedule, or your umbrella investment.",
  "Whatever direction you're walking, the wind is in your face. Scientifically proven.",
  "Forty-degree gusts are the universe's way of enforcing humility.",
  "The wind turned the whole outdoors into a wind tunnel without asking.",
  "This is a Wizard of Oz situation. Anything not nailed down is going to Kansas.",
  "Strong gusts, bad hair day, existential wonder at what you're doing outside.",
  "The wind is doing the most and asking for no credit.",
  "Your coffee is going to cool in sixty seconds flat if you take it outside.",
  "Hold the railing. Hold your hat. Hold your life together. In that order.",
  "This wind is making promises it intends to keep: about your hair, your hat, your patience.",
  "You will be humbled by this wind. It's not personal. It's meteorological.",
  "If it's this windy, the weather owes you an apology and a new umbrella.",
  "The outdoor concert should have been moved inside an hour ago.",
  "Wind whipping with enough force to renegotiate the terms of your morning plans.",
  "The gusts are ambitious today. Bigger than yesterday, louder than tomorrow.",
  "Sideways rain isn't just possible today. It's the expected experience.",
  "Every door hinge in this city is working overtime right now.",
  "The wind took one look at your to-do list and blew it into the highway.",
  "A sustained gust hits and suddenly everyone outside is briefly the same person: bent forward.",
  "Your carefully sorted trash and recycling bins are now colleagues again. And airborne.",
  "Gusts this strong are technically redecorating neighborhoods without permits.",
  "Walk into this wind and immediately look like you're arguing with the sky.",
  "The wind wants everyone to know it exists today. Message received, wind. Message received.",
  "Even the stubborn old oak in the park is having second thoughts.",
  "Wind advisory: your hat is not safe. Your sanity is not safe. Nothing is safe.",
  "The wind gusted and a small piece of your soul flew off with it.",
  "This is what 'hold on tight' was invented for.",
  "Your mail may be in the neighbor's yard by the time you get home.",
  "Gusts strong enough to make walking a genuinely athletic endeavor.",
  "The trees aren't waving hello. They're waving goodbye to their dignity.",
  "Every light object is a flying object now. Eyes forward, head down, hustle.",
  "The wind declared war on loose hair ties today. Yours already surrendered.",
  "Forty-plus gusts mean your planned outdoor coffee is now an indoor emergency.",
  "The wind is blowing through this city like it arrived via personal grievance.",
  "Today the wind does whatever it wants and there's not a damn thing you can do.",
  "Your hoodie strings are going to blind you. Tie them or lose an eye.",
  "Blustery as absolute hell and then some.",
  "Even Zeus is side-eyeing this wind and he invented wind.",
  "The gusts have gale-force energy and gale-force opinions about where your things belong.",
  "Pick up loose items in the yard or play a fun game of 'find my things tomorrow.'",
  "The wind is the weather's way of saying 'I do what I want.'",
  "Outdoor furniture has officially become indoor furniture as of this morning.",
  "You'll lose something today. Not sure what. But the wind has already decided.",
  "Walking against this wind is a workout. Log it. You earned those calories.",
  "The gusts are operating at 'maximum disrespect' today.",
  "Things left on porches are now someone else's problem. The wind distributed them.",
  "It's so windy your jacket billows like a cape. You are, briefly, a wind-based superhero.",
  "Even solid things are doubting themselves in this wind.",
  "Hold your documents. Hold your hat. Hold your entire external existence together.",
  "The wind is sending everything on an adventure whether it consented or not.",
  "This wind is not a metaphor. It's a physical force that wants your stuff.",
  "By the time you get inside, you'll have the hair of someone who just fought the sky.",
  "Gusts loud enough to make phone calls impossible outside. Consider it a gift.",
  "Everything you left on the porch is already in a new zip code.",
  "Wind this strong has a name. Today's name is 'your problem.'",
  "Lean into the gusts or they'll knock you off your feet. Literally.",
  "You'll spend more energy fighting the wind than doing whatever you went outside for.",
  "The wind made the trees into a percussive instrument all night. Did you notice?",
  "Look outside. Watch that plastic bag go. That bag is free now. You are not.",
  "This wind doesn't need your cooperation. It already has your things.",
  "Gusts strong enough to make street signs change their mind.",
  "Hair gel is not equipped for this fight. Neither is mousse. Nothing is.",
  "Hold your hat not just with your hand but with your will to survive.",
  "The wind is doing structural damage to your hair and your confidence.",
  "Every gust sounds like nature is trying to close a very old, very large door.",
  "Tie down the trash bins or listen to them escape at 3 AM. Either way.",
  "It's blowing strong enough that stepping outside requires a strategy.",
  "Your hood won't stay up. Your umbrella won't stay open. This is the wind's victory.",
  "The wind has no preference for what it takes. It is democratically chaotic.",
  "This forecast is literally 'hold the fuck on.'",
  "Your sidewalk is hosting a trash tornado courtesy of wind and bad timing.",
  "Things that blow away today: hat, receipt, faith in outdoor activities.",
  "Gusts have been verified at 'absurdly, personally offensive.'",
  "The wind hit fifty mph somewhere in this county and it is still going.",
  "Your outdoor plans just got overruled by the atmosphere.",
  "Walk outside and immediately become the person squinting into the wind in every movie.",
  "The wind has goals today. None of them are compatible with yours.",
  "Sustained gusts are not a phase. They're a whole-day commitment from the atmosphere.",
  "Outside is loud and combative and the wind is winning.",
  "Even your sturdy umbrella is nervous today. That should alarm you.",
  "The wind doesn't care about your umbrella investment. At all.",
  "Your morning commute has been reclassified as a weather experience.",
  "Everything swings, everything rattles, everything not nailed down is now airborne.",
  "A forty mph gust is the universe explaining that you're not the main character.",
  "This wind has been practicing all night and it shows.",
  "The trees are in full lurch today. That's a technical meteorological term for 'oh shit.'",
  "If your ladder is still outside: bring it in. Right now. I'll wait.",
  "The gust blew past and your plans blew with it. Adjust.",
  "Sustained wind at this level is what makes people move to calmer places.",
  "Your fence post is about to have an opinion it's never had before.",
  "This wind is writing the story today. You're a minor character.",
  "Forty-plus gusts: the official speed at which humans start swearing involuntarily.",
  "Even the flags are like 'okay, we get it, enough.'",
  "The wind advisory was not dramatic. In fact, it was underselling it.",
  "Your carefully considered ponytail is now an avant-garde wind sculpture.",
  "If something's not bolted down, the wind just did you a favor in identifying that.",
  "Hold on, lean forward, and accept that you are in a fight with the sky today.",
  "The wind is the boss today. Dress appropriately. Argue later.",
  "Even Aeolus thinks this particular gust sequence is a bit excessive.",
];
